<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-17">
<meta name="description" content="Part 6 tests whether richer predictors help once they are allocated across the level, persistence, and innovation-share channels of PGARCH, and finds an informative intermediate result rather than a finished benchmark win.">

<title>Volatility Forecasts (Part 6: Structured PGARCH Feature Allocation) – Steve Yang</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-html-eb71d4f0124c4d5ff63526840ab633f6.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<style>html{ scroll-behavior: smooth; }</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body>

<nav class="site-nav">
  <a href="../../">Home</a>
  <a href="../../pages/series.html">Series</a>
  <a href="../../pages/projects.html">Projects</a>
  <a href="../../pages/categories.html">Categories</a>
  <a href="../../pages/about.html">About</a>

  <span class="site-nav-spacer"></span>
  <a href="../../pages/search.html">Search</a>
</nav>

<header id="title-block-header">
<h1 class="title">Volatility Forecasts (Part 6: Structured PGARCH Feature Allocation)</h1>

<p class="date">2026-03-17</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>

  <ul>
  <li><a href="#introduction" id="toc-introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#why-part-6-exists" id="toc-why-part-6-exists"><span class="header-section-number">2</span> Why Part 6 Exists</a></li>
  <li><a href="#model-roadmap" id="toc-model-roadmap"><span class="header-section-number">3</span> Model Roadmap</a>
  <ul>
  <li><a href="#the-pgarch-recursion" id="toc-the-pgarch-recursion"><span class="header-section-number">3.1</span> The PGARCH Recursion</a></li>
  <li><a href="#the-part-6-ladder" id="toc-the-part-6-ladder"><span class="header-section-number">3.2</span> The Part 6 Ladder</a></li>
  </ul></li>
  <li><a href="#feature-universe-and-taxonomy" id="toc-feature-universe-and-taxonomy"><span class="header-section-number">4</span> Feature Universe and Taxonomy</a></li>
  <li><a href="#evaluation-standard-and-experimental-design" id="toc-evaluation-standard-and-experimental-design"><span class="header-section-number">5</span> Evaluation Standard and Experimental Design</a>
  <ul>
  <li><a href="#what-counts-as-success" id="toc-what-counts-as-success"><span class="header-section-number">5.1</span> What Counts as Success</a></li>
  <li><a href="#part-6-variants" id="toc-part-6-variants"><span class="header-section-number">5.2</span> Part 6 Variants</a></li>
  </ul></li>
  <li><a href="#main-results-summary" id="toc-main-results-summary"><span class="header-section-number">6</span> Main Results Summary</a></li>
  <li><a href="#statistical-comparison" id="toc-statistical-comparison"><span class="header-section-number">7</span> Statistical Comparison</a>
  <ul>
  <li><a href="#reading-the-dm-tests" id="toc-reading-the-dm-tests"><span class="header-section-number">7.1</span> Reading the DM Tests</a></li>
  </ul></li>
  <li><a href="#channel-diagnostics" id="toc-channel-diagnostics"><span class="header-section-number">8</span> Channel Diagnostics</a></li>
  <li><a href="#coefficient-and-allocation-diagnostics" id="toc-coefficient-and-allocation-diagnostics"><span class="header-section-number">9</span> Coefficient and Allocation Diagnostics</a></li>
  <li><a href="#nonlinear-preview-and-boundary-of-part-6" id="toc-nonlinear-preview-and-boundary-of-part-6"><span class="header-section-number">10</span> Nonlinear Preview and Boundary of Part 6</a></li>
  <li><a href="#what-part-6-actually-learned" id="toc-what-part-6-actually-learned"><span class="header-section-number">11</span> What Part 6 Actually Learned</a></li>
  <li><a href="#limitations" id="toc-limitations"><span class="header-section-number">12</span> Limitations</a></li>
  <li><a href="#handoff-to-part-7" id="toc-handoff-to-part-7"><span class="header-section-number">13</span> Handoff to Part 7</a></li>
  <li><a href="#appendix-implied-garch-parameters" id="toc-appendix-implied-garch-parameters"><span class="header-section-number">14</span> Appendix: Implied GARCH Parameters</a></li>
  </ul>
</nav>
<h2 data-number="1" id="introduction" class="anchored"><span class="header-section-number">1</span> Introduction</h2>
<p>Part 5 left the PGARCH branch open but unresolved. The three-channel <code>PGARCH-L</code> decomposition improved QLIKE relative to the earlier STES family and directionally improved on <code>GARCH(1,1)</code>, but it did not clear the series decision rule on its own. At the same time, the earlier feature-expansion work showed that simply widening the predictor set inside a single STES gate was not enough to create a useful forecasting gain.</p>
<p>Part 6 sits between that simpler PGARCH result and the broader Part 7 search. Its role is narrower than a final model-selection post. This is the step where the PGARCH line is expanded beyond the Part 5 formulations and asked a specific question: if the predictor set is made materially richer, does the predictive-GARCH recursion improve once those predictors are allowed to affect different structural channels rather than one common gate?</p>
<p>The answer in this notebook is disciplined but mixed. The all-feature linear PGARCH variants do not beat the Part 5 <code>PGARCH-L</code> baseline, and none of the expanded linear variants clears <code>GARCH(1,1)</code> under the Part 6 protocol. That negative result matters. It shows that richer information alone is not enough. At the same time, the exercise clarifies where richer predictors plausibly belong inside the recursion, exposes the limits of regularization-only allocation, and identifies the nonlinear XGBPGARCH line as the natural next search step rather than a solved endpoint.</p>
<p>The notebook therefore does four things in sequence. It places Part 6 inside the series, lays out the channel-based model roadmap and evaluation standard, summarizes the forecasting evidence, and then reads the diagnostic results that motivate Part 7.</p>
<h2 data-number="2" id="why-part-6-exists" class="anchored"><span class="header-section-number">2</span> Why Part 6 Exists</h2>
<p>This post is the expansion step inside the PGARCH branch of the series. Part 5 worked with a small return-based feature set and asked whether the predictive-GARCH decomposition itself helped. Part 6 keeps the dataset, target, benchmark, and train/test protocol fixed, but expands the PGARCH line along a different axis: richer predictors and richer allocation across the level <span class="math inline">\mu_t</span>, persistence <span class="math inline">\phi_t</span>, and innovation-share <span class="math inline">g_t</span> channels.</p>
<p>That placement matters for interpretation. Part 6 is not meant to settle the full expanded-feature problem. It is an intermediate result. The goal is to see whether a more structured linear PGARCH specification can turn the earlier feature-expansion idea into a benchmark-relevant forecasting gain, or whether the branch still needs a broader search over feature compression, nonlinear channel updates, or both.</p>
<p>The right public reading is therefore conservative. A positive finding here would mean that the expanded PGARCH line remains active under the Part 6 protocol. A negative finding would still be useful if it clarified which types of richer structure were worth carrying into Part 7.</p>
<h2 data-number="3" id="model-roadmap" class="anchored"><span class="header-section-number">3</span> Model Roadmap</h2>
<h3 data-number="3.1" id="the-pgarch-recursion" class="anchored"><span class="header-section-number">3.1</span> The PGARCH Recursion</h3>
<p>The PGARCH model defines the one-step-ahead variance forecast as</p>
<p><span class="math display">
h_{t+1} = (1 - \phi_t)\,\mu_t + \phi_t\,q_t, \qquad q_t = g_t\,y_t + (1 - g_t)\,h_t
</span></p>
<p>where <span class="math inline">y_t \ge 0</span> is the realized target, <span class="math inline">h_t</span> is the current variance forecast, and the three structural parameters are interpreted as follows. The level channel <span class="math inline">\mu_t</span> sets the anchor toward which variance mean-reverts. The persistence channel <span class="math inline">\phi_t</span> controls how strongly the recursion leans on that anchor versus the internal update. The innovation-share channel <span class="math inline">g_t</span> controls how aggressively new information is absorbed into the recursion.</p>
<p>In <code>PGARCH-L</code>, each channel is a linear function of predictors passed through a link that enforces admissible values:</p>
<p><span class="math display">
\mu_t = \mu_{\min} + \text{softplus}(\tilde{x}_{t-1}^\top w_\mu), \qquad
\phi_t = \phi_{\min} + (\phi_{\max} - \phi_{\min})\,\sigma(\tilde{x}_{t-1}^\top w_\phi), \qquad
g_t = g_{\min} + (g_{\max} - g_{\min})\,\sigma(\tilde{x}_{t-1}^\top w_g)
</span></p>
<p>The important modeling detail for Part 6 is that the current <code>PGARCHLinearModel</code> passes the same feature matrix to all three channels. Differential shrinkage is therefore a disciplined first attempt at channel allocation, not a hard architectural separation.</p>
<h3 data-number="3.2" id="the-part-6-ladder" class="anchored"><span class="header-section-number">3.2</span> The Part 6 Ladder</h3>
<p>The progression into the Part 6 models is simple and deliberate.</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Step</th>
<th style="text-align: left;">Model</th>
<th style="text-align: left;">What changes</th>
<th style="text-align: left;">Why it is in scope</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Linear <code>PGARCH-L</code> baseline</td>
<td style="text-align: left;">Reuse the Part 5 three-feature specification</td>
<td style="text-align: left;">Anchor the expanded-feature experiment to the accepted family baseline</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Expanded linear PGARCH with uniform shrinkage</td>
<td style="text-align: left;">Pass the richer feature matrix to all channels with common penalties</td>
<td style="text-align: left;">Test whether more predictors help at all</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Expanded linear PGARCH with channel-specific shrinkage</td>
<td style="text-align: left;">Keep the richer feature matrix, but vary <code>lambda_mu</code>, <code>lambda_phi</code>, and <code>lambda_g</code></td>
<td style="text-align: left;">Test whether richer features help only when the channels are treated differently</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Full <code>XGBPGARCHModel</code> preview</td>
<td style="text-align: left;">Replace linear channel maps with boosted updates in <span class="math inline">\mu</span>, <span class="math inline">\phi</span>, and <span class="math inline">g</span></td>
<td style="text-align: left;">Check whether the natural next step is a nonlinear channel update rather than another minor linear tweak</td>
</tr>
</tbody>
</table>
<p>This roadmap separates three questions that are easy to blur together. The first is whether linear PGARCH benefits from broader information at all. The second is whether channel-specific allocation helps more than uniform expansion. The third is whether a boosted or nonlinear update becomes the right next branch once the linear expanded models stall.</p>
<h2 data-number="4" id="feature-universe-and-taxonomy" class="anchored"><span class="header-section-number">4</span> Feature Universe and Taxonomy</h2>
<p>The executable Part 6 snapshot contains a 54-column predictor matrix. It reuses the broader feature-engineering ideas developed earlier in the series, but the realized design in this notebook is the 54-column matrix produced by the Part 6 pipeline and local data availability.</p>
<p>The taxonomy below is organizational rather than architectural. In the current linear PGARCH implementation, every feature is passed to every channel. The taxonomy simply records which channel a feature class is most naturally associated with before shrinkage is applied.</p>
<p>Fast return and intraday measures are the natural candidates for <span class="math inline">g_t</span>. Volatility-state variables such as HAR-style realized-volatility summaries, downside asymmetry, and volatility-of-volatility are the natural candidates for <span class="math inline">\phi_t</span>. Slower state variables such as implied-volatility levels, cross-asset conditions, macro-release timing, and liquidity controls are most naturally associated with <span class="math inline">\mu_t</span>.</p>
<p>That distinction is important for how the evidence should be read. The allocation table below is a prior about intended use, not proof that the fitted model enforces that allocation cleanly. One of the Part 6 findings is that shrinkage alone only partially succeeds at that task.</p>
<div id="37424c16" class="cell">
<details class="code-fold">
<summary>Build expanded feature set (adapted from feature expansion notebook)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ──────────────────────────────────────────────────────────────────────────────</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Feature construction pipeline, adapted from the STES/XGBSTES feature expansion</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># notebook (posts/volatility-forecasts-7/draft.ipynb).  We reuse the same</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># engineering logic to ensure consistency across the series.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ──────────────────────────────────────────────────────────────────────────────</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Shared OHLCV data ────────────────────────────────────────────────────────</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>ohlcv <span class="op">=</span> sample_cached.set_index(<span class="st">"date"</span>)[[<span class="st">"open"</span>, <span class="st">"close"</span>, <span class="st">"volume"</span>]].copy()</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>ohlcv.index <span class="op">=</span> pd.DatetimeIndex(ohlcv.index)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>ohlcv <span class="op">=</span> ohlcv.sort_index()</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>ohlcv_aligned <span class="op">=</span> ohlcv.reindex(target_idx, method<span class="op">=</span><span class="st">"ffill"</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># ── 1. Intraday return decomposition ─────────────────────────────────────────</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>intra_df <span class="op">=</span> pd.DataFrame(index<span class="op">=</span>target_idx)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>prev_close <span class="op">=</span> ohlcv_aligned[<span class="st">"close"</span>].shift(<span class="dv">1</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>intra_df[<span class="st">"overnight_return"</span>] <span class="op">=</span> np.log(ohlcv_aligned[<span class="st">"open"</span>] <span class="op">/</span> prev_close)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>intra_df[<span class="st">"intraday_return"</span>] <span class="op">=</span> np.log(ohlcv_aligned[<span class="st">"close"</span>] <span class="op">/</span> ohlcv_aligned[<span class="st">"open"</span>])</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>intra_df[<span class="st">"overnight_sq"</span>] <span class="op">=</span> intra_df[<span class="st">"overnight_return"</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>intra_df[<span class="st">"intraday_sq"</span>] <span class="op">=</span> intra_df[<span class="st">"intraday_return"</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>intra_df <span class="op">=</span> intra_df.fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>intraday_cols <span class="op">=</span> <span class="bu">list</span>(intra_df.columns)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co"># ── 2. HAR multi-horizon realised volatility ─────────────────────────────────</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>rv_daily <span class="op">=</span> r_par <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>har_df <span class="op">=</span> pd.DataFrame(index<span class="op">=</span>target_idx)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>har_df[<span class="st">"rv_1"</span>] <span class="op">=</span> rv_daily.shift(<span class="dv">1</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>har_df[<span class="st">"rv_5"</span>] <span class="op">=</span> rv_daily.rolling(<span class="dv">5</span>, min_periods<span class="op">=</span><span class="dv">1</span>).mean().shift(<span class="dv">1</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>har_df[<span class="st">"rv_22"</span>] <span class="op">=</span> rv_daily.rolling(<span class="dv">22</span>, min_periods<span class="op">=</span><span class="dv">1</span>).mean().shift(<span class="dv">1</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>har_df[<span class="st">"rv_60"</span>] <span class="op">=</span> rv_daily.rolling(<span class="dv">60</span>, min_periods<span class="op">=</span><span class="dv">1</span>).mean().shift(<span class="dv">1</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>har_df[<span class="st">"rv_ratio_5_22"</span>] <span class="op">=</span> har_df[<span class="st">"rv_5"</span>] <span class="op">/</span> har_df[<span class="st">"rv_22"</span>].clip(lower<span class="op">=</span><span class="fl">1e-12</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>har_df <span class="op">=</span> har_df.fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>har_rv_cols <span class="op">=</span> <span class="bu">list</span>(har_df.columns)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co"># ── 3. Downside asymmetry and leverage effect ────────────────────────────────</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>neg_mask <span class="op">=</span> (r_par <span class="op">&lt;</span> <span class="dv">0</span>).astype(<span class="bu">float</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>pos_mask <span class="op">=</span> (r_par <span class="op">&gt;=</span> <span class="dv">0</span>).astype(<span class="bu">float</span>)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>rv_daily_asym <span class="op">=</span> r_par <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>asym_df <span class="op">=</span> pd.DataFrame(index<span class="op">=</span>target_idx)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>neg_rv <span class="op">=</span> (rv_daily_asym <span class="op">*</span> neg_mask).rolling(<span class="dv">22</span>, min_periods<span class="op">=</span><span class="dv">1</span>).<span class="bu">sum</span>().shift(<span class="dv">1</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>pos_rv <span class="op">=</span> (rv_daily_asym <span class="op">*</span> pos_mask).rolling(<span class="dv">22</span>, min_periods<span class="op">=</span><span class="dv">1</span>).<span class="bu">sum</span>().shift(<span class="dv">1</span>)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>asym_df[<span class="st">"neg_semi_rv_22"</span>] <span class="op">=</span> neg_rv</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>asym_df[<span class="st">"pos_neg_rv_ratio"</span>] <span class="op">=</span> pos_rv <span class="op">/</span> neg_rv.clip(lower<span class="op">=</span><span class="fl">1e-12</span>)</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>asym_df[<span class="st">"signed_rv_interaction"</span>] <span class="op">=</span> (r_par <span class="op">*</span> rv_daily_asym).shift(<span class="dv">1</span>)</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>asym_df[<span class="st">"downside_freq_22"</span>] <span class="op">=</span> neg_mask.rolling(<span class="dv">22</span>, min_periods<span class="op">=</span><span class="dv">1</span>).mean().shift(<span class="dv">1</span>)</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>asym_df <span class="op">=</span> asym_df.fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>asym_cols <span class="op">=</span> <span class="bu">list</span>(asym_df.columns)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="co"># ── 4. Volatility-of-volatility and regime dispersion ────────────────────────</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>rv_daily_vov <span class="op">=</span> r_par <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>vov_df <span class="op">=</span> pd.DataFrame(index<span class="op">=</span>target_idx)</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>vov_df[<span class="st">"vov_22"</span>] <span class="op">=</span> rv_daily_vov.rolling(<span class="dv">22</span>, min_periods<span class="op">=</span><span class="dv">5</span>).std().shift(<span class="dv">1</span>)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>rv_max_22 <span class="op">=</span> rv_daily_vov.rolling(<span class="dv">22</span>, min_periods<span class="op">=</span><span class="dv">5</span>).<span class="bu">max</span>().shift(<span class="dv">1</span>)</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>rv_min_22 <span class="op">=</span> rv_daily_vov.rolling(<span class="dv">22</span>, min_periods<span class="op">=</span><span class="dv">5</span>).<span class="bu">min</span>().shift(<span class="dv">1</span>)</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>vov_df[<span class="st">"rv_range_22"</span>] <span class="op">=</span> rv_max_22 <span class="op">-</span> rv_min_22</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>rv_lag1 <span class="op">=</span> rv_daily_vov.shift(<span class="dv">1</span>)</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>vov_df[<span class="st">"rv_autocorr_5"</span>] <span class="op">=</span> rv_daily_vov.rolling(<span class="dv">5</span>, min_periods<span class="op">=</span><span class="dv">3</span>).corr(rv_lag1).shift(<span class="dv">1</span>)</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>vov_df <span class="op">=</span> vov_df.fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>vov_cols <span class="op">=</span> <span class="bu">list</span>(vov_df.columns)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="co"># ── 5. Volume and liquidity ──────────────────────────────────────────────────</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>vol_df <span class="op">=</span> pd.DataFrame(index<span class="op">=</span>target_idx)</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>spy_vol_aligned <span class="op">=</span> ohlcv_aligned[<span class="st">"volume"</span>]</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>spy_close_aligned <span class="op">=</span> ohlcv_aligned[<span class="st">"close"</span>]</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>vol_df[<span class="st">"volume_ratio"</span>] <span class="op">=</span> spy_vol_aligned <span class="op">/</span> spy_vol_aligned.rolling(<span class="dv">20</span>, min_periods<span class="op">=</span><span class="dv">1</span>).mean()</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>dollar_volume <span class="op">=</span> spy_close_aligned <span class="op">*</span> spy_vol_aligned</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>vol_df[<span class="st">"amihud_illiq"</span>] <span class="op">=</span> (r_par.<span class="bu">abs</span>() <span class="op">/</span> dollar_volume) <span class="op">*</span> <span class="fl">1e6</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>vol_df <span class="op">=</span> vol_df.fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>volume_cols <span class="op">=</span> <span class="bu">list</span>(vol_df.columns)</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="co"># ── 6. Calendar and event features ───────────────────────────────────────────</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="co"># Deterministic features — no API needed, computed from the trading calendar</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>    <span class="im">from</span> alphaforge.features <span class="im">import</span> CalendarFlagsTemplate, EventDateTemplate</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>    <span class="im">from</span> alphaforge.features.template <span class="im">import</span> SliceSpec <span class="im">as</span> AFSliceSpec</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>    cal_tmpl <span class="op">=</span> CalendarFlagsTemplate()</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>    cal_slice <span class="op">=</span> AFSliceSpec(start<span class="op">=</span>SAMPLE_START, end<span class="op">=</span>SAMPLE_END, entities<span class="op">=</span>[SAMPLE_TICKER])</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>    cal_ff <span class="op">=</span> cal_tmpl.transform(</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>        ctx_sample,</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>        params<span class="op">=</span>{</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>            <span class="st">"calendar"</span>: <span class="st">"XNYS"</span>,</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>            <span class="st">"flags"</span>: (<span class="st">"dow"</span>, <span class="st">"is_month_end"</span>, <span class="st">"is_quarter_end"</span>, <span class="st">"is_year_end"</span>),</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>            <span class="st">"one_hot_dow"</span>: <span class="va">True</span>,</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>        },</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>        <span class="bu">slice</span><span class="op">=</span>cal_slice,</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>        state<span class="op">=</span><span class="va">None</span>,</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(cal_ff.index, pd.MultiIndex):</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>        cal_ff <span class="op">=</span> cal_ff.xs(SAMPLE_TICKER, level<span class="op">=</span><span class="st">"entity_id"</span>)</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>    cal_ff <span class="op">=</span> cal_ff.reindex(target_idx).fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>    evt_tmpl <span class="op">=</span> EventDateTemplate()</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>    evt_ff <span class="op">=</span> evt_tmpl.transform(</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>        ctx_sample,</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>        params<span class="op">=</span>{</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>            <span class="st">"calendar"</span>: <span class="st">"XNYS"</span>,</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>            <span class="st">"events"</span>: (<span class="st">"fomc"</span>, <span class="st">"opex"</span>, <span class="st">"imm"</span>),</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>            <span class="st">"near_window"</span>: <span class="dv">3</span>,</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>        },</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>        <span class="bu">slice</span><span class="op">=</span>cal_slice,</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>        state<span class="op">=</span><span class="va">None</span>,</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(evt_ff.index, pd.MultiIndex):</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>        evt_ff <span class="op">=</span> evt_ff.xs(SAMPLE_TICKER, level<span class="op">=</span><span class="st">"entity_id"</span>)</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>    evt_ff <span class="op">=</span> evt_ff.reindex(target_idx).fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>    seasonal_df <span class="op">=</span> pd.concat([cal_ff, evt_ff], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add period-end lead windows</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col_end <span class="kw">in</span> [<span class="st">"is_month_end"</span>, <span class="st">"is_quarter_end"</span>, <span class="st">"is_year_end"</span>]:</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> col_end <span class="kw">in</span> seasonal_df.columns:</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>            lead_col <span class="op">=</span> col_end.replace(<span class="st">"is_"</span>, <span class="st">"pre_"</span>) <span class="op">+</span> <span class="st">"_3d"</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>            end_positions <span class="op">=</span> seasonal_df[col_end] <span class="op">==</span> <span class="dv">1</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>            lead_series <span class="op">=</span> pd.Series(<span class="fl">0.0</span>, index<span class="op">=</span>target_idx)</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> idx_pos <span class="kw">in</span> end_positions[end_positions].index:</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>                loc <span class="op">=</span> target_idx.get_loc(idx_pos)</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>                <span class="cf">for</span> lag <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">4</span>):</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">if</span> loc <span class="op">-</span> lag <span class="op">&gt;=</span> <span class="dv">0</span>:</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>                        lead_series.iloc[loc <span class="op">-</span> lag] <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>            seasonal_df[lead_col] <span class="op">=</span> lead_series</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>    seasonal_cols <span class="op">=</span> <span class="bu">list</span>(seasonal_df.columns)</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>    _cal_ok <span class="op">=</span> <span class="va">True</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Calendar/event features: </span><span class="sc">{</span><span class="bu">len</span>(seasonal_cols)<span class="sc">}</span><span class="ss"> columns"</span>)</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Calendar features unavailable (</span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">); building minimal DOW flags"</span>)</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>    seasonal_df <span class="op">=</span> pd.DataFrame(index<span class="op">=</span>target_idx)</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>    dow <span class="op">=</span> target_idx.dayofweek</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> d <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>):</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>        seasonal_df[<span class="ss">f"dow_</span><span class="sc">{</span>d<span class="sc">}</span><span class="ss">"</span>] <span class="op">=</span> (dow <span class="op">==</span> d).astype(<span class="bu">float</span>)</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>    seasonal_cols <span class="op">=</span> <span class="bu">list</span>(seasonal_df.columns)</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>    _cal_ok <span class="op">=</span> <span class="va">False</span></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a><span class="co"># ── 7. FRED-based features (VIX, cross-asset, stress, macro) ─────────────────</span></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>_fred_ok <span class="op">=</span> <span class="va">False</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>fred_feature_dfs <span class="op">=</span> []</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>fred_feature_cols <span class="op">=</span> []</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>    <span class="im">from</span> fredapi <span class="im">import</span> Fred</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>    fred <span class="op">=</span> Fred(api_key<span class="op">=</span>os.environ[<span class="st">"FRED_API_KEY"</span>])</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>    _start <span class="op">=</span> SAMPLE_START.strftime(<span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st">"</span>)</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>    _end <span class="op">=</span> SAMPLE_END.strftime(<span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st">"</span>)</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> _fred_to_daily(s, col_name, tidx):</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>        s <span class="op">=</span> s.rename(col_name)</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>        s.index <span class="op">=</span> pd.DatetimeIndex(s.index)</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> tidx.tz <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>            s.index <span class="op">=</span> s.index.tz_localize(<span class="st">"UTC"</span>) <span class="cf">if</span> s.index.tz <span class="kw">is</span> <span class="va">None</span> <span class="cf">else</span> s.index.tz_convert(<span class="st">"UTC"</span>)</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>            s.index <span class="op">=</span> s.index.tz_localize(<span class="va">None</span>) <span class="cf">if</span> s.index.tz <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> s.index</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> s.reindex(tidx, method<span class="op">=</span><span class="st">"ffill"</span>)</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>    <span class="co"># VIX features</span></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>    vix_df <span class="op">=</span> pd.DataFrame(index<span class="op">=</span>target_idx)</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>    vix_series <span class="op">=</span> fred.get_series(<span class="st">"VIXCLS"</span>, observation_start<span class="op">=</span>_start, observation_end<span class="op">=</span>_end).dropna()</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>    vix_df[<span class="st">"vix_level"</span>] <span class="op">=</span> _fred_to_daily(vix_series, <span class="st">"vix_level"</span>, target_idx)</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>    vix_df[<span class="st">"vix_change"</span>] <span class="op">=</span> vix_df[<span class="st">"vix_level"</span>].diff().fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>    vix_df[<span class="st">"vix_level"</span>] <span class="op">=</span> vix_df[<span class="st">"vix_level"</span>].ffill().bfill()</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>        vix3m <span class="op">=</span> fred.get_series(<span class="st">"VXVCLS"</span>, observation_start<span class="op">=</span>_start, observation_end<span class="op">=</span>_end).dropna()</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>        vix_df[<span class="st">"vix_term_slope"</span>] <span class="op">=</span> _fred_to_daily(vix_series, <span class="st">"v1"</span>, target_idx) <span class="op">-</span> _fred_to_daily(vix3m, <span class="st">"v2"</span>, target_idx)</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>        vix_df[<span class="st">"vix3m_available"</span>] <span class="op">=</span> _fred_to_daily(vix3m, <span class="st">"v3"</span>, target_idx).notna().astype(<span class="bu">float</span>)</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">Exception</span>:</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>        vix_df[<span class="st">"vix_term_slope"</span>] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>        vix_df[<span class="st">"vix3m_available"</span>] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>    <span class="co"># IV-RV spread</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>    rv_20_annualised <span class="op">=</span> np.sqrt(rv_daily.rolling(<span class="dv">20</span>, min_periods<span class="op">=</span><span class="dv">5</span>).mean().shift(<span class="dv">1</span>) <span class="op">*</span> <span class="dv">252</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>    vix_df[<span class="st">"iv_rv_spread"</span>] <span class="op">=</span> vix_df[<span class="st">"vix_level"</span>] <span class="op">-</span> rv_20_annualised</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>    vix_df <span class="op">=</span> vix_df.fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>    vix_cols <span class="op">=</span> <span class="bu">list</span>(vix_df.columns)</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>    fred_feature_dfs.append(vix_df[vix_cols])</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Cross-asset features</span></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>    cross_df <span class="op">=</span> pd.DataFrame(index<span class="op">=</span>target_idx)</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>    fred_cross <span class="op">=</span> {</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>        <span class="st">"BAMLH0A0HYM2"</span>: <span class="st">"credit_spread"</span>,</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>        <span class="st">"T10Y2Y"</span>: <span class="st">"curve_slope"</span>,</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>        <span class="st">"DCOILWTICO"</span>: <span class="st">"oil_price"</span>,</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>        <span class="st">"DGS2"</span>: <span class="st">"short_rate_level"</span>,</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>        <span class="st">"DGS10"</span>: <span class="st">"long_rate_level"</span>,</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>        <span class="st">"DTWEXBGS"</span>: <span class="st">"usd_level"</span>,</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> fred_id, col_name <span class="kw">in</span> fred_cross.items():</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>        <span class="cf">try</span>:</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>            s <span class="op">=</span> fred.get_series(fred_id, observation_start<span class="op">=</span>_start, observation_end<span class="op">=</span>_end).dropna()</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>            cross_df[col_name] <span class="op">=</span> _fred_to_daily(s, col_name, target_idx)</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>        <span class="cf">except</span> <span class="pp">Exception</span>:</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>            cross_df[col_name] <span class="op">=</span> np.nan</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>        copper_monthly <span class="op">=</span> fred.get_series(<span class="st">"PCOPPUSDM"</span>, observation_start<span class="op">=</span>_start, observation_end<span class="op">=</span>_end).dropna()</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>        cross_df[<span class="st">"copper_level"</span>] <span class="op">=</span> _fred_to_daily(copper_monthly, <span class="st">"copper_level"</span>, target_idx)</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">Exception</span>:</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>        cross_df[<span class="st">"copper_level"</span>] <span class="op">=</span> np.nan</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>        gld_src <span class="op">=</span> TiingoEODSource(api_key<span class="op">=</span>os.environ.get(<span class="st">"TIINGO_API"</span>) <span class="kw">or</span> os.environ.get(<span class="st">"TIINGO_API_KEY"</span>))</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>        gld_raw <span class="op">=</span> gld_src.fetch(Query(</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>            table<span class="op">=</span><span class="st">"market.ohlcv"</span>, columns<span class="op">=</span>[<span class="st">"close"</span>],</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>            start<span class="op">=</span>SAMPLE_START, end<span class="op">=</span>SAMPLE_END, entities<span class="op">=</span>[<span class="st">"GLD"</span>],</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>        ))</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>        gld_close <span class="op">=</span> gld_raw.set_index(<span class="st">"date"</span>)[<span class="st">"close"</span>].rename(<span class="st">"gold_price"</span>)</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> target_idx.tz <span class="kw">is</span> <span class="va">None</span>:</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>            gld_close.index <span class="op">=</span> pd.DatetimeIndex(gld_close.index).tz_localize(<span class="va">None</span>)</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>            gld_close.index <span class="op">=</span> pd.DatetimeIndex(gld_close.index).tz_convert(target_idx.tz)</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>        cross_df[<span class="st">"gold_price"</span>] <span class="op">=</span> gld_close.reindex(target_idx, method<span class="op">=</span><span class="st">"ffill"</span>)</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">Exception</span>:</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>        cross_df[<span class="st">"gold_price"</span>] <span class="op">=</span> np.nan</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Derived</span></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>    cross_df[<span class="st">"gold_return"</span>] <span class="op">=</span> np.log(cross_df[<span class="st">"gold_price"</span>] <span class="op">/</span> cross_df[<span class="st">"gold_price"</span>].shift(<span class="dv">1</span>))</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>    cross_df[<span class="st">"oil_return"</span>] <span class="op">=</span> np.log(cross_df[<span class="st">"oil_price"</span>] <span class="op">/</span> cross_df[<span class="st">"oil_price"</span>].shift(<span class="dv">1</span>))</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>    cross_df[<span class="st">"copper_change"</span>] <span class="op">=</span> cross_df[<span class="st">"copper_level"</span>].pct_change()</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>    cross_df[<span class="st">"short_rate_change"</span>] <span class="op">=</span> cross_df[<span class="st">"short_rate_level"</span>].diff()</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>    cross_df[<span class="st">"long_rate_change"</span>] <span class="op">=</span> cross_df[<span class="st">"long_rate_level"</span>].diff()</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>    cross_df[<span class="st">"usd_change"</span>] <span class="op">=</span> cross_df[<span class="st">"usd_level"</span>].pct_change()</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>    cross_df[<span class="st">"usd_available"</span>] <span class="op">=</span> cross_df[<span class="st">"usd_level"</span>].notna().astype(<span class="bu">float</span>)</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> [<span class="st">"credit_spread"</span>, <span class="st">"curve_slope"</span>, <span class="st">"short_rate_level"</span>, <span class="st">"long_rate_level"</span>,</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"usd_level"</span>, <span class="st">"copper_level"</span>]:</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>        cross_df[col] <span class="op">=</span> cross_df[col].ffill().bfill()</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> [<span class="st">"gold_return"</span>, <span class="st">"oil_return"</span>, <span class="st">"copper_change"</span>,</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"short_rate_change"</span>, <span class="st">"long_rate_change"</span>, <span class="st">"usd_change"</span>]:</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>        cross_df[col] <span class="op">=</span> cross_df[col].fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>    cross_df[<span class="st">"usd_level"</span>] <span class="op">=</span> cross_df[<span class="st">"usd_level"</span>].ffill().bfill()</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>    cross_df <span class="op">=</span> cross_df.drop(columns<span class="op">=</span>[<span class="st">"oil_price"</span>, <span class="st">"gold_price"</span>], errors<span class="op">=</span><span class="st">"ignore"</span>)</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>    cross_asset_cols <span class="op">=</span> [c <span class="cf">for</span> c <span class="kw">in</span> cross_df.columns <span class="cf">if</span> c <span class="kw">not</span> <span class="kw">in</span> (<span class="st">"oil_price"</span>, <span class="st">"gold_price"</span>)]</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a>    cross_df <span class="op">=</span> cross_df[cross_asset_cols].fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>    fred_feature_dfs.append(cross_df)</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Financial stress</span></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>    stress_df <span class="op">=</span> pd.DataFrame(index<span class="op">=</span>target_idx)</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>    stress_series <span class="op">=</span> {</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>        <span class="st">"VVIXCLS"</span>: <span class="st">"vvix_level"</span>,</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>        <span class="st">"NFCI"</span>: <span class="st">"nfci_level"</span>,</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>        <span class="st">"STLFSI4"</span>: <span class="st">"stlfsi_level"</span>,</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>        <span class="st">"TEDRATE"</span>: <span class="st">"ted_spread"</span>,</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> fred_id, col_name <span class="kw">in</span> stress_series.items():</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>        <span class="cf">try</span>:</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a>            s <span class="op">=</span> fred.get_series(fred_id, observation_start<span class="op">=</span>_start, observation_end<span class="op">=</span>_end).dropna()</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>            stress_df[col_name] <span class="op">=</span> _fred_to_daily(s, col_name, target_idx)</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>        <span class="cf">except</span> <span class="pp">Exception</span>:</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>            stress_df[col_name] <span class="op">=</span> np.nan</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>    stress_df <span class="op">=</span> stress_df.ffill().bfill().fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>    stress_cols <span class="op">=</span> <span class="bu">list</span>(stress_df.columns)</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>    fred_feature_dfs.append(stress_df)</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Macro release dates</span></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>    macro_df <span class="op">=</span> pd.DataFrame(<span class="fl">0.0</span>, index<span class="op">=</span>target_idx, columns<span class="op">=</span>[])</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>    trading_dates <span class="op">=</span> target_idx</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>    macro_release_series <span class="op">=</span> {<span class="st">"gdp"</span>: <span class="st">"GDP"</span>, <span class="st">"cpi"</span>: <span class="st">"CPIAUCSL"</span>, <span class="st">"nfp"</span>: <span class="st">"PAYEMS"</span>}</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> label, fred_id <span class="kw">in</span> macro_release_series.items():</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>        <span class="cf">try</span>:</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>            vintages <span class="op">=</span> fred.get_series_vintage_dates(fred_id)</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>            release_dates <span class="op">=</span> pd.DatetimeIndex(vintages)</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> trading_dates.tz <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>                release_dates <span class="op">=</span> release_dates.tz_localize(<span class="st">"UTC"</span>) <span class="cf">if</span> release_dates.tz <span class="kw">is</span> <span class="va">None</span> <span class="cf">else</span> release_dates.tz_convert(<span class="st">"UTC"</span>)</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>:</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>                release_dates <span class="op">=</span> release_dates.tz_localize(<span class="va">None</span>) <span class="cf">if</span> release_dates.tz <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> release_dates</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>            release_dates <span class="op">=</span> release_dates.normalize()</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>            macro_df[<span class="ss">f"is_</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">_release"</span>] <span class="op">=</span> trading_dates.isin(release_dates).astype(<span class="bu">float</span>)</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Pre-release 1d indicator (aligned to forecast date t+1)</span></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>            pre_col <span class="op">=</span> <span class="ss">f"pre_</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">_1d"</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>            shifted_releases <span class="op">=</span> release_dates <span class="op">-</span> pd.tseries.offsets.BDay(<span class="dv">1</span>)</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>            macro_df[pre_col] <span class="op">=</span> trading_dates.isin(shifted_releases).astype(<span class="bu">float</span>)</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>        <span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(<span class="ss">f"  Macro release </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> unavailable: </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>            macro_df[<span class="ss">f"is_</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">_release"</span>] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>            macro_df[<span class="ss">f"pre_</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">_1d"</span>] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>    macro_cols <span class="op">=</span> <span class="bu">list</span>(macro_df.columns)</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>    fred_feature_dfs.append(macro_df)</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>    _fred_ok <span class="op">=</span> <span class="va">True</span></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _df <span class="kw">in</span> fred_feature_dfs:</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>        fred_feature_cols.extend(<span class="bu">list</span>(_df.columns))</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"FRED-based features: </span><span class="sc">{</span><span class="bu">len</span>(fred_feature_cols)<span class="sc">}</span><span class="ss"> columns"</span>)</span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"FRED features unavailable (</span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">); proceeding without them"</span>)</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a>    _fred_ok <span class="op">=</span> <span class="va">False</span></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Assemble the expanded feature matrix ─────────────────────────────────────</span></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a><span class="co"># Start with the baseline return features (no const)</span></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>expanded_parts <span class="op">=</span> [X_par[base_feat_cols]]</span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="co"># Return-derived features (always available)</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a>expanded_parts.extend([intra_df, har_df, asym_df, vov_df, vol_df])</span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a><span class="co"># Calendar features (usually available)</span></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>expanded_parts.append(seasonal_df)</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a><span class="co"># FRED features (if available)</span></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> _fred_ok:</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a>    expanded_parts.extend(fred_feature_dfs)</span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a>X_expanded <span class="op">=</span> pd.concat(expanded_parts, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a>X_expanded <span class="op">=</span> X_expanded.fillna(<span class="fl">0.0</span>)</span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove any duplicate columns</span></span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a>X_expanded <span class="op">=</span> X_expanded.loc[:, <span class="op">~</span>X_expanded.columns.duplicated()]</span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>expanded_feat_cols <span class="op">=</span> <span class="bu">list</span>(X_expanded.columns)</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a><span class="co"># Split</span></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a>X_exp_tr <span class="op">=</span> X_expanded.iloc[SAMPLE_TRAIN_START:SAMPLE_SPLIT_INDEX]</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a>X_exp_te <span class="op">=</span> X_expanded.iloc[SAMPLE_SPLIT_INDEX:]</span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>X_exp_all <span class="op">=</span> pd.concat([X_exp_tr, X_exp_te])</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Expanded feature matrix: </span><span class="sc">{</span>X_expanded<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> columns"</span>)</span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Return-based:       </span><span class="sc">{</span><span class="bu">len</span>(base_feat_cols)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Intraday decomp:    </span><span class="sc">{</span><span class="bu">len</span>(intraday_cols)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  HAR-RV:             </span><span class="sc">{</span><span class="bu">len</span>(har_rv_cols)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Asymmetry:          </span><span class="sc">{</span><span class="bu">len</span>(asym_cols)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Vol-of-vol:         </span><span class="sc">{</span><span class="bu">len</span>(vov_cols)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Volume/liquidity:   </span><span class="sc">{</span><span class="bu">len</span>(volume_cols)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Calendar/event:     </span><span class="sc">{</span><span class="bu">len</span>(seasonal_cols)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> _fred_ok:</span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  FRED-based:         </span><span class="sc">{</span><span class="bu">len</span>(fred_feature_cols)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Train: </span><span class="sc">{</span>X_exp_tr<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, Test: </span><span class="sc">{</span>X_exp_te<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="2d7e1a21" class="cell">
<details class="code-fold">
<summary>Feature allocation taxonomy</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _assign_channel(feat_name):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">'''Assign a primary PGARCH channel based on the feature economic role.'''</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    f <span class="op">=</span> feat_name.lower()</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># g-channel: fast shock features</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    g_features <span class="op">=</span> {<span class="st">"overnight_return"</span>, <span class="st">"intraday_return"</span>, <span class="st">"overnight_sq"</span>, <span class="st">"intraday_sq"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"signed_rv_interaction"</span>}</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> f <span class="kw">in</span> g_features:</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"g (innovation)"</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">any</span>(k <span class="kw">in</span> f <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"logret"</span>, <span class="st">"log_return"</span>]):</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"g (innovation)"</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># phi-channel: persistence features</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    phi_features <span class="op">=</span> {<span class="st">"rv_autocorr_5"</span>, <span class="st">"vov_22"</span>, <span class="st">"rv_range_22"</span>, <span class="st">"rv_ratio_5_22"</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"neg_semi_rv_22"</span>, <span class="st">"pos_neg_rv_ratio"</span>, <span class="st">"downside_freq_22"</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"rv_5"</span>, <span class="st">"rv_22"</span>, <span class="st">"rv_60"</span>, <span class="st">"rv_1"</span>}</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> f <span class="kw">in</span> phi_features:</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"phi (persistence)"</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Everything else -&gt; mu-channel</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">"mu (level)"</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _assign_group(feat_name):</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="co">'''Assign a feature group label.'''</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    f <span class="op">=</span> feat_name.lower()</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">any</span>(k <span class="kw">in</span> f <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"logret"</span>, <span class="st">"log_return"</span>]):</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Return-based"</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> f.startswith(<span class="st">"dow_"</span>):</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Calendar (DOW)"</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">any</span>(k <span class="kw">in</span> f <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"month_end"</span>, <span class="st">"quarter_end"</span>, <span class="st">"year_end"</span>]):</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Calendar (Period-end)"</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">any</span>(k <span class="kw">in</span> f <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"fomc"</span>, <span class="st">"opex"</span>, <span class="st">"imm"</span>]):</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Calendar (Events)"</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">any</span>(k <span class="kw">in</span> f <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"vix"</span>, <span class="st">"iv_rv"</span>, <span class="st">"vix3m"</span>]):</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"VIX / Implied Vol"</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">any</span>(k <span class="kw">in</span> f <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"credit"</span>, <span class="st">"curve"</span>, <span class="st">"gold"</span>, <span class="st">"oil"</span>, <span class="st">"rate"</span>, <span class="st">"usd"</span>, <span class="st">"copper"</span>]):</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Cross-Asset"</span></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">any</span>(k <span class="kw">in</span> f <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"volume"</span>, <span class="st">"amihud"</span>]):</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Volume / Liquidity"</span></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">any</span>(k <span class="kw">in</span> f <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"gdp"</span>, <span class="st">"cpi"</span>, <span class="st">"nfp"</span>]):</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Macro Release"</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">any</span>(k <span class="kw">in</span> f <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"overnight"</span>, <span class="st">"intraday"</span>]):</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Intraday Decomp"</span></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">any</span>(k <span class="kw">in</span> f <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"rv_"</span>, <span class="st">"neg_semi"</span>, <span class="st">"downside"</span>, <span class="st">"signed_rv"</span>,</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"vov_"</span>, <span class="st">"nfci"</span>, <span class="st">"stlfsi"</span>, <span class="st">"ted"</span>, <span class="st">"vvix"</span>]):</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"Volatility State"</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">"Other"</span></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>taxonomy <span class="op">=</span> pd.DataFrame({</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Feature"</span>: expanded_feat_cols,</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Group"</span>: [_assign_group(f) <span class="cf">for</span> f <span class="kw">in</span> expanded_feat_cols],</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Channel"</span>: [_assign_channel(f) <span class="cf">for</span> f <span class="kw">in</span> expanded_feat_cols],</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>channel_summary <span class="op">=</span> taxonomy.groupby(<span class="st">"Channel"</span>)[<span class="st">"Feature"</span>].count().rename(<span class="st">"Count"</span>)</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>group_summary <span class="op">=</span> taxonomy.groupby([<span class="st">"Channel"</span>, <span class="st">"Group"</span>])[<span class="st">"Feature"</span>].count().rename(<span class="st">"Count"</span>)</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Channel allocation summary:"</span>)</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(channel_summary.to_string())</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Detailed group × channel:"</span>)</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(group_summary.to_string())</span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>display(style_results_table(taxonomy, precision<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="st">"Feature"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<h2 data-number="5" id="evaluation-standard-and-experimental-design" class="anchored"><span class="header-section-number">5</span> Evaluation Standard and Experimental Design</h2>
<p>The dataset, target, and split are held fixed relative to Part 5. After the 200-row warm-up discard, the effective sample contains 3,800 training observations and 2,035 out-of-sample observations on SPY daily variance from 2000 through 2023. <code>GARCH(1,1)</code> remains the benchmark, and the Part 5 <code>PGARCH-L</code> baseline remains the active family reference.</p>
<p>The underlying model implementations live in the sibling <code>volatility-forecast</code> repository, principally <code>volatility_forecast/model/pgarch_linear_model.py</code> for the linear branch and <code>volatility_forecast/model/xgb_pgarch_full_model.py</code> for the nonlinear preview.</p>
<h3 data-number="5.1" id="what-counts-as-success" class="anchored"><span class="header-section-number">5.1</span> What Counts as Success</h3>
<p>This series is not selecting models by in-sample fit. The decision rule remains the same as in Part 4 and Part 5: lower out-of-sample QLIKE than <code>GARCH(1,1)</code>, with Diebold-Mariano tests on QLIKE loss used to judge whether a benchmark improvement is statistically credible. RMSE and in-sample QLIKE remain useful diagnostics, but they are secondary. A model that fits the training window better while losing on OS QLIKE or failing against the benchmark is not treated as a success.</p>
<h3 data-number="5.2" id="part-6-variants" class="anchored"><span class="header-section-number">5.2</span> Part 6 Variants</h3>
<p>We define five linear PGARCH variants that move one step at a time through the expanded-feature question.</p>
<table class="caption-top">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Features</th>
<th style="text-align: center;"><code>lambda_mu</code></th>
<th style="text-align: center;"><code>lambda_phi</code></th>
<th style="text-align: center;"><code>lambda_g</code></th>
<th style="text-align: left;">Design intent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>A</strong> - Part 5 baseline</td>
<td style="text-align: left;">3 return features</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: left;">Reproduce the accepted Part 5 <code>PGARCH-L</code> reference</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>B</strong> - Expanded, uniform</td>
<td style="text-align: left;">All expanded</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: left;">Ask whether all-feature linear expansion helps at all</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>C</strong> - Structured, rich <code>mu</code></td>
<td style="text-align: left;">All expanded</td>
<td style="text-align: center;">0.001</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.1</td>
<td style="text-align: left;">Test the main channel-allocation idea</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>D</strong> - Structured, very rich <code>mu</code></td>
<td style="text-align: left;">All expanded</td>
<td style="text-align: center;">0.0001</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.1</td>
<td style="text-align: left;">Check whether giving the level channel even more freedom helps or overfits</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>E</strong> - Structured, relaxed <code>g</code></td>
<td style="text-align: left;">All expanded</td>
<td style="text-align: center;">0.001</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: left;">Check whether the innovation channel benefits from broader access</td>
</tr>
</tbody>
</table>
<p>The key comparisons are therefore easy to state. Model B against Model A asks whether simple expansion helps. Model C against Model B asks whether channel-specific shrinkage helps more than uniform shrinkage. Model D against Model C asks whether extra freedom in the level channel is useful or just costly. Model E against Model C asks whether a lean <code>g</code> channel is a helpful prior or an unnecessary restriction.</p>
<div id="7e6186d1" class="cell">
<details class="code-fold">
<summary>Fit GARCH(1,1) baseline</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>r_tr_pct <span class="op">=</span> r_tr <span class="op">*</span> SCALE_FACTOR</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>r_all_concat <span class="op">=</span> pd.concat([r_tr, r_te])</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>r_all_pct <span class="op">=</span> r_all_concat <span class="op">*</span> SCALE_FACTOR</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>garch_spec <span class="op">=</span> arch_model(r_tr_pct, vol<span class="op">=</span><span class="st">"GARCH"</span>, p<span class="op">=</span><span class="dv">1</span>, q<span class="op">=</span><span class="dv">1</span>, mean<span class="op">=</span><span class="st">"Zero"</span>, rescale<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>garch_fit <span class="op">=</span> garch_spec.fit(disp<span class="op">=</span><span class="st">"off"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>omega_g, alpha_g, beta_g <span class="op">=</span> (</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    garch_fit.params[<span class="st">"omega"</span>],</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    garch_fit.params[<span class="st">"alpha[1]"</span>],</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    garch_fit.params[<span class="st">"beta[1]"</span>],</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>cv_sq_is <span class="op">=</span> garch_fit.conditional_volatility.values <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>r_sq_is <span class="op">=</span> r_tr_pct.values <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>garch_pred_is <span class="op">=</span> (omega_g <span class="op">+</span> alpha_g <span class="op">*</span> r_sq_is <span class="op">+</span> beta_g <span class="op">*</span> cv_sq_is) <span class="op">/</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>garch_spec_full <span class="op">=</span> arch_model(r_all_pct, vol<span class="op">=</span><span class="st">"GARCH"</span>, p<span class="op">=</span><span class="dv">1</span>, q<span class="op">=</span><span class="dv">1</span>, mean<span class="op">=</span><span class="st">"Zero"</span>, rescale<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>garch_fit_full <span class="op">=</span> garch_spec_full.fit(disp<span class="op">=</span><span class="st">"off"</span>, last_obs<span class="op">=</span><span class="bu">len</span>(r_tr))</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>garch_fcast <span class="op">=</span> garch_fit_full.forecast(start<span class="op">=</span><span class="bu">len</span>(r_tr), reindex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>garch_pred_os <span class="op">=</span> garch_fcast.variance.values.flatten() <span class="op">/</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"GARCH(1,1): omega=</span><span class="sc">{</span>omega_g<span class="sc">:.6f}</span><span class="ss">, alpha=</span><span class="sc">{</span>alpha_g<span class="sc">:.4f}</span><span class="ss">, beta=</span><span class="sc">{</span>beta_g<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="e3d2f382" class="cell">
<details class="code-fold">
<summary>Fit PGARCH-L model ladder (Models A–E)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>RANDOM_STATE <span class="op">=</span> <span class="dv">42</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Model A: Part 5 baseline (3 return features, no regularisation) ──────────</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>X_base_tr <span class="op">=</span> X_tr[base_feat_cols]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>X_base_te <span class="op">=</span> X_te[base_feat_cols]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>X_base_all <span class="op">=</span> pd.concat([X_base_tr, X_base_te])</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>model_a <span class="op">=</span> PGARCHLinearModel(loss<span class="op">=</span><span class="st">"qlike"</span>, random_state<span class="op">=</span>RANDOM_STATE)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>model_a.fit(y_tr.values, X_base_tr.values)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>h_a <span class="op">=</span> model_a.predict_variance(y_all.values, X_base_all.values)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>h_a_is, h_a_os <span class="op">=</span> h_a[: <span class="bu">len</span>(y_tr)], h_a[<span class="bu">len</span>(y_tr) :]</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Model A (Part 5 baseline):  train QLIKE = </span><span class="sc">{</span>model_a<span class="sc">.</span>train_loss_<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Model B: Expanded features, uniform regularisation ───────────────────────</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>model_b <span class="op">=</span> PGARCHLinearModel(</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    loss<span class="op">=</span><span class="st">"qlike"</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    lambda_mu<span class="op">=</span><span class="fl">0.01</span>, lambda_phi<span class="op">=</span><span class="fl">0.01</span>, lambda_g<span class="op">=</span><span class="fl">0.01</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span>RANDOM_STATE,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>model_b.fit(y_tr.values, X_exp_tr.values)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>h_b <span class="op">=</span> model_b.predict_variance(y_all.values, X_exp_all.values)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>h_b_is, h_b_os <span class="op">=</span> h_b[: <span class="bu">len</span>(y_tr)], h_b[<span class="bu">len</span>(y_tr) :]</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Model B (uniform reg):      train QLIKE = </span><span class="sc">{</span>model_b<span class="sc">.</span>train_loss_<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Model C: Structured (rich mu, lean g) ────────────────────────────────────</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>model_c <span class="op">=</span> PGARCHLinearModel(</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    loss<span class="op">=</span><span class="st">"qlike"</span>,</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    lambda_mu<span class="op">=</span><span class="fl">0.001</span>, lambda_phi<span class="op">=</span><span class="fl">0.01</span>, lambda_g<span class="op">=</span><span class="fl">0.1</span>,</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span>RANDOM_STATE,</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>model_c.fit(y_tr.values, X_exp_tr.values)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>h_c <span class="op">=</span> model_c.predict_variance(y_all.values, X_exp_all.values)</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>h_c_is, h_c_os <span class="op">=</span> h_c[: <span class="bu">len</span>(y_tr)], h_c[<span class="bu">len</span>(y_tr) :]</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Model C (rich mu, lean g):  train QLIKE = </span><span class="sc">{</span>model_c<span class="sc">.</span>train_loss_<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Model D: Structured (very rich mu) ───────────────────────────────────────</span></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>model_d <span class="op">=</span> PGARCHLinearModel(</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>    loss<span class="op">=</span><span class="st">"qlike"</span>,</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>    lambda_mu<span class="op">=</span><span class="fl">0.0001</span>, lambda_phi<span class="op">=</span><span class="fl">0.01</span>, lambda_g<span class="op">=</span><span class="fl">0.1</span>,</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span>RANDOM_STATE,</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>model_d.fit(y_tr.values, X_exp_tr.values)</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>h_d <span class="op">=</span> model_d.predict_variance(y_all.values, X_exp_all.values)</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>h_d_is, h_d_os <span class="op">=</span> h_d[: <span class="bu">len</span>(y_tr)], h_d[<span class="bu">len</span>(y_tr) :]</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Model D (very rich mu):     train QLIKE = </span><span class="sc">{</span>model_d<span class="sc">.</span>train_loss_<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Model E: Structured (relaxed g) ──────────────────────────────────────────</span></span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>model_e <span class="op">=</span> PGARCHLinearModel(</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>    loss<span class="op">=</span><span class="st">"qlike"</span>,</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>    lambda_mu<span class="op">=</span><span class="fl">0.001</span>, lambda_phi<span class="op">=</span><span class="fl">0.01</span>, lambda_g<span class="op">=</span><span class="fl">0.01</span>,</span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span>RANDOM_STATE,</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>model_e.fit(y_tr.values, X_exp_tr.values)</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>h_e <span class="op">=</span> model_e.predict_variance(y_all.values, X_exp_all.values)</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>h_e_is, h_e_os <span class="op">=</span> h_e[: <span class="bu">len</span>(y_tr)], h_e[<span class="bu">len</span>(y_tr) :]</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Model E (relaxed g):        train QLIKE = </span><span class="sc">{</span>model_e<span class="sc">.</span>train_loss_<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">All PGARCH-L variants fitted."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="performance-table" class="cell" data-tbl-cap="Out-of-sample performance: GARCH(1,1) vs PGARCH-L variants">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>actual_is <span class="op">=</span> y_tr.values</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>actual_os <span class="op">=</span> y_te.values</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>model_predictions <span class="op">=</span> {</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GARCH(1,1)"</span>:              (garch_pred_is,  garch_pred_os),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"A: PGARCH-L baseline"</span>:    (h_a_is,         h_a_os),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B: Expanded uniform"</span>:     (h_b_is,         h_b_os),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"C: Structured (rich mu)"</span>: (h_c_is,         h_c_os),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"D: Structured (very rich mu)"</span>: (h_d_is,    h_d_os),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"E: Structured (relaxed g)"</span>:    (h_e_is,    h_e_os),</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, (pred_is, pred_os) <span class="kw">in</span> model_predictions.items():</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    rows.append({</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Model"</span>: name,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"IS RMSE"</span>: rmse(actual_is, pred_is),</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS RMSE"</span>: rmse(actual_os, pred_os),</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"IS QLIKE"</span>: qlike(actual_is, pred_is),</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS QLIKE"</span>: qlike(actual_os, pred_os),</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> pd.DataFrame(rows).set_index(<span class="st">"Model"</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Highlight the best OS scores</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>display(style_results_table(results_df, precision<span class="op">=</span><span class="dv">6</span>, index_col<span class="op">=</span><span class="st">"Model"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<h2 data-number="6" id="main-results-summary" class="anchored"><span class="header-section-number">6</span> Main Results Summary</h2>
<p>The full metric table above is the detailed record. The compact summary below is the reading guide for the rest of the post.</p>
<table class="caption-top">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">OS QLIKE</th>
<th style="text-align: center;">DM vs GARCH (QLIKE)</th>
<th style="text-align: center;">p-value</th>
<th style="text-align: left;">Part 6 reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>GARCH(1,1)</code></td>
<td style="text-align: right;"><code>1.561044</code></td>
<td style="text-align: center;"><code>0.0000</code></td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: left;">benchmark</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>A: PGARCH-L baseline</code></td>
<td style="text-align: right;"><code>1.550144</code></td>
<td style="text-align: center;">not re-tabulated here</td>
<td style="text-align: center;">not re-tabulated here</td>
<td style="text-align: left;">improves on mean OS QLIKE, but remains a carry-over non-significant benchmark comparison from Part 5</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>B: Expanded uniform</code></td>
<td style="text-align: right;"><code>1.604755</code></td>
<td style="text-align: center;">not re-tabulated here</td>
<td style="text-align: center;">not re-tabulated here</td>
<td style="text-align: left;">negative result</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>C: Structured (rich mu)</code></td>
<td style="text-align: right;"><code>1.625556</code></td>
<td style="text-align: center;"><code>1.5542</code></td>
<td style="text-align: center;"><code>0.1203</code></td>
<td style="text-align: left;">negative result</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>D: Structured (very rich mu)</code></td>
<td style="text-align: right;"><code>1.830423</code></td>
<td style="text-align: center;">not re-tabulated here</td>
<td style="text-align: center;">not re-tabulated here</td>
<td style="text-align: left;">negative result</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>E: Structured (relaxed g)</code></td>
<td style="text-align: right;"><code>1.616961</code></td>
<td style="text-align: center;">not re-tabulated here</td>
<td style="text-align: center;">not re-tabulated here</td>
<td style="text-align: left;">negative result</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>XGBPGARCHModel</code> preview</td>
<td style="text-align: right;">fit failed</td>
<td style="text-align: center;">initializer failure</td>
<td style="text-align: center;"><code>-</code></td>
<td style="text-align: left;">unresolved preview</td>
</tr>
</tbody>
</table>
<p>The headline result is straightforward. The Part 5 three-feature <code>PGARCH-L</code> baseline remains the strongest forecast inside this notebook. The expanded linear models all improve in-sample fit, but those gains do not survive out of sample. Part 6 therefore adds structure and diagnostics more clearly than it adds predictive performance.</p>
<div id="9bdaaa5b" class="cell">
<details class="code-fold">
<summary>OS QLIKE ranking bar chart</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>chart_df <span class="op">=</span> results_df[[<span class="st">"OS QLIKE"</span>]].sort_values(<span class="st">"OS QLIKE"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>_colors <span class="op">=</span> {</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GARCH(1,1)"</span>: BLOG_PALETTE[<span class="dv">2</span>],</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"A: PGARCH-L baseline"</span>: BLOG_PALETTE[<span class="dv">3</span>],</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>bar_colors <span class="op">=</span> [_colors.get(idx, BLOG_PALETTE[<span class="dv">0</span>]) <span class="cf">for</span> idx <span class="kw">in</span> chart_df.index]</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax.barh(chart_df.index, chart_df[<span class="st">"OS QLIKE"</span>], color<span class="op">=</span>bar_colors,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>               edgecolor<span class="op">=</span><span class="st">"white"</span>, linewidth<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"OS QLIKE (lower is better)"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Out-of-Sample QLIKE Ranking"</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>ax.invert_yaxis()</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<h2 data-number="7" id="statistical-comparison" class="anchored"><span class="header-section-number">7</span> Statistical Comparison</h2>
<p>Point rankings are not enough on their own. The Diebold-Mariano table below checks whether the visible QLIKE differences are large enough to treat as more than noise.</p>
<p>In this notebook the DM evidence mostly reinforces, rather than overturns, the ranking table. The expanded all-feature models are not merely failing to post a benchmark-clearing p-value. On the most important comparisons, the loss differentials also point in the wrong direction.</p>
<div id="06af4d83" class="cell">
<details class="code-fold">
<summary>Diebold-Mariano tests</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _qlike_loss(y, yhat):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    y_a, h_a <span class="op">=</span> np.asarray(y, <span class="bu">float</span>), np.maximum(np.asarray(yhat, <span class="bu">float</span>), <span class="fl">1e-12</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.log(h_a) <span class="op">+</span> y_a <span class="op">/</span> h_a</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _sq_loss(y, yhat):</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (np.asarray(y, <span class="bu">float</span>) <span class="op">-</span> np.asarray(yhat, <span class="bu">float</span>)) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>dm_pairs <span class="op">=</span> [</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"C: Structured (rich mu)"</span>, <span class="st">"GARCH(1,1)"</span>),</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"C: Structured (rich mu)"</span>, <span class="st">"A: PGARCH-L baseline"</span>),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"C: Structured (rich mu)"</span>, <span class="st">"B: Expanded uniform"</span>),</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"C: Structured (rich mu)"</span>, <span class="st">"E: Structured (relaxed g)"</span>),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"D: Structured (very rich mu)"</span>, <span class="st">"C: Structured (rich mu)"</span>),</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"B: Expanded uniform"</span>, <span class="st">"A: PGARCH-L baseline"</span>),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>dm_rows <span class="op">=</span> []</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> loss_name, loss_fn <span class="kw">in</span> [(<span class="st">"QLIKE"</span>, _qlike_loss), (<span class="st">"Squared"</span>, _sq_loss)]:</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name_a, name_b <span class="kw">in</span> dm_pairs:</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        _, pred_a <span class="op">=</span> model_predictions[name_a]</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>        _, pred_b <span class="op">=</span> model_predictions[name_b]</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>        loss_a <span class="op">=</span> loss_fn(actual_os, pred_a)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>        loss_b <span class="op">=</span> loss_fn(actual_os, pred_b)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>        dm_result <span class="op">=</span> diebold_mariano(loss_a, loss_b)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>        dm_rows.append({</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Loss"</span>: loss_name,</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Model A"</span>: name_a,</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Model B"</span>: name_b,</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>            <span class="st">"DM stat"</span>: dm_result[<span class="st">"dm_stat"</span>],</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>            <span class="st">"p-value"</span>: dm_result[<span class="st">"p_value"</span>],</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Mean diff"</span>: dm_result[<span class="st">"mean_d"</span>],</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>dm_df <span class="op">=</span> pd.DataFrame(dm_rows)</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>display(style_results_table(dm_df, precision<span class="op">=</span><span class="dv">4</span>, index_col<span class="op">=</span><span class="st">"Model A"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<h3 data-number="7.1" id="reading-the-dm-tests" class="anchored"><span class="header-section-number">7.1</span> Reading the DM Tests</h3>
<p>Three comparisons carry most of the interpretive weight.</p>
<p>First, Model C is worse than <code>GARCH(1,1)</code> on mean OS QLIKE, and its DM statistic against <code>GARCH(1,1)</code> is <code>1.5542</code> with <code>p = 0.1203</code>. That is not a benchmark-clearing result.</p>
<p>Second, Model C is worse than the Part 5 <code>PGARCH-L</code> baseline, and that comparison is stronger. The DM statistic against Model A is <code>1.9879</code> with <code>p = 0.0470</code>. The first structured all-feature specification is therefore not just inconclusive against the benchmark; it is materially worse than the simpler three-feature baseline under the Part 6 protocol.</p>
<p>Third, making the <code>mu</code> channel even looser is a negative result rather than an improvement. Model D is worse than Model C, with DM statistic <code>2.6157</code> and <code>p = 0.0090</code>. In this all-feature linear setup, extra freedom in the level channel amplifies overfitting rather than uncovering additional predictive signal.</p>
<p>The remaining rows are still useful. Uniform regularization does not improve on the Part 5 baseline, and relaxing the <code>g</code> penalty does not rescue the expanded design. The expanded linear branch therefore remains active as a modeling question, but not yet as a benchmark-clearing forecasting result.</p>
<h2 data-number="8" id="channel-diagnostics" class="anchored"><span class="header-section-number">8</span> Channel Diagnostics</h2>
<p>The diagnostic plots do not overturn the forecasting result, but they explain why the structured branch remained worth carrying forward. PGARCH is useful here because it reveals how the richer feature set changes the level anchor, persistence, and innovation share even when headline OS performance does not improve.</p>
<p>The question in this section is therefore diagnostic rather than promotional. Do the expanded models move the channels in economically interpretable ways, and do those movements help explain both the promise and the failure of the Part 6 specifications?</p>
<div id="343a8271" class="cell">
<details class="code-fold">
<summary>Time-varying structural parameters: mu_t, phi_t, g_t over the test period</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract components for Models A, C, and E over the out-of-sample period</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>models_to_plot <span class="op">=</span> {</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"A: Baseline"</span>: (model_a, X_base_te),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"C: Structured"</span>: (model_c, X_exp_te),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"E: Relaxed g"</span>: (model_e, X_exp_te),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>test_dates <span class="op">=</span> y_te.index</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">10</span>), sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>channel_names <span class="op">=</span> [<span class="st">"mu"</span>, <span class="st">"phi"</span>, <span class="st">"g"</span>]</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>channel_labels <span class="op">=</span> [<span class="vs">r"</span><span class="dv">$\m</span><span class="vs">u_t</span><span class="dv">$</span><span class="vs"> </span><span class="kw">(</span><span class="vs">level anchor</span><span class="kw">)</span><span class="vs">"</span>, <span class="vs">r"</span><span class="dv">$</span><span class="er">\</span><span class="vs">phi_t</span><span class="dv">$</span><span class="vs"> </span><span class="kw">(</span><span class="vs">persistence</span><span class="kw">)</span><span class="vs">"</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">g_t</span><span class="dv">$</span><span class="vs"> </span><span class="kw">(</span><span class="vs">innovation share</span><span class="kw">)</span><span class="vs">"</span>]</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (ch, ch_label) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">zip</span>(channel_names, channel_labels)):</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> axes[i]</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j, (label, (mod, X_mod)) <span class="kw">in</span> <span class="bu">enumerate</span>(models_to_plot.items()):</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>        comps <span class="op">=</span> mod.predict_components(X_mod.values)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>        ax.plot(test_dates, comps[ch], label<span class="op">=</span>label, color<span class="op">=</span>BLOG_PALETTE[j],</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>                alpha<span class="op">=</span><span class="fl">0.8</span>, linewidth<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(ch_label)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    ax.legend(loc<span class="op">=</span><span class="st">"upper right"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>axes[<span class="op">-</span><span class="dv">1</span>].set_xlabel(<span class="st">"Date"</span>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">"Structural Parameters Over the Test Period"</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="9f6ca218" class="cell">
<details class="code-fold">
<summary>Channel summary statistics (test period)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>summary_rows <span class="op">=</span> []</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, (mod, X_mod) <span class="kw">in</span> models_to_plot.items():</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    comps <span class="op">=</span> mod.predict_components(X_mod.values)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ch <span class="kw">in</span> [<span class="st">"mu"</span>, <span class="st">"phi"</span>, <span class="st">"g"</span>]:</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        vals <span class="op">=</span> comps[ch]</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        summary_rows.append({</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Model"</span>: label,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Channel"</span>: ch,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Mean"</span>: np.mean(vals),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Std"</span>: np.std(vals),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Min"</span>: np.<span class="bu">min</span>(vals),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Max"</span>: np.<span class="bu">max</span>(vals),</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>            <span class="st">"CV"</span>: np.std(vals) <span class="op">/</span> <span class="bu">max</span>(np.mean(vals), <span class="fl">1e-12</span>),</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>summary_df <span class="op">=</span> pd.DataFrame(summary_rows)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>display(style_results_table(summary_df, precision<span class="op">=</span><span class="dv">6</span>, index_col<span class="op">=</span><span class="st">"Model"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<h2 data-number="9" id="coefficient-and-allocation-diagnostics" class="anchored"><span class="header-section-number">9</span> Coefficient and Allocation Diagnostics</h2>
<p>Coefficient inspection is useful here as a diagnostic, not as a victory lap. The question is whether differential shrinkage actually steers features toward their intended roles, and whether any such steering is strong enough to support the structural story told in the setup section.</p>
<p>That is a stricter standard than simply finding large coefficients. A publication-ready reading has to ask whether the intended allocation is visible in the fitted weights, and whether the answer is strong enough to explain the forecasting outcomes.</p>
<div id="bed3ba3b" class="cell">
<details class="code-fold">
<summary>Per-channel coefficient analysis for Model C</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _extract_channel_coefs(model, feat_cols):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">'''Extract per-channel coefficients (on the standardised scale).'''</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    theta <span class="op">=</span> model.theta_</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    block <span class="op">=</span> <span class="bu">len</span>(theta) <span class="op">//</span> <span class="dv">3</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># First element of each block is the intercept</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    w_mu <span class="op">=</span> theta[:block]</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    w_phi <span class="op">=</span> theta[block:<span class="dv">2</span><span class="op">*</span>block]</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    w_g <span class="op">=</span> theta[<span class="dv">2</span><span class="op">*</span>block:]</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Skip intercept (index 0)</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.DataFrame({</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Feature"</span>: feat_cols,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Group"</span>: [_assign_group(f) <span class="cf">for</span> f <span class="kw">in</span> feat_cols],</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Primary channel"</span>: [_assign_channel(f) <span class="cf">for</span> f <span class="kw">in</span> feat_cols],</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"w_mu"</span>: w_mu[<span class="dv">1</span>:],</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"w_phi"</span>: w_phi[<span class="dv">1</span>:],</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"w_g"</span>: w_g[<span class="dv">1</span>:],</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"|w_mu|"</span>: np.<span class="bu">abs</span>(w_mu[<span class="dv">1</span>:]),</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">"|w_phi|"</span>: np.<span class="bu">abs</span>(w_phi[<span class="dv">1</span>:]),</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"|w_g|"</span>: np.<span class="bu">abs</span>(w_g[<span class="dv">1</span>:]),</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>coef_df <span class="op">=</span> _extract_channel_coefs(model_c, expanded_feat_cols)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Top features per channel</span></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ch, label <span class="kw">in</span> [(<span class="st">"mu"</span>, <span class="st">"mu (level)"</span>), (<span class="st">"phi"</span>, <span class="st">"phi (persistence)"</span>), (<span class="st">"g"</span>, <span class="st">"g (innovation)"</span>)]:</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span><span class="st">'='</span><span class="op">*</span><span class="dv">60</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Top 15 features in </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> channel (|w_</span><span class="sc">{</span>ch<span class="sc">}</span><span class="ss">|):"</span>)</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'='</span><span class="op">*</span><span class="dv">60</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>    top <span class="op">=</span> coef_df.nlargest(<span class="dv">15</span>, <span class="ss">f"|w_</span><span class="sc">{</span>ch<span class="sc">}</span><span class="ss">|"</span>)[[<span class="st">"Feature"</span>, <span class="st">"Group"</span>, <span class="st">"Primary channel"</span>, <span class="ss">f"w_</span><span class="sc">{</span>ch<span class="sc">}</span><span class="ss">"</span>, <span class="ss">f"|w_</span><span class="sc">{</span>ch<span class="sc">}</span><span class="ss">|"</span>]]</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(top.to_string(index<span class="op">=</span><span class="va">False</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="f5cc4f56" class="cell">
<details class="code-fold">
<summary>Channel coefficient heatmap (top 20 features by total importance)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>coef_df[<span class="st">"total_importance"</span>] <span class="op">=</span> coef_df[<span class="st">"|w_mu|"</span>] <span class="op">+</span> coef_df[<span class="st">"|w_phi|"</span>] <span class="op">+</span> coef_df[<span class="st">"|w_g|"</span>]</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>top20 <span class="op">=</span> coef_df.nlargest(<span class="dv">20</span>, <span class="st">"total_importance"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">10</span>))</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>data_to_plot <span class="op">=</span> top20[[<span class="st">"w_mu"</span>, <span class="st">"w_phi"</span>, <span class="st">"w_g"</span>]].values</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>feat_labels <span class="op">=</span> top20[<span class="st">"Feature"</span>].values</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>im <span class="op">=</span> ax.imshow(data_to_plot, cmap<span class="op">=</span><span class="st">"RdBu_r"</span>, aspect<span class="op">=</span><span class="st">"auto"</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>               vmin<span class="op">=-</span>np.<span class="bu">abs</span>(data_to_plot).<span class="bu">max</span>(), vmax<span class="op">=</span>np.<span class="bu">abs</span>(data_to_plot).<span class="bu">max</span>())</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>ax.set_xticks([<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>])</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels([<span class="vs">r"</span><span class="dv">$</span><span class="vs">w_</span><span class="dv">\m</span><span class="vs">u</span><span class="dv">$</span><span class="vs">"</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">w_</span><span class="er">\</span><span class="vs">phi</span><span class="dv">$</span><span class="vs">"</span>, <span class="vs">r"</span><span class="dv">$</span><span class="vs">w_g</span><span class="dv">$</span><span class="vs">"</span>], fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>ax.set_yticks(<span class="bu">range</span>(<span class="bu">len</span>(feat_labels)))</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>ax.set_yticklabels(feat_labels, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Standardised Coefficients by Channel (Model C, Top 20)"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>fig.colorbar(im, ax<span class="op">=</span>ax, shrink<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span><span class="st">"Coefficient"</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="e38e9fb7" class="cell">
<details class="code-fold">
<summary>Validate channel allocation: fraction of weight in primary vs other channels</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _allocation_score(row):</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">'''Fraction of total absolute weight in the primary channel.'''</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    total <span class="op">=</span> row[<span class="st">"|w_mu|"</span>] <span class="op">+</span> row[<span class="st">"|w_phi|"</span>] <span class="op">+</span> row[<span class="st">"|w_g|"</span>]</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> total <span class="op">&lt;</span> <span class="fl">1e-12</span>:</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.nan</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    ch_map <span class="op">=</span> {<span class="st">"g (innovation)"</span>: <span class="st">"|w_g|"</span>, <span class="st">"phi (persistence)"</span>: <span class="st">"|w_phi|"</span>, <span class="st">"mu (level)"</span>: <span class="st">"|w_mu|"</span>}</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    primary_col <span class="op">=</span> ch_map.get(row[<span class="st">"Primary channel"</span>], <span class="st">"|w_mu|"</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> row[primary_col] <span class="op">/</span> total</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>coef_df[<span class="st">"allocation_score"</span>] <span class="op">=</span> coef_df.<span class="bu">apply</span>(_allocation_score, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Group-level summary</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>alloc_summary <span class="op">=</span> coef_df.groupby(<span class="st">"Primary channel"</span>).agg(</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    n_features<span class="op">=</span>(<span class="st">"Feature"</span>, <span class="st">"count"</span>),</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    mean_alloc<span class="op">=</span>(<span class="st">"allocation_score"</span>, <span class="st">"mean"</span>),</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    median_alloc<span class="op">=</span>(<span class="st">"allocation_score"</span>, <span class="st">"median"</span>),</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    mean_total_w<span class="op">=</span>(<span class="st">"total_importance"</span>, <span class="st">"mean"</span>),</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>).<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Allocation validation: fraction of weight in the intended channel"</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"(higher = regularisation is steering features as intended)</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>display(style_results_table(alloc_summary, precision<span class="op">=</span><span class="dv">4</span>, index_col<span class="op">=</span><span class="st">"Primary channel"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The diagnostic evidence is mixed but informative. Relative to the Part 5 baseline, the structured models move more variation into the level and persistence channels and keep the <span class="math inline">g_t</span> path more stable when the <span class="math inline">g</span> penalty is kept high. But the allocation-score table also shows the limit of this approach: shrinkage alone does not produce a clean channel separation, especially for features intended for the innovation channel. The structural prior is only partially enforced, which helps explain why interpretability improved more than forecast accuracy.</p>
<div id="cd72aa7a" class="cell">
<details class="code-fold">
<summary>Forecast paths: GARCH vs PGARCH-L baseline vs Structured (2019-2021 window)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>window_start <span class="op">=</span> pd.Timestamp(<span class="st">"2019-01-01"</span>, tz<span class="op">=</span><span class="st">"UTC"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>window_end <span class="op">=</span> pd.Timestamp(<span class="st">"2021-12-31"</span>, tz<span class="op">=</span><span class="st">"UTC"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>test_dates <span class="op">=</span> y_te.index</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> (test_dates <span class="op">&gt;=</span> window_start) <span class="op">&amp;</span> (test_dates <span class="op">&lt;=</span> window_end)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>plot_dates <span class="op">=</span> test_dates[mask]</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">5</span>))</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>ax.plot(plot_dates, y_te.values[mask], label<span class="op">=</span><span class="st">"Realised ($y_t = r_t^2$)"</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>BLOG_PALETTE[<span class="dv">4</span>], alpha<span class="op">=</span><span class="fl">0.4</span>, linewidth<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>ax.plot(plot_dates, garch_pred_os[mask], label<span class="op">=</span><span class="st">"GARCH(1,1)"</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>BLOG_PALETTE[<span class="dv">2</span>], linewidth<span class="op">=</span><span class="fl">1.0</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>ax.plot(plot_dates, h_a_os[mask], label<span class="op">=</span><span class="st">"A: PGARCH-L baseline"</span>,</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>BLOG_PALETTE[<span class="dv">3</span>], linewidth<span class="op">=</span><span class="fl">1.0</span>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>ax.plot(plot_dates, h_c_os[mask], label<span class="op">=</span><span class="st">"C: Structured (rich mu, lean g)"</span>,</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>BLOG_PALETTE[<span class="dv">0</span>], linewidth<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Variance"</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Forecast Paths: 2019–2021 (includes COVID spike)"</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"upper right"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<h2 data-number="10" id="nonlinear-preview-and-boundary-of-part-6" class="anchored"><span class="header-section-number">10</span> Nonlinear Preview and Boundary of Part 6</h2>
<p>Part 6 includes only a boundary check on the full <code>XGBPGARCHModel</code>. It is not a Part 7-style model search. The purpose is narrower: if the all-feature linear PGARCH variants stall, is the natural next branch a boosted three-channel update rather than another minor linear reparameterization?</p>
<p>The answer from this notebook is provisional. The preview does not produce a usable nonlinear comparison because the default <code>linear_pgarch</code> initializer fails on the expanded design. That failure should not be read as evidence that the nonlinear branch loses. It should also not be read as a win. It shows that once the feature set is widened, the nonlinear PGARCH line already depends on initialization discipline before any substantive comparison can be made.</p>
<div id="f2a40f3c" class="cell">
<details class="code-fold">
<summary>Fit full XGBPGARCHModel (optional — may be slow)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="im">from</span> volatility_forecast.model.xgb_pgarch_full_model <span class="im">import</span> XGBPGARCHModel</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    y_tr_scaled <span class="op">=</span> y_tr.values <span class="op">*</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    y_all_scaled <span class="op">=</span> y_all.values <span class="op">*</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    xgb_full <span class="op">=</span> XGBPGARCHModel(</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>        loss<span class="op">=</span><span class="st">"qlike"</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        n_outer_rounds<span class="op">=</span><span class="dv">25</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>        trees_per_channel_per_round<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>        learning_rate<span class="op">=</span><span class="fl">0.02</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        max_depth<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>        min_child_weight<span class="op">=</span><span class="fl">5.0</span>,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>        reg_lambda<span class="op">=</span><span class="fl">1.0</span>,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>        init_method<span class="op">=</span><span class="st">"linear_pgarch"</span>,</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>        random_state<span class="op">=</span>RANDOM_STATE,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>        verbosity<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    xgb_full.fit(y_tr_scaled, X_exp_tr)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>    h_xgb_full_scaled <span class="op">=</span> xgb_full.predict_variance(y_all_scaled, X_exp_all)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>    h_xgb_full <span class="op">=</span> h_xgb_full_scaled <span class="op">/</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    h_xgb_full_is <span class="op">=</span> h_xgb_full[:<span class="bu">len</span>(y_tr)]</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    h_xgb_full_os <span class="op">=</span> h_xgb_full[<span class="bu">len</span>(y_tr):]</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>    xgb_full_rmse_os <span class="op">=</span> rmse(actual_os, h_xgb_full_os)</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>    xgb_full_qlike_os <span class="op">=</span> qlike(actual_os, h_xgb_full_os)</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"XGBPGARCHModel (full): OS RMSE = </span><span class="sc">{</span>xgb_full_rmse_os<span class="sc">:.6f}</span><span class="ss">, OS QLIKE = </span><span class="sc">{</span>xgb_full_qlike_os<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># DM test vs Model C</span></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>    loss_xgb <span class="op">=</span> _qlike_loss(actual_os, h_xgb_full_os)</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>    loss_c <span class="op">=</span> _qlike_loss(actual_os, h_c_os)</span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>    dm_xgb_vs_c <span class="op">=</span> diebold_mariano(loss_xgb, loss_c)</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"DM (XGBPGARCHModel vs Model C, QLIKE): stat=</span><span class="sc">{</span>dm_xgb_vs_c[<span class="st">'dm_stat'</span>]<span class="sc">:.3f}</span><span class="ss">, p=</span><span class="sc">{</span>dm_xgb_vs_c[<span class="st">'p_value'</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>    _xgb_full_available <span class="op">=</span> <span class="va">True</span></span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"XGBPGARCHModel comparison skipped: </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>    _xgb_full_available <span class="op">=</span> <span class="va">False</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="6f1a94eb" class="cell">
<details class="code-fold">
<summary>Final combined results table</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>final_rows <span class="op">=</span> <span class="bu">list</span>(rows)  <span class="co"># from the earlier performance table</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> _xgb_full_available:</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    final_rows.append({</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Model"</span>: <span class="st">"F: XGBPGARCHModel (full)"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"IS RMSE"</span>: rmse(actual_is, h_xgb_full_is),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS RMSE"</span>: xgb_full_rmse_os,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"IS QLIKE"</span>: qlike(actual_is, h_xgb_full_is),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS QLIKE"</span>: xgb_full_qlike_os,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>final_df <span class="op">=</span> pd.DataFrame(final_rows).set_index(<span class="st">"Model"</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>final_df <span class="op">=</span> final_df.sort_values(<span class="st">"OS QLIKE"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>display(style_results_table(final_df, precision<span class="op">=</span><span class="dv">6</span>, index_col<span class="op">=</span><span class="st">"Model"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<h2 data-number="11" id="what-part-6-actually-learned" class="anchored"><span class="header-section-number">11</span> What Part 6 Actually Learned</h2>
<p>Part 6 leaves a cleaner result than the original draft suggested.</p>
<p>First, the Part 5 three-feature <code>PGARCH-L</code> baseline remains the strongest specification inside this notebook. It posts the best OS QLIKE among the evaluated fits.</p>
<p>Second, expanding the feature set inside linear PGARCH is not enough by itself. Models B through E all fit the training sample better than Model A, but each one loses ground out of sample. The Part 6 problem is therefore not lack of in-sample flexibility. It is controlling how richer information enters the recursion without paying too much variance.</p>
<p>Third, the structural story is still useful. The channel plots and coefficient tables indicate that richer predictors can move the level and persistence channels in economically interpretable ways, while the <span class="math inline">g_t</span> channel becomes much less stable when its penalty is relaxed. That is not a forecasting win, but it is enough to keep channel-specific modeling alive as an active branch at this stage of the series.</p>
<p>Fourth, the nonlinear extension remains unresolved rather than rejected. The full boosted preview fails at initialization, which identifies a concrete technical obstacle and a natural next search step.</p>
<h2 data-number="12" id="limitations" class="anchored"><span class="header-section-number">12</span> Limitations</h2>
<p>The limitations are direct. Part 6 does not deliver an expanded-feature model that clears <code>GARCH(1,1)</code> on OS QLIKE. It also does not show that differential regularization alone can produce a clean channel allocation; the allocation-score table shows only partial steering, especially in the intended innovation channel. Finally, the nonlinear preview is incomplete because the initializer failed before a fair boosted comparison was available.</p>
<p>Those limitations are not incidental. They are the reason this post is an intermediate result rather than a final victory post.</p>
<h2 data-number="13" id="handoff-to-part-7" class="anchored"><span class="header-section-number">13</span> Handoff to Part 7</h2>
<p>Part 7 is therefore the broader search-and-stress-test phase, not a retroactive correction to Part 6. Part 6 leaves the series with a live but unresolved branch: richer PGARCH specifications remain plausible, but the all-feature linear versions overfit and the first full nonlinear preview is blocked by initialization.</p>
<p>The natural next search step is to keep the benchmark, target, and QLIKE-based decision rule fixed while broadening the specification search inside the PGARCH and XGBPGARCH line. That means testing whether the encouraging ideas from Part 6 survive alternative feature allocations, narrower screened subsets, better initialization discipline, and stronger robustness checks. In that sense Part 7 extends Part 6 rather than overturning it. The question shifts from whether richer structure can help in principle to which richer structure, if any, survives a wider and stricter search.</p>
<h2 data-number="14" id="appendix-implied-garch-parameters" class="anchored"><span class="header-section-number">14</span> Appendix: Implied GARCH Parameters</h2>
<p>For interpretability, we convert the structured PGARCH-L coefficients into implied <span class="math inline">\omega_t = (1-\phi_t)\mu_t</span>, <span class="math inline">\alpha_t = \phi_t g_t</span>, and <span class="math inline">\beta_t = \phi_t(1-g_t)</span> and report their test-period statistics.</p>
<div id="1eacfee8" class="cell">
<details class="code-fold">
<summary>Implied GARCH parameters for selected models</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>impl_rows <span class="op">=</span> []</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, (mod, X_mod) <span class="kw">in</span> models_to_plot.items():</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    impl <span class="op">=</span> mod.implied_garch_params(X_mod.values)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> param <span class="kw">in</span> [<span class="st">"omega"</span>, <span class="st">"alpha"</span>, <span class="st">"beta"</span>]:</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>        vals <span class="op">=</span> impl[param]</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>        impl_rows.append({</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Model"</span>: label,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Parameter"</span>: param,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Mean"</span>: np.mean(vals),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Std"</span>: np.std(vals),</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Min"</span>: np.<span class="bu">min</span>(vals),</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Max"</span>: np.<span class="bu">max</span>(vals),</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>impl_df <span class="op">=</span> pd.DataFrame(impl_rows)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>display(style_results_table(impl_df, precision<span class="op">=</span><span class="dv">6</span>, index_col<span class="op">=</span><span class="st">"Model"</span>))</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparison with static GARCH(1,1)</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Static GARCH(1,1) parameters for reference:"</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  omega = </span><span class="sc">{</span>omega_g<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  alpha = </span><span class="sc">{</span>alpha_g<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  beta  = </span><span class="sc">{</span>beta_g<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>


<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button,
          { trigger: "manual",
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/steveya\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined;
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              }
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            }
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>