project:
  type: website
  output-dir: docs

website:
  title: "Steve Yang"
  site-url: "https://steveya.github.io"
  description: "Updates on quantitative analysis, data science, and ML education."
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: pages/projects.qmd
      - text: "Archives"
        href: pages/archives.qmd
      - text: "Categories"
        href: pages/categories.qmd
      - text: "Tags"
        href: pages/tags.qmd
      - text: "About"
        href: pages/about.qmd
  page-footer:
    center: "© Steve Yang"

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    mathjax: true

execute:
  freeze: auto
  enabled: false
