<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-03">
<meta name="description" content="We keep RMSE for benchmark comparability, then refit STES and XGBSTES under QLIKE to see how the training loss changes out-of-sample ranking and calibration.">

<title>Volatility Forecasts (Part 4 — RMSE Benchmarks and QLIKE Training) – Steve Yang</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-html-eb71d4f0124c4d5ff63526840ab633f6.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body>

<nav class="site-nav">
  <a href="../../">Home</a>
  <a href="../../pages/series.html">Series</a>
  <a href="../../pages/projects.html">Projects</a>
  <a href="../../pages/categories.html">Categories</a>
  <a href="../../pages/about.html">About</a>

  <span class="site-nav-spacer"></span>
  <a href="../../pages/search.html">Search</a>
</nav>

<header id="title-block-header">
<h1 class="title">Volatility Forecasts (Part 4 — RMSE Benchmarks and QLIKE Training)</h1>

<p class="date">2026-03-03</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#methodology-same-models-different-training-objectives" id="toc-methodology-same-models-different-training-objectives"><span class="header-section-number">2</span> Methodology: Same Models, Different Training Objectives</a>
  <ul>
  <li><a href="#model-inventory" id="toc-model-inventory"><span class="header-section-number">2.1</span> Model inventory</a></li>
  <li><a href="#two-training-objectives" id="toc-two-training-objectives"><span class="header-section-number">2.2</span> Two training objectives</a></li>
  <li><a href="#the-qlike-objective" id="toc-the-qlike-objective"><span class="header-section-number">2.3</span> The QLIKE objective</a></li>
  </ul></li>
  <li><a href="#qlike-gradient-and-the-stes-jacobian" id="toc-qlike-gradient-and-the-stes-jacobian"><span class="header-section-number">3</span> QLIKE Gradient and the STES Jacobian</a>
  <ul>
  <li><a href="#step-1-per-element-gradient-of-qlike" id="toc-step-1-per-element-gradient-of-qlike"><span class="header-section-number">3.1</span> Step 1: Per-element gradient of QLIKE</a></li>
  <li><a href="#step-2-chain-rule-through-the-stes-recursion" id="toc-step-2-chain-rule-through-the-stes-recursion"><span class="header-section-number">3.2</span> Step 2: Chain rule through the STES recursion</a></li>
  <li><a href="#step-3-forward-sensitivity-recursion" id="toc-step-3-forward-sensitivity-recursion"><span class="header-section-number">3.3</span> Step 3: Forward sensitivity recursion</a></li>
  <li><a href="#step-4-assembling-the-gradient" id="toc-step-4-assembling-the-gradient"><span class="header-section-number">3.4</span> Step 4: Assembling the gradient</a></li>
  </ul></li>
  <li><a href="#xgbstes-with-qlike-training" id="toc-xgbstes-with-qlike-training"><span class="header-section-number">4</span> XGBSTES with QLIKE Training</a>
  <ul>
  <li><a href="#custom-gradient-and-hessian" id="toc-custom-gradient-and-hessian"><span class="header-section-number">4.1</span> Custom gradient and Hessian</a></li>
  <li><a href="#end-to-end-backward-pass" id="toc-end-to-end-backward-pass"><span class="header-section-number">4.2</span> End-to-end backward pass</a></li>
  </ul></li>
  <li><a href="#formal-comparison-and-calibration" id="toc-formal-comparison-and-calibration"><span class="header-section-number">5</span> Formal Comparison and Calibration</a>
  <ul>
  <li><a href="#reading-the-tables" id="toc-reading-the-tables"><span class="header-section-number">5.1</span> Reading the tables</a></li>
  </ul></li>
  <li><a href="#ranking-the-models-under-both-criteria" id="toc-ranking-the-models-under-both-criteria"><span class="header-section-number">6</span> Ranking the Models Under Both Criteria</a></li>
  <li><a href="#conclusion" id="toc-conclusion"><span class="header-section-number">7</span> Conclusion</a>
  <ul>
  <li><a href="#whats-next" id="toc-whats-next"><span class="header-section-number">7.1</span> What’s next</a></li>
  </ul></li>
  <li><a href="#appendix-garch11-model-recap-and-mle" id="toc-appendix-garch11-model-recap-and-mle"><span class="header-section-number">8</span> Appendix: GARCH(1,1) Model Recap and MLE</a>
  <ul>
  <li><a href="#the-model" id="toc-the-model"><span class="header-section-number">8.1</span> The model</a></li>
  <li><a href="#maximum-likelihood-estimation" id="toc-maximum-likelihood-estimation"><span class="header-section-number">8.2</span> Maximum likelihood estimation</a></li>
  <li><a href="#mle-is-qlike" id="toc-mle-is-qlike"><span class="header-section-number">8.3</span> MLE is QLIKE</a></li>
  <li><a href="#why-not-fit-garch-under-mse" id="toc-why-not-fit-garch-under-mse"><span class="header-section-number">8.4</span> Why not fit GARCH under MSE?</a></li>
  </ul></li>
  </ul>
</nav>
<h2 data-number="1" id="introduction" class="anchored"><span class="header-section-number">1</span> Introduction</h2>
<p>In <a href="../volatility-forecasts-3/">Part 3</a> we showed that replacing the fixed smoothing coefficient in exponential smoothing with a learned gate improves one-step-ahead volatility forecasts. The best model in that post was <strong>XGBSTES</strong>, where the gate is learned by a gradient-boosted linear model rather than a single logistic regression. Every result so far has been trained and scored under RMSE, following the paper from <a href="../volatility-forecasts-1/">Part 1</a> (<a href="https://doi.org/10.1002/for.2648">Liu, Taylor &amp; Choo, 2020</a>).</p>
<p>Before adding new covariates, we want to settle a more basic modeling choice: <strong>what loss function should train the model?</strong> RMSE is a common choice for forecasting task in general, but for variance forecasts the more natural objective is often <strong>QLIKE</strong>.</p>
<p>The case for QLIKE rests on two properties established in the forecast-evaluation literature. First, <a href="https://doi.org/10.1016/j.jeconom.2010.07.008">Patton (2011)</a> showed that QLIKE belongs to the class of loss functions that are <em>robust</em> to noise in the volatility proxy — it ranks forecasts consistently even when realized variance is measured with error. Second, <a href="https://doi.org/10.1198/073500105000000063">Hansen and Lunde (2005)</a> demonstrated that QLIKE provides a <em>consistent</em> ranking function for conditional-variance models, meaning the best forecast under the population criterion wins in large samples regardless of the proxy used.</p>
<p>Practically, the difference matters because RMSE is level-sensitive: a few large volatility spikes dominate the score. QLIKE evaluates forecasts proportionally, so it is more informative about whether the model is systematically too high or too low as a <em>variance</em> forecast, not just whether it tracks large episodes in absolute magnitude. A model can look strong under RMSE by following big moves, yet score poorly under QLIKE because it is miscalibrated on a proportional basis. Rather than choosing one metric by convention, this post compares both directly.</p>
<p>The questions are:</p>
<ol type="1">
<li><strong>Do the MSE-trained models still compare well on the fixed split from the earlier posts?</strong></li>
<li><strong>What changes when we retrain each model family under QLIKE, keeping the same features and split?</strong></li>
<li><strong>Do MSE and QLIKE lead to different out-of-sample rankings or calibration judgments?</strong></li>
</ol>
<p>We keep the same SPY sample spanning January 2000 through December 2023. As in Part 3, we use the first 200 observations as warm-up, use observations 201 through 4,000 for estimation, and reserve the remainder for out-of-sample evaluation. The target remains next-day squared return. The scope of this post is limited to the QLIKE loss-function question. We derive the QLIKE gradient for STES, show how it enters the XGBSTES custom objective, and compare all seven model variants empirically. Regularization and feature expansion are deferred to <a href="../volatility-forecasts-5/">Part 5</a>.</p>
<h2 data-number="2" id="methodology-same-models-different-training-objectives" class="anchored"><span class="header-section-number">2</span> Methodology: Same Models, Different Training Objectives</h2>
<h3 data-number="2.1" id="model-inventory" class="anchored"><span class="header-section-number">2.1</span> Model inventory</h3>
<p>We compare four baseline architectures on the same fixed split. Let <span class="math inline">y_{t+1} = r_{t+1}^2</span> denote next-day realized variance and let <span class="math inline">\hat v_{t+1 \vert t}</span> denote the one-step-ahead forecast formed at time <span class="math inline">t</span>.</p>
<ul>
<li><strong>GARCH(1,1)</strong>: the standard parametric conditional-variance benchmark fit by maximum likelihood.</li>
<li><strong>ES</strong>: exponential smoothing with a fixed coefficient.</li>
<li><strong>STES</strong>: smooth-transition exponential smoothing with a logistic gate <span class="math inline">\alpha_t = \sigma(x_t^\top \beta)</span>.</li>
<li><strong>XGBSTES</strong>: the same smoothing recursion, but with the gate produced by a boosted linear model <span class="math inline">f_{\text{XGB}}(x_t)</span>.</li>
</ul>
<p>The <strong>feature set stays fixed</strong> throughout this post. Every STES and XGBSTES model uses the same three return-based inputs from Part 3 — lagged return, lagged absolute return, and lagged squared return. The only thing that changes is the training objective.</p>
<h3 data-number="2.2" id="two-training-objectives" class="anchored"><span class="header-section-number">2.2</span> Two training objectives</h3>
<p>To make the comparison fair, we train every model under both RMSE and QLIKE where possible. ES, STES, and XGBSTES each appear twice — once trained under squared error, once under QLIKE. That gives us six model–loss variants, plus GARCH.</p>
<p><strong>GARCH is already QLIKE-trained.</strong> As the <a href="#appendix-garch11-model-recap-and-mle">appendix</a> shows, GARCH’s Gaussian MLE objective is mathematically equivalent to the QLIKE loss — the two produce exactly the same parameter estimates. GARCH therefore naturally sits on the QLIKE side of the comparison. We keep it as a single MLE-fitted model, giving us <strong>seven model variants</strong> in total.</p>
<h3 data-number="2.3" id="the-qlike-objective" class="anchored"><span class="header-section-number">2.3</span> The QLIKE objective</h3>
<p>For a variance forecast <span class="math inline">\hat v_{t+1|t}(\theta)</span>, the per-observation QLIKE loss is</p>
<p><span class="math display">
\ell\bigl(y_{t+1}, \hat v_{t+1\vert t}\bigr)
= \frac{y_{t+1}}{\hat v_{t+1 \vert t}} - \log\left(\frac{y_{t+1}}{\hat v_{t+1 \vert t}}\right) - 1
</span></p>
<p>The <a href="#appendix-garch11-model-recap-and-mle">appendix</a> derives this loss from the Gaussian log-likelihood used to fit GARCH(1,1). In brief: maximizing the conditional log-likelihood of a Gaussian variance model is equivalent to minimizing <span class="math inline">\sum_t [\log \hat v_t + y_t / \hat v_t]</span>, and the per-observation QLIKE above is just this expression shifted by the constants <span class="math inline">-\log y_t - 1</span> so that <span class="math inline">\ell = 0</span> when <span class="math inline">\hat v_{t+1|t} = y_{t+1}</span> exactly.</p>
<p>The “quasi” in QLIKE means the Gaussian distributional assumption need not hold. <a href="https://doi.org/10.1016/j.jeconom.2010.07.008">Patton (2011)</a> showed that QLIKE ranks forecasts consistently even when the true return distribution is non-Gaussian, as long as the conditional mean of <span class="math inline">y_{t+1}</span> equals the forecast target. That robustness is what makes it attractive for variance models, where the Gaussian assumption is routinely violated.</p>
<p>The training objective sums this over the estimation sample:</p>
<p><span class="math display">
\mathcal{L}_{\text{QLIKE}}(\theta) = \sum_{t=s}^{T-1} \ell\bigl(y_{t+1}, \hat v_{t+1 \vert t}(\theta)\bigr)
</span></p>
<p>Both STES and XGBSTES use light L2 regularization in this post. For STES, we select the L2 penalty from a small grid via three-fold cross-validation. For XGBSTES, XGBoost’s built-in <code>reg_lambda</code> provides the same role. This keeps the gate weights from drifting too far; the heavier regularization machinery — adaptive lasso and elastic net — arrives in <a href="../volatility-forecasts-5/">Part 5</a> once we expand the feature set.</p>
<p>For ES, we simply fit an <code>STESModel</code> with a constant-only feature under <code>loss="qlike"</code>, which reduces the logistic gate to a single optimized smoothing coefficient. For STES, <span class="math inline">\theta = \beta</span> enters through the logistic gate. For XGBSTES, the gate is still learned end-to-end, but the boosted linear weights are chosen to minimize the same QLIKE target rather than squared error. The sections below derive the gradients that make this possible.</p>
<h2 data-number="3" id="qlike-gradient-and-the-stes-jacobian" class="anchored"><span class="header-section-number">3</span> QLIKE Gradient and the STES Jacobian</h2>
<p>This section derives the gradient that lets us train STES under QLIKE using <code>scipy.optimize.minimize</code> with L-BFGS-B. The derivation parallels the RMSE Jacobian from <a href="../volatility-forecasts-3/">Part 3</a>, and the same sensitivity recursion applies — the only thing that changes is how the loss couples to the forecast.</p>
<h3 data-number="3.1" id="step-1-per-element-gradient-of-qlike" class="anchored"><span class="header-section-number">3.1</span> Step 1: Per-element gradient of QLIKE</h3>
<p>The per-observation QLIKE loss at time <span class="math inline">t</span> is</p>
<p><span class="math display">
\ell_t = \frac{y_{t+1}}{\hat v_{t+1 \vert t}} - \log\left(\frac{y_{t+1}}{\hat v_{t+1 \vert t}}\right) - 1
</span></p>
<p>Differentiating with respect to the forecast <span class="math inline">\hat v \equiv \hat v_{t+1 \vert t}</span>:</p>
<p><span class="math display">
\frac{\partial \ell_t}{\partial \hat v}
= -\frac{y_{t+1}}{\hat v^2} + \frac{1}{\hat v}
= \frac{\hat v - y_{t+1}}{\hat v^2}
</span></p>
<p>This is the key quantity. When <span class="math inline">\hat v &gt; y_{t+1}</span> the gradient is positive (the forecast is too high, push it down); when <span class="math inline">\hat v &lt; y_{t+1}</span> it is negative (push it up). The <span class="math inline">\hat v^2</span> denominator makes the gradient automatically <em>scale-aware</em> — small forecasts receive proportionally stronger corrections than large ones. Compare this with the RMSE gradient <span class="math inline">\partial \ell^{\text{MSE}}_t / \partial \hat v = 2(\hat v - y_{t+1})</span>, which treats all forecast levels equally.</p>
<h3 data-number="3.2" id="step-2-chain-rule-through-the-stes-recursion" class="anchored"><span class="header-section-number">3.2</span> Step 2: Chain rule through the STES recursion</h3>
<p>Recall the STES forecast recursion from Part 3:</p>
<p><span class="math display">
\hat v_{t+1|t} = \alpha_t \, r_t^2 + (1 - \alpha_t) \, \hat v_{t|t-1}, \qquad \alpha_t = \sigma(x_t^\top \beta).
</span></p>
<p>The total QLIKE objective is <span class="math inline">\mathcal{L}(\beta) = \sum_t \ell_t</span>, and by the chain rule</p>
<p><span class="math display">
\frac{\partial \mathcal{L}}{\partial \beta_j}
= \sum_t \frac{\partial \ell_t}{\partial \hat v_{t+1|t}} \cdot \frac{\partial \hat v_{t+1|t}}{\partial \beta_j}.
</span></p>
<p>The second factor, <span class="math inline">\partial \hat v_{t+1|t} / \partial \beta_j</span>, is the <em>sensitivity</em> of the forecast to each gate parameter. It does not depend on the choice of loss and is purely a property of the STES recursion.</p>
<h3 data-number="3.3" id="step-3-forward-sensitivity-recursion" class="anchored"><span class="header-section-number">3.3</span> Step 3: Forward sensitivity recursion</h3>
<p>Instead of differentiating the loss end-to-end in one pass, we separate the calculation into a <em>forward recursion</em> that propagates parameter sensitivities through the STES state, and a <em>backward weighting</em> that multiplies those sensitivities by the per-step loss gradient. The forward pass computes how each parameter nudges the forecast at every time step; the backward weighting (Step 1) tells us how much that nudge costs. This two-part structure is the same idea behind backpropagation in neural networks — we reuse the forward sensitivities for any choice of loss, and only swap the backward weights when we switch from RMSE to QLIKE.</p>
<p>In Part 3 we derived the forward-mode recursion for this sensitivity. Defining <span class="math inline">D_{t+1,j} = \partial \hat v_{t+1|t} / \partial \beta_j</span>, the recursion is</p>
<p><span class="math display">
D_{t+1,j} = \alpha_t (1 - \alpha_t)\, x_{t,j}\, (r_t^2 - \hat v_{t|t-1}) + (1 - \alpha_t)\, D_{t,j},
</span></p>
<p>initialized at <span class="math inline">D_{1,j} = 0</span>. This is identical for RMSE and QLIKE — the recursion propagates sensitivities independently of the loss function.</p>
<h3 data-number="3.4" id="step-4-assembling-the-gradient" class="anchored"><span class="header-section-number">3.4</span> Step 4: Assembling the gradient</h3>
<p>Combining Steps 1–3, the full QLIKE gradient is</p>
<p><span class="math display">
\frac{\partial \mathcal{L}}{\partial \beta_j}
= \sum_t \frac{\hat v_{t+1|t} - y_{t+1}}{\hat v_{t+1|t}^2} \cdot D_{t+1,j}.
</span></p>
<p>This is a scalar objective with an analytical gradient vector, so we pass it to <code>scipy.optimize.minimize</code> with the L-BFGS-B solver. This is the main structural difference from RMSE training: the RMSE path uses <code>scipy.optimize.least_squares</code>, which exploits the <em>vector</em> of residuals and the Jacobian matrix <span class="math inline">[D_{t+1,j}]_{t,j}</span> for Gauss-Newton steps. QLIKE cannot be decomposed into a sum of squared residuals, so we fall back to the general-purpose L-BFGS-B optimizer that only needs the scalar loss and its gradient.</p>
<h2 data-number="4" id="xgbstes-with-qlike-training" class="anchored"><span class="header-section-number">4</span> XGBSTES with QLIKE Training</h2>
<p>Switching XGBSTES from RMSE to QLIKE requires supplying XGBoost with a custom objective that returns per-leaf gradient and Hessian-diagonal values on the QLIKE scale. The end-to-end sensitivity backward pass from Part 3 carries over unchanged — only the top-level loss derivatives are different.</p>
<h3 data-number="4.1" id="custom-gradient-and-hessian" class="anchored"><span class="header-section-number">4.1</span> Custom gradient and Hessian</h3>
<p>XGBoost’s custom-objective interface expects, for each observation <span class="math inline">t</span>, a gradient <span class="math inline">g_t</span> and a Hessian diagonal <span class="math inline">h_t</span> of the loss with respect to the model’s raw prediction. For QLIKE these are:</p>
<p><span class="math display">
g_t = \frac{\hat v_{t+1|t} - y_{t+1}}{\hat v_{t+1|t}^2}, \qquad
h_t = \frac{2\, y_{t+1} - \hat v_{t+1|t}}{\hat v_{t+1|t}^3}.
</span></p>
<p>The gradient <span class="math inline">g_t</span> is the same expression derived in the previous section. The Hessian diagonal <span class="math inline">h_t</span> follows from differentiating <span class="math inline">g_t</span> once more with respect to <span class="math inline">\hat v_{t+1|t}</span>:</p>
<p><span class="math display">
h_t = \frac{\partial g_t}{\partial \hat v} = \frac{\partial}{\partial \hat v}\left[\frac{\hat v - y}{\hat v^2}\right] = \frac{2y - \hat v}{\hat v^3}.
</span></p>
<p>Note that <span class="math inline">h_t</span> can be negative when <span class="math inline">\hat v &gt; 2y</span> (i.e., the forecast is more than twice the realized variance). XGBoost handles this gracefully in the boosted-linear setting by regularizing the leaf weights.</p>
<h3 data-number="4.2" id="end-to-end-backward-pass" class="anchored"><span class="header-section-number">4.2</span> End-to-end backward pass</h3>
<p>In the end-to-end training mode, the STES recursion sits between XGBoost’s raw gate output and the final variance forecast. The backward pass propagates <span class="math inline">g_t</span> and <span class="math inline">h_t</span> through the sensitivity recursion to compute the gradient with respect to the boosted-linear gate parameters. This is the same forward-backward structure used for RMSE in Part 3 — the only change is that <span class="math inline">g_t</span> and <span class="math inline">h_t</span> are now computed from QLIKE rather than squared error. In practice, switching from RMSE to QLIKE training is a one-line change: set <code>loss="qlike"</code> in the model constructor.</p>
<div id="3c9d7a74" class="cell" data-execution_count="90">
<details class="code-fold">
<summary>Get previous STES/XGBSTES dataset (cache-only)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> volatility_forecast.pipeline <span class="im">import</span> build_vol_dataset, VolDatasetSpec</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> alphaforge.features.dataset_spec <span class="im">import</span> (</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    UniverseSpec, TimeSpec, FeatureRequest, TargetRequest, JoinPolicy, MissingnessPolicy,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> volatility_forecast.features.return_features <span class="im">import</span> (</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    LagLogReturnTemplate, LagAbsLogReturnTemplate, LagSquaredLogReturnTemplate,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> volatility_forecast.targets.squared_return <span class="im">import</span> NextDaySquaredReturnTarget</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> build_dataset_spec_sample(source: <span class="bu">str</span>, ticker: <span class="bu">str</span>, start, end, lags: <span class="bu">int</span>) <span class="op">-&gt;</span> VolDatasetSpec:</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    features <span class="op">=</span> (</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>        FeatureRequest(</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>            template<span class="op">=</span>LagLogReturnTemplate(),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>            params<span class="op">=</span>{<span class="st">"lags"</span>: lags, <span class="st">"source"</span>: source, <span class="st">"table"</span>: <span class="st">"market.ohlcv"</span>, <span class="st">"price_col"</span>: <span class="st">"close"</span>},</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>        FeatureRequest(</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>            template<span class="op">=</span>LagAbsLogReturnTemplate(),</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>            params<span class="op">=</span>{<span class="st">"lags"</span>: lags, <span class="st">"source"</span>: source, <span class="st">"table"</span>: <span class="st">"market.ohlcv"</span>, <span class="st">"price_col"</span>: <span class="st">"close"</span>},</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>        FeatureRequest(</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>            template<span class="op">=</span>LagSquaredLogReturnTemplate(),</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>            params<span class="op">=</span>{<span class="st">"lags"</span>: lags, <span class="st">"source"</span>: source, <span class="st">"table"</span>: <span class="st">"market.ohlcv"</span>, <span class="st">"price_col"</span>: <span class="st">"close"</span>},</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    target <span class="op">=</span> TargetRequest(</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>        template<span class="op">=</span>NextDaySquaredReturnTarget(),</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>        params<span class="op">=</span>{<span class="st">"source"</span>: source, <span class="st">"table"</span>: <span class="st">"market.ohlcv"</span>, <span class="st">"price_col"</span>: <span class="st">"close"</span>, <span class="st">"scale"</span>: <span class="fl">1.0</span>},</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>        horizon<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>        name<span class="op">=</span><span class="st">"y"</span>,</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> VolDatasetSpec(</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>        universe<span class="op">=</span>UniverseSpec(entities<span class="op">=</span>[ticker]),</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>        time<span class="op">=</span>TimeSpec(start<span class="op">=</span>start, end<span class="op">=</span>end, calendar<span class="op">=</span><span class="st">"XNYS"</span>, grid<span class="op">=</span><span class="st">"B"</span>, asof<span class="op">=</span><span class="va">None</span>),</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>        features<span class="op">=</span>features,</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>        target<span class="op">=</span>target,</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>        join_policy<span class="op">=</span>JoinPolicy(how<span class="op">=</span><span class="st">"inner"</span>, sort_index<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>        missingness<span class="op">=</span>MissingnessPolicy(final_row_policy<span class="op">=</span><span class="st">"drop_if_any_nan"</span>),</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>spec_sample <span class="op">=</span> build_dataset_spec_sample(</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    source<span class="op">=</span><span class="st">"tiingo"</span>,</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    ticker<span class="op">=</span>SAMPLE_TICKER,</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>    start<span class="op">=</span>SAMPLE_START,</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>    end<span class="op">=</span>SAMPLE_END,</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>    lags<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="co"># Cache-only context (same cache path/mode as script convention)</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>ctx_sample <span class="op">=</span> build_default_ctx(</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>    tiingo_api_key<span class="op">=</span>os.environ.get(<span class="st">"TIINGO_API"</span>) <span class="kw">or</span> os.environ.get(<span class="st">"TIINGO_API_KEY"</span>),</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>    tiingo_cache_backends<span class="op">=</span>[cache],</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>    tiingo_cache_mode<span class="op">=</span><span class="st">"use"</span>,</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>X_raw, y_raw, r_raw, _ <span class="op">=</span> build_vol_dataset(ctx_sample, spec_sample, persist<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">isinstance</span>(X_raw.index, pd.MultiIndex):</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>    X_par <span class="op">=</span> X_raw.xs(SAMPLE_TICKER, level<span class="op">=</span><span class="st">"entity_id"</span>).sort_index().astype(<span class="bu">float</span>)</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>    y_par <span class="op">=</span> y_raw.xs(SAMPLE_TICKER, level<span class="op">=</span><span class="st">"entity_id"</span>).sort_index().astype(<span class="bu">float</span>)</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>    r_par <span class="op">=</span> r_raw.xs(SAMPLE_TICKER, level<span class="op">=</span><span class="st">"entity_id"</span>).sort_index().astype(<span class="bu">float</span>)</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>    X_par <span class="op">=</span> X_raw.sort_index().astype(<span class="bu">float</span>)</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>    y_par <span class="op">=</span> y_raw.sort_index().astype(<span class="bu">float</span>)</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>    r_par <span class="op">=</span> r_raw.sort_index().astype(<span class="bu">float</span>)</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="st">"const"</span> <span class="kw">not</span> <span class="kw">in</span> X_par.columns:</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>    X_par[<span class="st">"const"</span>] <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="co"># Align all objects</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>common_idx <span class="op">=</span> X_par.index.intersection(y_par.index).intersection(r_par.index)</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>X_par <span class="op">=</span> X_par.loc[common_idx]</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>y_par <span class="op">=</span> y_par.loc[common_idx]</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>r_par <span class="op">=</span> r_par.loc[common_idx]</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample dataset rows: </span><span class="sc">{</span><span class="bu">len</span>(X_par)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample date range: </span><span class="sc">{</span>X_par<span class="sc">.</span>index<span class="sc">.</span><span class="bu">min</span>()<span class="sc">.</span>date()<span class="sc">}</span><span class="ss"> → </span><span class="sc">{</span>X_par<span class="sc">.</span>index<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>date()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Feature columns: </span><span class="sc">{</span><span class="bu">list</span>(X_par.columns)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sample dataset rows: 6035
Sample date range: 2000-01-04 → 2023-12-28
Feature columns: ['lag.logret.fc5d3612d9c7', 'lag.abslogret.1ad490bcb584', 'lag.sqlogret.c2cf3aa70c10', 'const']</code></pre>
</div>
</div>
<div id="19b9bb7d" class="cell" data-execution_count="91">
<details class="code-fold">
<summary>Fixed split and GARCH(1,1) setup</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> arch <span class="im">import</span> arch_model</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Match the historical Part 3 protocol exactly for the shared baseline block.</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>SAMPLE_TRAIN_START <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>SAMPLE_SPLIT_INDEX <span class="op">=</span> <span class="dv">4000</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">len</span>(X_par) <span class="op">&lt;=</span> SAMPLE_SPLIT_INDEX:</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">RuntimeError</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"Need more than </span><span class="sc">{</span>SAMPLE_SPLIT_INDEX<span class="sc">}</span><span class="ss"> rows for fixed split, got </span><span class="sc">{</span><span class="bu">len</span>(X_par)<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>X_tr <span class="op">=</span> X_par.iloc[SAMPLE_TRAIN_START:SAMPLE_SPLIT_INDEX]</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>X_te <span class="op">=</span> X_par.iloc[SAMPLE_SPLIT_INDEX:]</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>y_tr <span class="op">=</span> y_par.iloc[SAMPLE_TRAIN_START:SAMPLE_SPLIT_INDEX]</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>y_te <span class="op">=</span> y_par.iloc[SAMPLE_SPLIT_INDEX:]</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>r_tr <span class="op">=</span> r_par.iloc[SAMPLE_TRAIN_START:SAMPLE_SPLIT_INDEX]</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>r_te <span class="op">=</span> r_par.iloc[SAMPLE_SPLIT_INDEX:]</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Train rows: </span><span class="sc">{</span><span class="bu">len</span>(X_tr)<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>X_tr<span class="sc">.</span>index<span class="sc">.</span><span class="bu">min</span>()<span class="sc">.</span>date()<span class="sc">}</span><span class="ss"> → </span><span class="sc">{</span>X_tr<span class="sc">.</span>index<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>date()<span class="sc">}</span><span class="ss">)"</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Test rows:  </span><span class="sc">{</span><span class="bu">len</span>(X_te)<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>X_te<span class="sc">.</span>index<span class="sc">.</span><span class="bu">min</span>()<span class="sc">.</span>date()<span class="sc">}</span><span class="ss"> → </span><span class="sc">{</span>X_te<span class="sc">.</span>index<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>date()<span class="sc">}</span><span class="ss">)"</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co"># ── GARCH(1,1) ──────────────────────────────────────────────────────────</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit on training returns (percentage scale for numerical stability)</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>r_tr_pct <span class="op">=</span> r_tr <span class="op">*</span> <span class="fl">100.0</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>r_all_concat <span class="op">=</span> pd.concat([r_tr, r_te])</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>r_all_pct <span class="op">=</span> r_all_concat <span class="op">*</span> <span class="fl">100.0</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>garch_train_len <span class="op">=</span> <span class="bu">len</span>(r_tr)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>garch_spec <span class="op">=</span> arch_model(r_tr_pct, vol<span class="op">=</span><span class="st">"GARCH"</span>, p<span class="op">=</span><span class="dv">1</span>, q<span class="op">=</span><span class="dv">1</span>, mean<span class="op">=</span><span class="st">"Zero"</span>, rescale<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>garch_fit <span class="op">=</span> garch_spec.fit(disp<span class="op">=</span><span class="st">"off"</span>)</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>omega_g <span class="op">=</span> garch_fit.params[<span class="st">"omega"</span>]</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>alpha_g <span class="op">=</span> garch_fit.params[<span class="st">"alpha[1]"</span>]</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>beta_g <span class="op">=</span> garch_fit.params[<span class="st">"beta[1]"</span>]</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">GARCH(1,1) parameters: ω=</span><span class="sc">{</span>omega_g<span class="sc">:.6f}</span><span class="ss">, α=</span><span class="sc">{</span>alpha_g<span class="sc">:.4f}</span><span class="ss">, β=</span><span class="sc">{</span>beta_g<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a><span class="co"># IS one-step-ahead: σ²_{t+1} = ω + α·r²_t + β·σ²_t predicts y[t] = r²_{t+1}</span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>cv_sq_is <span class="op">=</span> garch_fit.conditional_volatility.values <span class="op">**</span> <span class="dv">2</span>  <span class="co"># σ²_t in pct²</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>r_sq_is <span class="op">=</span> r_tr_pct.values <span class="op">**</span> <span class="dv">2</span>                           <span class="co"># r²_t in pct²</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>garch_pred_is <span class="op">=</span> (omega_g <span class="op">+</span> alpha_g <span class="op">*</span> r_sq_is <span class="op">+</span> beta_g <span class="op">*</span> cv_sq_is) <span class="op">/</span> (<span class="fl">100.0</span> <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a><span class="co"># OS: fit on full data using only IS-estimated parameters, then forecast</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>garch_spec_full <span class="op">=</span> arch_model(r_all_pct, vol<span class="op">=</span><span class="st">"GARCH"</span>, p<span class="op">=</span><span class="dv">1</span>, q<span class="op">=</span><span class="dv">1</span>, mean<span class="op">=</span><span class="st">"Zero"</span>, rescale<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>garch_fit_full <span class="op">=</span> garch_spec_full.fit(disp<span class="op">=</span><span class="st">"off"</span>, last_obs<span class="op">=</span>garch_train_len)</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>garch_fcast <span class="op">=</span> garch_fit_full.forecast(start<span class="op">=</span>garch_train_len, reindex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>garch_pred_os <span class="op">=</span> garch_fcast.variance.values.flatten() <span class="op">/</span> (<span class="fl">100.0</span> <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"GARCH IS predictions: </span><span class="sc">{</span><span class="bu">len</span>(garch_pred_is)<span class="sc">}</span><span class="ss">, OS predictions: </span><span class="sc">{</span><span class="bu">len</span>(garch_pred_os)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Train rows: 3800 (2000-10-18 → 2015-11-25)
Test rows:  2035 (2015-11-27 → 2023-12-28)

GARCH(1,1) parameters: ω=0.018841, α=0.0952, β=0.8899
GARCH IS predictions: 3800, OS predictions: 2035</code></pre>
</div>
</div>
<div id="fit-stes-xgb-losses" class="cell" data-execution_count="92">
<details class="code-fold">
<summary>Load archived RMSE baselines; refit ES, STES, XGBSTES under QLIKE (light L2 via CV)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> importlib</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> volatility_forecast.model.stes_model <span class="im">as</span> stes_module</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> volatility_forecast.model.tree_stes_model <span class="im">as</span> tree_stes_module</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(stes_module)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(tree_stes_module)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>STESModel <span class="op">=</span> stes_module.STESModel</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>XGBoostSTESModel <span class="op">=</span> tree_stes_module.XGBoostSTESModel</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> scale_data_sample(X_train, X_test):</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    cols_to_scale <span class="op">=</span> [c <span class="cf">for</span> c <span class="kw">in</span> X_train.columns <span class="cf">if</span> c <span class="op">!=</span> <span class="st">"const"</span>]</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> cols_to_scale:</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> X_train.copy(), X_test.copy()</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    X_tr_s <span class="op">=</span> X_train.copy()</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    X_te_s <span class="op">=</span> X_test.copy()</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    X_tr_s[cols_to_scale] <span class="op">=</span> scaler.fit_transform(X_train[cols_to_scale])</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    X_te_s[cols_to_scale] <span class="op">=</span> scaler.transform(X_test[cols_to_scale])</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> X_tr_s, X_te_s</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _align_archive_series(series, target_index):</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    aligned <span class="op">=</span> series.reindex(target_index)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> aligned.isna().<span class="bu">any</span>():</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>        src <span class="op">=</span> series.copy()</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>        src.index <span class="op">=</span> pd.DatetimeIndex(src.index).tz_convert(<span class="st">"UTC"</span>).normalize()</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>        tgt <span class="op">=</span> pd.DatetimeIndex(target_index).tz_convert(<span class="st">"UTC"</span>).normalize()</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>        aligned <span class="op">=</span> src.reindex(tgt)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>        aligned.index <span class="op">=</span> target_index</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> aligned.isna().<span class="bu">any</span>():</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>        missing <span class="op">=</span> <span class="bu">int</span>(aligned.isna().<span class="bu">sum</span>())</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">RuntimeError</span>(<span class="ss">f"Archive alignment failed: </span><span class="sc">{</span>missing<span class="sc">}</span><span class="ss"> missing values remain."</span>)</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> aligned.astype(<span class="bu">float</span>)</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>SCALE_FACTOR <span class="op">=</span> <span class="fl">100.0</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>XGB_PARAMS_SAMPLE <span class="op">=</span> {</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">"booster"</span>: <span class="st">"gblinear"</span>,</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">"updater"</span>: <span class="st">"coord_descent"</span>,</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    <span class="st">"max_depth"</span>: <span class="dv">5</span>,</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>    <span class="st">"learning_rate"</span>: <span class="fl">0.01</span>,</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    <span class="st">"subsample"</span>: <span class="fl">1.0</span>,</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>    <span class="st">"colsample_bytree"</span>: <span class="fl">1.0</span>,</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>    <span class="st">"min_child_weight"</span>: <span class="fl">1.0</span>,</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>    <span class="st">"reg_lambda"</span>: <span class="fl">1.0</span>,</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>    <span class="st">"reg_alpha"</span>: <span class="fl">0.0</span>,</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>    <span class="st">"verbosity"</span>: <span class="dv">0</span>,</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>XGB_ROUNDS_SAMPLE <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>GRID_E2E <span class="op">=</span> [</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"min_child_weight"</span>: <span class="fl">5.0</span>, <span class="st">"learning_rate"</span>: <span class="fl">0.05</span>, <span class="st">"max_depth"</span>: <span class="dv">3</span>},</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"min_child_weight"</span>: <span class="fl">20.0</span>, <span class="st">"learning_rate"</span>: <span class="fl">0.1</span>, <span class="st">"max_depth"</span>: <span class="dv">3</span>},</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"min_child_weight"</span>: <span class="fl">50.0</span>, <span class="st">"learning_rate"</span>: <span class="fl">0.05</span>, <span class="st">"max_depth"</span>: <span class="dv">2</span>},</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>STES_L2_GRID <span class="op">=</span> [</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"l2_reg"</span>: <span class="fl">0.0</span>},</span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"l2_reg"</span>: <span class="fl">0.001</span>},</span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"l2_reg"</span>: <span class="fl">0.01</span>},</span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"l2_reg"</span>: <span class="fl">0.1</span>},</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"l2_reg"</span>: <span class="fl">1.0</span>},</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>X_tr_s, X_te_s <span class="op">=</span> scale_data_sample(X_tr, X_te)</span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a>X_all_s <span class="op">=</span> pd.concat([X_tr_s, X_te_s])</span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a>r_all <span class="op">=</span> pd.concat([r_tr, r_te])</span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a>archive_dir <span class="op">=</span> VF_PATH <span class="op">/</span> <span class="st">"outputs"</span> <span class="op">/</span> <span class="st">"volatility_forecast_2_monte_carlo"</span></span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a>archive_pred_path <span class="op">=</span> archive_dir <span class="op">/</span> <span class="st">"SPY_Analysis_predictions_all_runs.csv"</span></span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> archive_pred_path.exists():</span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">FileNotFoundError</span>(</span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"Archived Part 3 predictions not found at </span><span class="sc">{</span>archive_pred_path<span class="sc">}</span><span class="ss">. "</span></span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Re-run volatility_forecast_2.py to regenerate them."</span></span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a>archive_preds <span class="op">=</span> pd.read_csv(archive_pred_path, parse_dates<span class="op">=</span>[<span class="st">"ts_utc"</span>]).set_index(<span class="st">"ts_utc"</span>)</span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a>archive_preds.index <span class="op">=</span> pd.DatetimeIndex(archive_preds.index).tz_convert(<span class="st">"UTC"</span>)</span>
<span id="cb5-81"><a href="#cb5-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-82"><a href="#cb5-82" aria-hidden="true" tabindex="-1"></a>es_pred_all <span class="op">=</span> _align_archive_series(archive_preds[<span class="st">"ES_run_42"</span>], X_all_s.index)</span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a>stes_pred_all <span class="op">=</span> _align_archive_series(archive_preds[<span class="st">"STES_run_42"</span>], X_all_s.index)</span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a>xgb_pred_all <span class="op">=</span> _align_archive_series(archive_preds[<span class="st">"XGBSTES_E2E_run_42"</span>], X_all_s.index)</span>
<span id="cb5-85"><a href="#cb5-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-86"><a href="#cb5-86" aria-hidden="true" tabindex="-1"></a>es_pred_is <span class="op">=</span> es_pred_all.iloc[: <span class="bu">len</span>(X_tr_s)].values</span>
<span id="cb5-87"><a href="#cb5-87" aria-hidden="true" tabindex="-1"></a>es_pred_os <span class="op">=</span> es_pred_all.iloc[<span class="bu">len</span>(X_tr_s):].values</span>
<span id="cb5-88"><a href="#cb5-88" aria-hidden="true" tabindex="-1"></a>stes_pred_is <span class="op">=</span> stes_pred_all.iloc[: <span class="bu">len</span>(X_tr_s)].values</span>
<span id="cb5-89"><a href="#cb5-89" aria-hidden="true" tabindex="-1"></a>stes_pred_os <span class="op">=</span> stes_pred_all.iloc[<span class="bu">len</span>(X_tr_s):].values</span>
<span id="cb5-90"><a href="#cb5-90" aria-hidden="true" tabindex="-1"></a>xgb_pred_is <span class="op">=</span> xgb_pred_all.iloc[: <span class="bu">len</span>(X_tr_s)].values</span>
<span id="cb5-91"><a href="#cb5-91" aria-hidden="true" tabindex="-1"></a>xgb_pred_os <span class="op">=</span> xgb_pred_all.iloc[<span class="bu">len</span>(X_tr_s):].values</span>
<span id="cb5-92"><a href="#cb5-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-93"><a href="#cb5-93" aria-hidden="true" tabindex="-1"></a>r_tr_scaled <span class="op">=</span> r_tr <span class="op">*</span> SCALE_FACTOR</span>
<span id="cb5-94"><a href="#cb5-94" aria-hidden="true" tabindex="-1"></a>y_tr_scaled <span class="op">=</span> y_tr <span class="op">*</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb5-95"><a href="#cb5-95" aria-hidden="true" tabindex="-1"></a>r_all_scaled <span class="op">=</span> r_all <span class="op">*</span> SCALE_FACTOR</span>
<span id="cb5-96"><a href="#cb5-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-97"><a href="#cb5-97" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Loaded ES/STES/XGBSTES RMSE baselines from archived Part 3 outputs."</span>)</span>
<span id="cb5-98"><a href="#cb5-98" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Archive file: </span><span class="sc">{</span>archive_pred_path<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-99"><a href="#cb5-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-100"><a href="#cb5-100" aria-hidden="true" tabindex="-1"></a><span class="co"># ── ES (QLIKE) ──────────────────────────────────────────────────────────</span></span>
<span id="cb5-101"><a href="#cb5-101" aria-hidden="true" tabindex="-1"></a><span class="co"># ESModel is STESModel with const-only features. Use STESModel directly.</span></span>
<span id="cb5-102"><a href="#cb5-102" aria-hidden="true" tabindex="-1"></a>es_qlike <span class="op">=</span> STESModel(loss<span class="op">=</span><span class="st">"qlike"</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb5-103"><a href="#cb5-103" aria-hidden="true" tabindex="-1"></a>es_qlike.fit(X_tr_s[[<span class="st">"const"</span>]], y_tr, returns<span class="op">=</span>r_tr)</span>
<span id="cb5-104"><a href="#cb5-104" aria-hidden="true" tabindex="-1"></a>es_qlike_pred_all, _ <span class="op">=</span> es_qlike.predict_with_alpha(X_all_s[[<span class="st">"const"</span>]], returns<span class="op">=</span>r_all)</span>
<span id="cb5-105"><a href="#cb5-105" aria-hidden="true" tabindex="-1"></a>es_qlike_pred_all <span class="op">=</span> pd.Series(es_qlike_pred_all, index<span class="op">=</span>X_all_s.index)</span>
<span id="cb5-106"><a href="#cb5-106" aria-hidden="true" tabindex="-1"></a>es_qlike_pred_is <span class="op">=</span> es_qlike_pred_all.iloc[: <span class="bu">len</span>(X_tr_s)].values</span>
<span id="cb5-107"><a href="#cb5-107" aria-hidden="true" tabindex="-1"></a>es_qlike_pred_os <span class="op">=</span> es_qlike_pred_all.iloc[<span class="bu">len</span>(X_tr_s):].values</span>
<span id="cb5-108"><a href="#cb5-108" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"ES QLIKE alpha: </span><span class="sc">{</span><span class="bu">float</span>(<span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>es_qlike.params)))<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb5-109"><a href="#cb5-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-110"><a href="#cb5-110" aria-hidden="true" tabindex="-1"></a><span class="co"># ── STES (QLIKE) ────────────────────────────────────────────────────────</span></span>
<span id="cb5-111"><a href="#cb5-111" aria-hidden="true" tabindex="-1"></a>stes_qlike <span class="op">=</span> STESModel(loss<span class="op">=</span><span class="st">"qlike"</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb5-112"><a href="#cb5-112" aria-hidden="true" tabindex="-1"></a>stes_qlike.fit(</span>
<span id="cb5-113"><a href="#cb5-113" aria-hidden="true" tabindex="-1"></a>    X_tr_s,</span>
<span id="cb5-114"><a href="#cb5-114" aria-hidden="true" tabindex="-1"></a>    y_tr,</span>
<span id="cb5-115"><a href="#cb5-115" aria-hidden="true" tabindex="-1"></a>    returns<span class="op">=</span>r_tr,</span>
<span id="cb5-116"><a href="#cb5-116" aria-hidden="true" tabindex="-1"></a>    perform_cv<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb5-117"><a href="#cb5-117" aria-hidden="true" tabindex="-1"></a>    cv_grid<span class="op">=</span>STES_L2_GRID,</span>
<span id="cb5-118"><a href="#cb5-118" aria-hidden="true" tabindex="-1"></a>    cv_splits<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb5-119"><a href="#cb5-119" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-120"><a href="#cb5-120" aria-hidden="true" tabindex="-1"></a>stes_qlike_pred_all, stes_qlike_alpha_all <span class="op">=</span> stes_qlike.predict_with_alpha(X_all_s, returns<span class="op">=</span>r_all)</span>
<span id="cb5-121"><a href="#cb5-121" aria-hidden="true" tabindex="-1"></a>stes_qlike_pred_all <span class="op">=</span> pd.Series(stes_qlike_pred_all, index<span class="op">=</span>X_all_s.index)</span>
<span id="cb5-122"><a href="#cb5-122" aria-hidden="true" tabindex="-1"></a>stes_qlike_pred_is <span class="op">=</span> stes_qlike_pred_all.iloc[: <span class="bu">len</span>(X_tr_s)].values</span>
<span id="cb5-123"><a href="#cb5-123" aria-hidden="true" tabindex="-1"></a>stes_qlike_pred_os <span class="op">=</span> stes_qlike_pred_all.iloc[<span class="bu">len</span>(X_tr_s):].values</span>
<span id="cb5-124"><a href="#cb5-124" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"STES QLIKE best l2_reg: </span><span class="sc">{</span>stes_qlike<span class="sc">.</span>l2_reg<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-125"><a href="#cb5-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-126"><a href="#cb5-126" aria-hidden="true" tabindex="-1"></a><span class="co"># ── XGBSTES (QLIKE) ────────────────────────────────────────────────────</span></span>
<span id="cb5-127"><a href="#cb5-127" aria-hidden="true" tabindex="-1"></a>xgbstes_qlike <span class="op">=</span> XGBoostSTESModel(</span>
<span id="cb5-128"><a href="#cb5-128" aria-hidden="true" tabindex="-1"></a>    xgb_params<span class="op">=</span>XGB_PARAMS_SAMPLE,</span>
<span id="cb5-129"><a href="#cb5-129" aria-hidden="true" tabindex="-1"></a>    num_boost_round<span class="op">=</span>XGB_ROUNDS_SAMPLE,</span>
<span id="cb5-130"><a href="#cb5-130" aria-hidden="true" tabindex="-1"></a>    fit_method<span class="op">=</span><span class="st">"end_to_end"</span>,</span>
<span id="cb5-131"><a href="#cb5-131" aria-hidden="true" tabindex="-1"></a>    loss<span class="op">=</span><span class="st">"qlike"</span>,</span>
<span id="cb5-132"><a href="#cb5-132" aria-hidden="true" tabindex="-1"></a>    e2e_grad_hess_scale<span class="op">=</span><span class="fl">1.0</span>,</span>
<span id="cb5-133"><a href="#cb5-133" aria-hidden="true" tabindex="-1"></a>    e2e_debug<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb5-134"><a href="#cb5-134" aria-hidden="true" tabindex="-1"></a>    e2e_debug_print_once<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb5-135"><a href="#cb5-135" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb5-136"><a href="#cb5-136" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-137"><a href="#cb5-137" aria-hidden="true" tabindex="-1"></a>xgbstes_qlike.fit(</span>
<span id="cb5-138"><a href="#cb5-138" aria-hidden="true" tabindex="-1"></a>    X_tr_s,</span>
<span id="cb5-139"><a href="#cb5-139" aria-hidden="true" tabindex="-1"></a>    y_tr_scaled,</span>
<span id="cb5-140"><a href="#cb5-140" aria-hidden="true" tabindex="-1"></a>    returns<span class="op">=</span>r_tr_scaled,</span>
<span id="cb5-141"><a href="#cb5-141" aria-hidden="true" tabindex="-1"></a>    perform_cv<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb5-142"><a href="#cb5-142" aria-hidden="true" tabindex="-1"></a>    cv_grid<span class="op">=</span>GRID_E2E,</span>
<span id="cb5-143"><a href="#cb5-143" aria-hidden="true" tabindex="-1"></a>    cv_splits<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb5-144"><a href="#cb5-144" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-145"><a href="#cb5-145" aria-hidden="true" tabindex="-1"></a>xgb_qlike_pred_scaled_all <span class="op">=</span> xgbstes_qlike.predict(X_all_s, returns<span class="op">=</span>r_all_scaled)</span>
<span id="cb5-146"><a href="#cb5-146" aria-hidden="true" tabindex="-1"></a>xgb_qlike_pred_all <span class="op">=</span> pd.Series(xgb_qlike_pred_scaled_all <span class="op">/</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>), index<span class="op">=</span>X_all_s.index)</span>
<span id="cb5-147"><a href="#cb5-147" aria-hidden="true" tabindex="-1"></a>xgb_qlike_pred_is <span class="op">=</span> xgb_qlike_pred_all.iloc[: <span class="bu">len</span>(X_tr_s)].values</span>
<span id="cb5-148"><a href="#cb5-148" aria-hidden="true" tabindex="-1"></a>xgb_qlike_pred_os <span class="op">=</span> xgb_qlike_pred_all.iloc[<span class="bu">len</span>(X_tr_s):].values</span>
<span id="cb5-149"><a href="#cb5-149" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"XGBSTES QLIKE best params: </span><span class="sc">{</span>xgbstes_qlike<span class="sc">.</span>xgb_params<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-150"><a href="#cb5-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-151"><a href="#cb5-151" aria-hidden="true" tabindex="-1"></a>model_predictions <span class="op">=</span> {</span>
<span id="cb5-152"><a href="#cb5-152" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GARCH(1,1)"</span>: {<span class="st">"train_loss"</span>: <span class="st">"MLE"</span>, <span class="st">"is"</span>: garch_pred_is, <span class="st">"os"</span>: garch_pred_os},</span>
<span id="cb5-153"><a href="#cb5-153" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ES (RMSE)"</span>: {<span class="st">"train_loss"</span>: <span class="st">"RMSE"</span>, <span class="st">"is"</span>: es_pred_is, <span class="st">"os"</span>: es_pred_os},</span>
<span id="cb5-154"><a href="#cb5-154" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ES (QLIKE)"</span>: {<span class="st">"train_loss"</span>: <span class="st">"QLIKE"</span>, <span class="st">"is"</span>: es_qlike_pred_is, <span class="st">"os"</span>: es_qlike_pred_os},</span>
<span id="cb5-155"><a href="#cb5-155" aria-hidden="true" tabindex="-1"></a>    <span class="st">"STES (RMSE)"</span>: {<span class="st">"train_loss"</span>: <span class="st">"RMSE"</span>, <span class="st">"is"</span>: stes_pred_is, <span class="st">"os"</span>: stes_pred_os},</span>
<span id="cb5-156"><a href="#cb5-156" aria-hidden="true" tabindex="-1"></a>    <span class="st">"STES (QLIKE)"</span>: {<span class="st">"train_loss"</span>: <span class="st">"QLIKE"</span>, <span class="st">"is"</span>: stes_qlike_pred_is, <span class="st">"os"</span>: stes_qlike_pred_os},</span>
<span id="cb5-157"><a href="#cb5-157" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGBSTES (RMSE)"</span>: {<span class="st">"train_loss"</span>: <span class="st">"RMSE"</span>, <span class="st">"is"</span>: xgb_pred_is, <span class="st">"os"</span>: xgb_pred_os},</span>
<span id="cb5-158"><a href="#cb5-158" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGBSTES (QLIKE)"</span>: {<span class="st">"train_loss"</span>: <span class="st">"QLIKE"</span>, <span class="st">"is"</span>: xgb_qlike_pred_is, <span class="st">"os"</span>: xgb_qlike_pred_os},</span>
<span id="cb5-159"><a href="#cb5-159" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Loaded ES/STES/XGBSTES RMSE baselines from archived Part 3 outputs.
Archive file: /Users/steveyang/Projects/Github/volatility-forecast/outputs/volatility_forecast_2_monte_carlo/SPY_Analysis_predictions_all_runs.csv
ES QLIKE alpha: 0.0687</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>STES QLIKE best l2_reg: 1.0
XGBSTES QLIKE best params: {'booster': 'gblinear', 'updater': 'coord_descent', 'max_depth': 3, 'learning_rate': 0.1, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 20.0, 'reg_lambda': 1.0, 'reg_alpha': 0.0, 'verbosity': 0}</code></pre>
</div>
</div>
<div class="cell" data-tbl-cap="All seven model variants: GARCH baseline, MSE-trained, and QLIKE-trained" data-execution_count="93">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>actual_is <span class="op">=</span> y_tr.values</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>actual_os <span class="op">=</span> y_te.values</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>comparison_table <span class="op">=</span> pd.DataFrame(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Model"</span>: <span class="bu">list</span>(model_predictions.keys()),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Train Loss"</span>: [model_predictions[name][<span class="st">"train_loss"</span>] <span class="cf">for</span> name <span class="kw">in</span> model_predictions],</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"IS RMSE"</span>: [rmse(actual_is, model_predictions[name][<span class="st">"is"</span>]) <span class="cf">for</span> name <span class="kw">in</span> model_predictions],</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS RMSE"</span>: [rmse(actual_os, model_predictions[name][<span class="st">"os"</span>]) <span class="cf">for</span> name <span class="kw">in</span> model_predictions],</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS MAE"</span>: [mae(actual_os, model_predictions[name][<span class="st">"os"</span>]) <span class="cf">for</span> name <span class="kw">in</span> model_predictions],</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS QLIKE"</span>: [qlike(actual_os, model_predictions[name][<span class="st">"os"</span>]) <span class="cf">for</span> name <span class="kw">in</span> model_predictions],</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>display(style_results_table(comparison_table, precision<span class="op">=</span><span class="dv">6</span>, index_col<span class="op">=</span><span class="st">"Model"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="baseline-loss-table" class="cell-output cell-output-display">
<style type="text/css">
#T_286de table {
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.95rem;
  line-height: 1.4;
}
#T_286de thead th {
  text-align: left;
  font-weight: 600;
  border-bottom: 1px solid #ddd;
  padding: 8px 12px;
}
#T_286de tbody td {
  padding: 8px 12px;
  border-bottom: 1px solid #eee;
}
#T_286de tbody tr:nth-child(even) {
  background-color: #f7f7f756;
}
</style>

<table id="T_286de" class="caption-top">
<caption>All seven model variants: GARCH baseline, MSE-trained, and QLIKE-trained</caption>
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_286de_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Train Loss</th>
<th id="T_286de_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">IS RMSE</th>
<th id="T_286de_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">OS RMSE</th>
<th id="T_286de_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">OS MAE</th>
<th id="T_286de_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">OS QLIKE</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Model</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col3" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col4" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_286de_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">GARCH(1,1)</th>
<td id="T_286de_row0_col0" class="data row0 col0">MLE</td>
<td id="T_286de_row0_col1" class="data row0 col1">0.000504</td>
<td id="T_286de_row0_col2" class="data row0 col2">0.000460</td>
<td id="T_286de_row0_col3" class="data row0 col3">0.000139</td>
<td id="T_286de_row0_col4" class="data row0 col4">1.561044</td>
</tr>
<tr class="even">
<th id="T_286de_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">ES (RMSE)</th>
<td id="T_286de_row1_col0" class="data row1 col0">RMSE</td>
<td id="T_286de_row1_col1" class="data row1 col1">0.000506</td>
<td id="T_286de_row1_col2" class="data row1 col2">0.000464</td>
<td id="T_286de_row1_col3" class="data row1 col3">0.000140</td>
<td id="T_286de_row1_col4" class="data row1 col4">1.619823</td>
</tr>
<tr class="odd">
<th id="T_286de_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">ES (QLIKE)</th>
<td id="T_286de_row2_col0" class="data row2 col0">QLIKE</td>
<td id="T_286de_row2_col1" class="data row2 col1">0.000508</td>
<td id="T_286de_row2_col2" class="data row2 col2">0.000477</td>
<td id="T_286de_row2_col3" class="data row2 col3">0.000144</td>
<td id="T_286de_row2_col4" class="data row2 col4">1.613638</td>
</tr>
<tr class="even">
<th id="T_286de_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">STES (RMSE)</th>
<td id="T_286de_row3_col0" class="data row3 col0">RMSE</td>
<td id="T_286de_row3_col1" class="data row3 col1">0.000501</td>
<td id="T_286de_row3_col2" class="data row3 col2">0.000451</td>
<td id="T_286de_row3_col3" class="data row3 col3">0.000135</td>
<td id="T_286de_row3_col4" class="data row3 col4">1.637744</td>
</tr>
<tr class="odd">
<th id="T_286de_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">STES (QLIKE)</th>
<td id="T_286de_row4_col0" class="data row4 col0">QLIKE</td>
<td id="T_286de_row4_col1" class="data row4 col1">0.000503</td>
<td id="T_286de_row4_col2" class="data row4 col2">0.000478</td>
<td id="T_286de_row4_col3" class="data row4 col3">0.000141</td>
<td id="T_286de_row4_col4" class="data row4 col4">1.599050</td>
</tr>
<tr class="even">
<th id="T_286de_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">XGBSTES (RMSE)</th>
<td id="T_286de_row5_col0" class="data row5 col0">RMSE</td>
<td id="T_286de_row5_col1" class="data row5 col1">0.000502</td>
<td id="T_286de_row5_col2" class="data row5 col2">0.000443</td>
<td id="T_286de_row5_col3" class="data row5 col3">0.000132</td>
<td id="T_286de_row5_col4" class="data row5 col4">1.685679</td>
</tr>
<tr class="odd">
<th id="T_286de_level0_row6" class="row_heading level0 row6" data-quarto-table-cell-role="th">XGBSTES (QLIKE)</th>
<td id="T_286de_row6_col0" class="data row6 col0">QLIKE</td>
<td id="T_286de_row6_col1" class="data row6 col1">0.000510</td>
<td id="T_286de_row6_col2" class="data row6 col2">0.000472</td>
<td id="T_286de_row6_col3" class="data row6 col3">0.000148</td>
<td id="T_286de_row6_col4" class="data row6 col4">1.610119</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="dynamic-loss-head-to-head" class="cell" data-tbl-cap="Head-to-head comparison: MSE-trained vs QLIKE-trained within each model family" data-execution_count="94">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>head_to_head <span class="op">=</span> pd.DataFrame(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Family"</span>: [<span class="st">"ES"</span>, <span class="st">"STES"</span>, <span class="st">"XGBSTES"</span>],</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS RMSE (MSE train)"</span>: [</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>            rmse(actual_os, es_pred_os),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>            rmse(actual_os, stes_pred_os),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>            rmse(actual_os, xgb_pred_os),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS RMSE (QLIKE train)"</span>: [</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>            rmse(actual_os, es_qlike_pred_os),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>            rmse(actual_os, stes_qlike_pred_os),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>            rmse(actual_os, xgb_qlike_pred_os),</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Delta RMSE"</span>: [</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>            rmse(actual_os, es_qlike_pred_os) <span class="op">-</span> rmse(actual_os, es_pred_os),</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>            rmse(actual_os, stes_qlike_pred_os) <span class="op">-</span> rmse(actual_os, stes_pred_os),</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>            rmse(actual_os, xgb_qlike_pred_os) <span class="op">-</span> rmse(actual_os, xgb_pred_os),</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS QLIKE (MSE train)"</span>: [</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>            qlike(actual_os, es_pred_os),</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>            qlike(actual_os, stes_pred_os),</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>            qlike(actual_os, xgb_pred_os),</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>        <span class="st">"OS QLIKE (QLIKE train)"</span>: [</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>            qlike(actual_os, es_qlike_pred_os),</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>            qlike(actual_os, stes_qlike_pred_os),</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>            qlike(actual_os, xgb_qlike_pred_os),</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Delta QLIKE"</span>: [</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>            qlike(actual_os, es_qlike_pred_os) <span class="op">-</span> qlike(actual_os, es_pred_os),</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>            qlike(actual_os, stes_qlike_pred_os) <span class="op">-</span> qlike(actual_os, stes_pred_os),</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>            qlike(actual_os, xgb_qlike_pred_os) <span class="op">-</span> qlike(actual_os, xgb_pred_os),</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>rank_table <span class="op">=</span> comparison_table[[<span class="st">"Model"</span>, <span class="st">"OS RMSE"</span>, <span class="st">"OS QLIKE"</span>]].copy()</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>rank_table[<span class="st">"RMSE Rank"</span>] <span class="op">=</span> rank_table[<span class="st">"OS RMSE"</span>].rank(method<span class="op">=</span><span class="st">"dense"</span>)</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>rank_table[<span class="st">"QLIKE Rank"</span>] <span class="op">=</span> rank_table[<span class="st">"OS QLIKE"</span>].rank(method<span class="op">=</span><span class="st">"dense"</span>)</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>rank_table <span class="op">=</span> rank_table.sort_values([<span class="st">"RMSE Rank"</span>, <span class="st">"QLIKE Rank"</span>, <span class="st">"Model"</span>]).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Head-to-head: MSE-trained vs QLIKE-trained within each family:"</span>)</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>display(style_results_table(head_to_head, precision<span class="op">=</span><span class="dv">6</span>, index_col<span class="op">=</span><span class="st">"Family"</span>))</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Out-of-sample ranking under the two loss functions:"</span>)</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>display(style_results_table(rank_table, precision<span class="op">=</span><span class="dv">6</span>, index_col<span class="op">=</span><span class="st">"Model"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Head-to-head: MSE-trained vs QLIKE-trained within each family:</code></pre>
</div>
<div id="dynamic-loss-head-to-head-1" class="cell-output cell-output-display">
<style type="text/css">
#T_b11e0 table {
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.95rem;
  line-height: 1.4;
}
#T_b11e0 thead th {
  text-align: left;
  font-weight: 600;
  border-bottom: 1px solid #ddd;
  padding: 8px 12px;
}
#T_b11e0 tbody td {
  padding: 8px 12px;
  border-bottom: 1px solid #eee;
}
#T_b11e0 tbody tr:nth-child(even) {
  background-color: #f7f7f756;
}
</style>

<table id="T_b11e0" class="caption-top">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_b11e0_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">OS RMSE (MSE train)</th>
<th id="T_b11e0_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">OS RMSE (QLIKE train)</th>
<th id="T_b11e0_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Delta RMSE</th>
<th id="T_b11e0_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">OS QLIKE (MSE train)</th>
<th id="T_b11e0_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">OS QLIKE (QLIKE train)</th>
<th id="T_b11e0_level0_col5" class="col_heading level0 col5" data-quarto-table-cell-role="th">Delta QLIKE</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Family</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col3" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col4" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col5" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_b11e0_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">ES</th>
<td id="T_b11e0_row0_col0" class="data row0 col0">0.000464</td>
<td id="T_b11e0_row0_col1" class="data row0 col1">0.000477</td>
<td id="T_b11e0_row0_col2" class="data row0 col2">0.000013</td>
<td id="T_b11e0_row0_col3" class="data row0 col3">1.619823</td>
<td id="T_b11e0_row0_col4" class="data row0 col4">1.613638</td>
<td id="T_b11e0_row0_col5" class="data row0 col5">-0.006186</td>
</tr>
<tr class="even">
<th id="T_b11e0_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">STES</th>
<td id="T_b11e0_row1_col0" class="data row1 col0">0.000451</td>
<td id="T_b11e0_row1_col1" class="data row1 col1">0.000478</td>
<td id="T_b11e0_row1_col2" class="data row1 col2">0.000027</td>
<td id="T_b11e0_row1_col3" class="data row1 col3">1.637744</td>
<td id="T_b11e0_row1_col4" class="data row1 col4">1.599050</td>
<td id="T_b11e0_row1_col5" class="data row1 col5">-0.038694</td>
</tr>
<tr class="odd">
<th id="T_b11e0_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">XGBSTES</th>
<td id="T_b11e0_row2_col0" class="data row2 col0">0.000443</td>
<td id="T_b11e0_row2_col1" class="data row2 col1">0.000472</td>
<td id="T_b11e0_row2_col2" class="data row2 col2">0.000029</td>
<td id="T_b11e0_row2_col3" class="data row2 col3">1.685679</td>
<td id="T_b11e0_row2_col4" class="data row2 col4">1.610119</td>
<td id="T_b11e0_row2_col5" class="data row2 col5">-0.075559</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Out-of-sample ranking under the two loss functions:</code></pre>
</div>
<div id="dynamic-loss-head-to-head-2" class="cell-output cell-output-display">
<style type="text/css">
#T_decf4 table {
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.95rem;
  line-height: 1.4;
}
#T_decf4 thead th {
  text-align: left;
  font-weight: 600;
  border-bottom: 1px solid #ddd;
  padding: 8px 12px;
}
#T_decf4 tbody td {
  padding: 8px 12px;
  border-bottom: 1px solid #eee;
}
#T_decf4 tbody tr:nth-child(even) {
  background-color: #f7f7f756;
}
</style>

<table id="T_decf4" class="caption-top">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_decf4_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">OS RMSE</th>
<th id="T_decf4_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">OS QLIKE</th>
<th id="T_decf4_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">RMSE Rank</th>
<th id="T_decf4_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">QLIKE Rank</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Model</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col3" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_decf4_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">XGBSTES (RMSE)</th>
<td id="T_decf4_row0_col0" class="data row0 col0">0.000443</td>
<td id="T_decf4_row0_col1" class="data row0 col1">1.685679</td>
<td id="T_decf4_row0_col2" class="data row0 col2">1.000000</td>
<td id="T_decf4_row0_col3" class="data row0 col3">7.000000</td>
</tr>
<tr class="even">
<th id="T_decf4_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">STES (RMSE)</th>
<td id="T_decf4_row1_col0" class="data row1 col0">0.000451</td>
<td id="T_decf4_row1_col1" class="data row1 col1">1.637744</td>
<td id="T_decf4_row1_col2" class="data row1 col2">2.000000</td>
<td id="T_decf4_row1_col3" class="data row1 col3">6.000000</td>
</tr>
<tr class="odd">
<th id="T_decf4_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">GARCH(1,1)</th>
<td id="T_decf4_row2_col0" class="data row2 col0">0.000460</td>
<td id="T_decf4_row2_col1" class="data row2 col1">1.561044</td>
<td id="T_decf4_row2_col2" class="data row2 col2">3.000000</td>
<td id="T_decf4_row2_col3" class="data row2 col3">1.000000</td>
</tr>
<tr class="even">
<th id="T_decf4_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">ES (RMSE)</th>
<td id="T_decf4_row3_col0" class="data row3 col0">0.000464</td>
<td id="T_decf4_row3_col1" class="data row3 col1">1.619823</td>
<td id="T_decf4_row3_col2" class="data row3 col2">4.000000</td>
<td id="T_decf4_row3_col3" class="data row3 col3">5.000000</td>
</tr>
<tr class="odd">
<th id="T_decf4_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">XGBSTES (QLIKE)</th>
<td id="T_decf4_row4_col0" class="data row4 col0">0.000472</td>
<td id="T_decf4_row4_col1" class="data row4 col1">1.610119</td>
<td id="T_decf4_row4_col2" class="data row4 col2">5.000000</td>
<td id="T_decf4_row4_col3" class="data row4 col3">3.000000</td>
</tr>
<tr class="even">
<th id="T_decf4_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">ES (QLIKE)</th>
<td id="T_decf4_row5_col0" class="data row5 col0">0.000477</td>
<td id="T_decf4_row5_col1" class="data row5 col1">1.613638</td>
<td id="T_decf4_row5_col2" class="data row5 col2">6.000000</td>
<td id="T_decf4_row5_col3" class="data row5 col3">4.000000</td>
</tr>
<tr class="odd">
<th id="T_decf4_level0_row6" class="row_heading level0 row6" data-quarto-table-cell-role="th">STES (QLIKE)</th>
<td id="T_decf4_row6_col0" class="data row6 col0">0.000478</td>
<td id="T_decf4_row6_col1" class="data row6 col1">1.599050</td>
<td id="T_decf4_row6_col2" class="data row6 col2">7.000000</td>
<td id="T_decf4_row6_col3" class="data row6 col3">2.000000</td>
</tr>
</tbody>
</table>
</div>
<p>Head-to-head comparison: MSE-trained vs QLIKE-trained within each model family</p>
</div>
<h2 data-number="5" id="formal-comparison-and-calibration" class="anchored"><span class="header-section-number">5</span> Formal Comparison and Calibration</h2>
<p>Point metrics are informative, but the interesting question is whether the loss swap changes the forecast in a statistically meaningful way or merely nudges the ranking table. We therefore look at two complementary diagnostics. <a href="../forecast-comparison/">Our post on forecast comparison</a> provides some background on these two diagnostics.</p>
<ol type="1">
<li><strong>Diebold-Mariano tests</strong> on squared error and QLIKE loss differentials. For the pairwise comparisons below, a negative statistic favors the first-named model.</li>
<li><strong>Mincer-Zarnowitz regressions</strong> on the variance scale. Here a slope close to one is the practical calibration target.</li>
</ol>
<div id="loss-dm-and-mz" class="cell" data-execution_count="97">
<details class="code-fold">
<summary>DM tests and Mincer-Zarnowitz regressions for MSE-trained vs QLIKE-trained models</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _sq_loss(y, yhat):</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.asarray(y, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    yhat <span class="op">=</span> np.asarray(yhat, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (y <span class="op">-</span> yhat) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _qlike_loss(y, yhat, eps<span class="op">=</span><span class="fl">1e-8</span>):</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.asarray(y, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    yhat <span class="op">=</span> np.clip(np.asarray(yhat, dtype<span class="op">=</span><span class="bu">float</span>), eps, <span class="va">None</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    ratio <span class="op">=</span> np.clip(y, eps, <span class="va">None</span>) <span class="op">/</span> yhat</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ratio <span class="op">-</span> np.log(ratio) <span class="op">-</span> <span class="fl">1.0</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>dm_pairs <span class="op">=</span> [</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"ES QLIKE vs ES RMSE"</span>, es_qlike_pred_os, es_pred_os),</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"STES QLIKE vs STES RMSE"</span>, stes_qlike_pred_os, stes_pred_os),</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGBSTES QLIKE vs XGBSTES RMSE"</span>, xgb_qlike_pred_os, xgb_pred_os),</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGBSTES RMSE vs GARCH"</span>, xgb_pred_os, garch_pred_os),</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGBSTES QLIKE vs GARCH"</span>, xgb_qlike_pred_os, garch_pred_os),</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>dm_rows <span class="op">=</span> []</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, pred_a, pred_b <span class="kw">in</span> dm_pairs:</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>    res_sq <span class="op">=</span> diebold_mariano(_sq_loss(actual_os, pred_a), _sq_loss(actual_os, pred_b), h<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>    res_ql <span class="op">=</span> diebold_mariano(_qlike_loss(actual_os, pred_a), _qlike_loss(actual_os, pred_b), h<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>    dm_rows.append(</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>        {</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Comparison"</span>: label,</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>            <span class="st">"DM (SqErr)"</span>: res_sq[<span class="st">"dm_stat"</span>],</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>            <span class="st">"p (SqErr)"</span>: res_sq[<span class="st">"p_value"</span>],</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>            <span class="st">"DM (QLIKE)"</span>: res_ql[<span class="st">"dm_stat"</span>],</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>            <span class="st">"p (QLIKE)"</span>: res_ql[<span class="st">"p_value"</span>],</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>dm_table <span class="op">=</span> pd.DataFrame(dm_rows)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>display(style_results_table(dm_table, precision<span class="op">=</span><span class="dv">4</span>, index_col<span class="op">=</span><span class="st">"Comparison"</span>))</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>mz_models <span class="op">=</span> [</span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"ES RMSE"</span>, es_pred_os),</span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"ES QLIKE"</span>, es_qlike_pred_os),</span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"STES RMSE"</span>, stes_pred_os),</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"STES QLIKE"</span>, stes_qlike_pred_os),</span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGBSTES RMSE"</span>, xgb_pred_os),</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGBSTES QLIKE"</span>, xgb_qlike_pred_os),</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"GARCH"</span>, garch_pred_os),</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>mz_rows <span class="op">=</span> []</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, pred <span class="kw">in</span> mz_models:</span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>    mz <span class="op">=</span> mincer_zarnowitz(actual_os, pred)</span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>    mz_rows.append(</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>        {</span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Model"</span>: label,</span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a>            <span class="st">"const"</span>: mz[<span class="st">"params"</span>].get(<span class="st">"const"</span>, np.nan),</span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>            <span class="st">"beta"</span>: mz[<span class="st">"params"</span>].get(<span class="st">"beta"</span>, np.nan),</span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a>            <span class="st">"R2"</span>: mz[<span class="st">"r2"</span>],</span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>mz_table <span class="op">=</span> pd.DataFrame(mz_rows)</span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a>display(style_results_table(mz_table, precision<span class="op">=</span><span class="dv">4</span>, index_col<span class="op">=</span><span class="st">"Model"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="loss-dm-and-mz-1" class="cell-output cell-output-display">
<style type="text/css">
#T_4063a table {
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.95rem;
  line-height: 1.4;
}
#T_4063a thead th {
  text-align: left;
  font-weight: 600;
  border-bottom: 1px solid #ddd;
  padding: 8px 12px;
}
#T_4063a tbody td {
  padding: 8px 12px;
  border-bottom: 1px solid #eee;
}
#T_4063a tbody tr:nth-child(even) {
  background-color: #f7f7f756;
}
</style>

<table id="T_4063a" class="caption-top">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_4063a_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">DM (SqErr)</th>
<th id="T_4063a_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">p (SqErr)</th>
<th id="T_4063a_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">DM (QLIKE)</th>
<th id="T_4063a_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">p (QLIKE)</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Comparison</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col3" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_4063a_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">ES QLIKE vs ES RMSE</th>
<td id="T_4063a_row0_col0" class="data row0 col0">0.9997</td>
<td id="T_4063a_row0_col1" class="data row0 col1">0.3176</td>
<td id="T_4063a_row0_col2" class="data row0 col2">-0.4457</td>
<td id="T_4063a_row0_col3" class="data row0 col3">0.6559</td>
</tr>
<tr class="even">
<th id="T_4063a_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">STES QLIKE vs STES RMSE</th>
<td id="T_4063a_row1_col0" class="data row1 col0">0.8752</td>
<td id="T_4063a_row1_col1" class="data row1 col1">0.3816</td>
<td id="T_4063a_row1_col2" class="data row1 col2">-1.3834</td>
<td id="T_4063a_row1_col3" class="data row1 col3">0.1667</td>
</tr>
<tr class="odd">
<th id="T_4063a_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">XGBSTES QLIKE vs XGBSTES RMSE</th>
<td id="T_4063a_row2_col0" class="data row2 col0">1.8453</td>
<td id="T_4063a_row2_col1" class="data row2 col1">0.0651</td>
<td id="T_4063a_row2_col2" class="data row2 col2">-2.5739</td>
<td id="T_4063a_row2_col3" class="data row2 col3">0.0101</td>
</tr>
<tr class="even">
<th id="T_4063a_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">XGBSTES RMSE vs GARCH</th>
<td id="T_4063a_row3_col0" class="data row3 col0">-1.2552</td>
<td id="T_4063a_row3_col1" class="data row3 col1">0.2095</td>
<td id="T_4063a_row3_col2" class="data row3 col2">2.4891</td>
<td id="T_4063a_row3_col3" class="data row3 col3">0.0129</td>
</tr>
<tr class="odd">
<th id="T_4063a_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">XGBSTES QLIKE vs GARCH</th>
<td id="T_4063a_row4_col0" class="data row4 col0">0.6649</td>
<td id="T_4063a_row4_col1" class="data row4 col1">0.5062</td>
<td id="T_4063a_row4_col2" class="data row4 col2">1.8168</td>
<td id="T_4063a_row4_col3" class="data row4 col3">0.0694</td>
</tr>
</tbody>
</table>
</div>
<div id="loss-dm-and-mz-2" class="cell-output cell-output-display">
<style type="text/css">
#T_b6ade table {
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.95rem;
  line-height: 1.4;
}
#T_b6ade thead th {
  text-align: left;
  font-weight: 600;
  border-bottom: 1px solid #ddd;
  padding: 8px 12px;
}
#T_b6ade tbody td {
  padding: 8px 12px;
  border-bottom: 1px solid #eee;
}
#T_b6ade tbody tr:nth-child(even) {
  background-color: #f7f7f756;
}
</style>

<table id="T_b6ade" class="caption-top">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_b6ade_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">const</th>
<th id="T_b6ade_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">beta</th>
<th id="T_b6ade_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">R2</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Model</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_b6ade_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">ES RMSE</th>
<td id="T_b6ade_row0_col0" class="data row0 col0">0.0000</td>
<td id="T_b6ade_row0_col1" class="data row0 col1">0.8843</td>
<td id="T_b6ade_row0_col2" class="data row0 col2">0.2564</td>
</tr>
<tr class="even">
<th id="T_b6ade_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">ES QLIKE</th>
<td id="T_b6ade_row1_col0" class="data row1 col0">0.0000</td>
<td id="T_b6ade_row1_col1" class="data row1 col1">0.8972</td>
<td id="T_b6ade_row1_col2" class="data row1 col2">0.2123</td>
</tr>
<tr class="odd">
<th id="T_b6ade_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">STES RMSE</th>
<td id="T_b6ade_row2_col0" class="data row2 col0">0.0000</td>
<td id="T_b6ade_row2_col1" class="data row2 col1">1.0123</td>
<td id="T_b6ade_row2_col2" class="data row2 col2">0.2930</td>
</tr>
<tr class="even">
<th id="T_b6ade_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">STES QLIKE</th>
<td id="T_b6ade_row3_col0" class="data row3 col0">-0.0001</td>
<td id="T_b6ade_row3_col1" class="data row3 col1">1.5210</td>
<td id="T_b6ade_row3_col2" class="data row3 col2">0.2343</td>
</tr>
<tr class="odd">
<th id="T_b6ade_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">XGBSTES RMSE</th>
<td id="T_b6ade_row4_col0" class="data row4 col0">0.0000</td>
<td id="T_b6ade_row4_col1" class="data row4 col1">1.0701</td>
<td id="T_b6ade_row4_col2" class="data row4 col2">0.3197</td>
</tr>
<tr class="even">
<th id="T_b6ade_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">XGBSTES QLIKE</th>
<td id="T_b6ade_row5_col0" class="data row5 col0">0.0000</td>
<td id="T_b6ade_row5_col1" class="data row5 col1">0.7272</td>
<td id="T_b6ade_row5_col2" class="data row5 col2">0.2635</td>
</tr>
<tr class="odd">
<th id="T_b6ade_level0_row6" class="row_heading level0 row6" data-quarto-table-cell-role="th">GARCH</th>
<td id="T_b6ade_row6_col0" class="data row6 col0">-0.0000</td>
<td id="T_b6ade_row6_col1" class="data row6 col1">1.0190</td>
<td id="T_b6ade_row6_col2" class="data row6 col2">0.2652</td>
</tr>
</tbody>
</table>
</div>
</div>
<h3 data-number="5.1" id="reading-the-tables" class="anchored"><span class="header-section-number">5.1</span> Reading the tables</h3>
<p>The DM tests split the three model families into two groups:</p>
<ol type="1">
<li><p><strong>ES and STES — no significant difference.</strong> For both families, switching to QLIKE training nudges the QLIKE score downward (ES: −0.006; STES: −0.039) and RMSE upward by a tiny amount, but none of these differences reach statistical significance (DM p-values all above 0.16). The exponential-smoothing recursion naturally produces strictly positive variance forecasts, so QLIKE training is well-posed — the gains are simply small.</p></li>
<li><p><strong>XGBSTES — significant QLIKE improvement.</strong> XGBSTES is the only family where QLIKE training yields a statistically significant gain: the QLIKE score drops by 0.076 (DM = −2.57, p = 0.01). The RMSE penalty is marginal (DM = 1.85, p = 0.065). Cross-family, GARCH significantly beats XGBSTES (RMSE) on QLIKE (DM = 2.49, p = 0.013); retraining XGBSTES under QLIKE narrows the gap but does not quite close it (p = 0.069).</p></li>
</ol>
<p>The MZ regressions confirm the ranking chart’s underlying story. STES (RMSE) and GARCH are the best-calibrated models (β ≈ 1.01 and 1.02 respectively) — both sit close to the ideal β = 1 line. XGBSTES (RMSE) has the highest R² (0.32) but overshoots slightly (β = 1.07). QLIKE training tends to push calibration away from one: STES (QLIKE) overshoots to β = 1.52, while XGBSTES (QLIKE) undershoots to β = 0.73. The trade-off is real: optimizing for QLIKE improves QLIKE scores at the cost of MZ calibration and RMSE.</p>
<h2 data-number="6" id="ranking-the-models-under-both-criteria" class="anchored"><span class="header-section-number">6</span> Ranking the Models Under Both Criteria</h2>
<p>The figure below makes the trade-off visible. The left panel orders all seven models by out-of-sample RMSE; the right panel orders the same forecasts by out-of-sample QLIKE. Two things jump out:</p>
<ul>
<li><strong>RMSE-trained models sweep the top of the RMSE panel.</strong> XGBSTES (RMSE) leads, followed by STES (RMSE), GARCH, and ES (RMSE). Every QLIKE-trained variant ranks below its RMSE counterpart on this axis.</li>
<li><strong>GARCH is the only model in the top three on <em>both</em> panels</strong> — 3rd in RMSE, 1st in QLIKE. Its MLE objective, mathematically equivalent to QLIKE, gives it a natural dual advantage.</li>
</ul>
<div id="cell-rmse-qlike-ranking-chart" class="cell" data-execution_count="96">
<details class="code-fold">
<summary>Two-panel ranking chart: OS RMSE and OS QLIKE</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>plot_df <span class="op">=</span> comparison_table.copy()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>plot_df[<span class="st">"Palette"</span>] <span class="op">=</span> plot_df[<span class="st">"Model"</span>].<span class="bu">map</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">"GARCH(1,1)"</span>: <span class="st">"#5F7A8A"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"ES (RMSE)"</span>: <span class="st">"#C9A66B"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"ES (QLIKE)"</span>: <span class="st">"#A68B4B"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"STES (RMSE)"</span>: BLOG_PALETTE[<span class="dv">0</span>],</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"XGBSTES (RMSE)"</span>: BLOG_PALETTE[<span class="dv">1</span>],</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"STES (QLIKE)"</span>: <span class="st">"#D8893B"</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"XGBSTES (QLIKE)"</span>: <span class="st">"#8C5E58"</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">7</span>))</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, metric <span class="kw">in</span> <span class="bu">zip</span>(axes, [<span class="st">"OS RMSE"</span>, <span class="st">"OS QLIKE"</span>]):</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    chart_df <span class="op">=</span> plot_df.sort_values(metric, ascending<span class="op">=</span><span class="va">True</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    bars <span class="op">=</span> ax.barh(</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>        chart_df[<span class="st">"Model"</span>],</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>        chart_df[metric],</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>chart_df[<span class="st">"Palette"</span>],</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>        edgecolor<span class="op">=</span><span class="st">"white"</span>,</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>        linewidth<span class="op">=</span><span class="fl">0.6</span>,</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>    ax.set_title(metric, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(metric)</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>    ax.invert_yaxis()</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> bar, val <span class="kw">in</span> <span class="bu">zip</span>(bars, chart_df[metric]):</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>        ax.text(val, bar.get_y() <span class="op">+</span> bar.get_height() <span class="op">/</span> <span class="dv">2</span>, <span class="ss">f" </span><span class="sc">{</span>val<span class="sc">:.6f}</span><span class="ss">"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">"How Model Rankings Change When the Criterion Changes"</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img src="index_files/figure-html/rmse-qlike-ranking-chart-output-1.png" id="rmse-qlike-ranking-chart" class="img-fluid"></p>
</figure>
</div>
</div>
</div>
<h2 data-number="7" id="conclusion" class="anchored"><span class="header-section-number">7</span> Conclusion</h2>
<p>Running seven model variants through a symmetric training experiment — each family fitted under both RMSE and QLIKE wherever feasible — produces two clear take-aways:</p>
<ol type="1">
<li><p><strong>The training loss reshuffles rankings, but only within the metric it targets.</strong> Under RMSE, the top three models are all RMSE-trained; under QLIKE, the top three are all QLIKE-aligned (GARCH MLE, STES QLIKE, XGBSTES QLIKE). No single model dominates both lists, confirming that the loss function is a design choice that trades accuracy on one criterion for accuracy on the other.</p></li>
<li><p><strong>GARCH’s MLE is already QLIKE, and it shows.</strong> GARCH(1,1) is the only model that lands in the top three under <em>both</em> criteria (3rd in RMSE, 1st in QLIKE). There is no separate “QLIKE-trained GARCH” because MLE already minimizes QLIKE for a Gaussian likelihood; this structural advantage makes GARCH a strong default when the practitioner’s criterion is uncertain.</p></li>
</ol>
<p>The experiment also reveals what it leaves unanswered. All models here use the same three gate features (constant, return, realized variance) and a single in-sample/out-of-sample split. Whether richer feature sets or more sophisticated time-series cross-validation would change the rankings is the subject of <a href="../volatility-forecasts-5/">Part 5</a>.</p>
<h3 data-number="7.1" id="whats-next" class="anchored"><span class="header-section-number">7.1</span> What’s next</h3>
<p>We will tackle the following things in the next few posts.</p>
<ol type="1">
<li><strong>Feature expansion</strong> — adding trailing realized-variance windows, calendar and event indicators, and CFTC positioning data to the gate inputs.</li>
<li><strong>Regularization</strong> — deriving and implementing adaptive lasso and elastic net for the STES gate under both RMSE (coordinate descent) and QLIKE (proximal L-BFGS), so we can expand the feature set without overfitting.</li>
<li><strong>Train/test split</strong> — comparing model performance using more sophisticated time-series splits to create real-time variance forecasts and DM statistics.</li>
</ol>
<h2 data-number="8" id="appendix-garch11-model-recap-and-mle" class="anchored"><span class="header-section-number">8</span> Appendix: GARCH(1,1) Model Recap and MLE</h2>
<p>We quickly give a self-contained recap of the GARCH(1,1) model and derive its maximum-likelihood estimator step by step. The aim is to show that GARCH MLE is mathematically equivalent to QLIKE, a statement we made above.</p>
<h3 data-number="8.1" id="the-model" class="anchored"><span class="header-section-number">8.1</span> The model</h3>
<p>GARCH(1,1) (<a href="https://doi.org/10.1016/0304-4076(86)90063-1">Bollerslev, 1986</a>) specifies a conditionally Gaussian return process:</p>
<p><span class="math display">
r_t = \sigma_t \, \epsilon_t, \qquad \epsilon_t \overset{\text{iid}}{\sim} N(0,\,1),
</span></p>
<p>where the conditional variance <span class="math inline">\sigma_t^2 \equiv \text{Var}(r_t \mid \mathcal{F}_{t-1})</span> follows the recursion</p>
<p><span class="math display">
\sigma_t^2 = \omega + \alpha \, r_{t-1}^2 + \beta \, \sigma_{t-1}^2.
</span></p>
<p>The three parameters <span class="math inline">(\omega, \alpha, \beta)</span> are constrained to <span class="math inline">\omega &gt; 0</span>, <span class="math inline">\alpha \ge 0</span>, <span class="math inline">\beta \ge 0</span> to keep the variance positive, and <span class="math inline">\alpha + \beta &lt; 1</span> for covariance stationarity. The unconditional variance is <span class="math inline">\bar\sigma^2 = \omega / (1 - \alpha - \beta)</span>.</p>
<p>Intuitively, the recursion says: today’s variance is a weighted combination of a long-run baseline (<span class="math inline">\omega</span>), yesterday’s squared return (<span class="math inline">\alpha r_{t-1}^2</span>, the “shock” component), and yesterday’s conditional variance (<span class="math inline">\beta \sigma_{t-1}^2</span>, the “persistence” component). When <span class="math inline">\beta</span> is large — typically 0.85–0.95 for daily equity returns — variance shocks decay slowly, which captures the well-known volatility clustering in financial returns.</p>
<h3 data-number="8.2" id="maximum-likelihood-estimation" class="anchored"><span class="header-section-number">8.2</span> Maximum likelihood estimation</h3>
<p>GARCH parameters are fit by maximum likelihood. Given a sample of returns <span class="math inline">(r_1, \ldots, r_T)</span> and an initial variance <span class="math inline">\sigma_1^2</span> (usually set to the sample variance), each observation has the conditional density</p>
<p><span class="math display">
p(r_t \mid \mathcal{F}_{t-1}) = \frac{1}{\sqrt{2\pi\,\sigma_t^2}} \exp\!\left(-\frac{r_t^2}{2\,\sigma_t^2}\right).
</span></p>
<p>Taking logs:</p>
<p><span class="math display">
\log p(r_t \mid \mathcal{F}_{t-1}) = -\tfrac{1}{2}\log(2\pi) - \tfrac{1}{2}\log \sigma_t^2 - \frac{r_t^2}{2\,\sigma_t^2}.
</span></p>
<p>The full-sample log-likelihood is the sum over all observations:</p>
<p><span class="math display">
\ell(\omega, \alpha, \beta) = \sum_{t=1}^{T} \log p(r_t \mid \mathcal{F}_{t-1})
= -\frac{T}{2}\log(2\pi) - \frac{1}{2}\sum_{t=1}^{T}\left[\log \sigma_t^2 + \frac{r_t^2}{\sigma_t^2}\right].
</span></p>
<p>Since <span class="math inline">-\frac{T}{2}\log(2\pi)</span> is a constant that does not depend on the parameters, maximizing <span class="math inline">\ell</span> is equivalent to minimizing</p>
<p><span class="math display">
\mathcal{L}_{\text{MLE}} = \sum_{t=1}^{T}\left[\log \sigma_t^2 + \frac{r_t^2}{\sigma_t^2}\right].
</span></p>
<h3 data-number="8.3" id="mle-is-qlike" class="anchored"><span class="header-section-number">8.3</span> MLE is QLIKE</h3>
<p>Now identify the GARCH forecast with the generic variance forecast: <span class="math inline">\hat v_t = \sigma_t^2</span>, and the squared return with the realized-variance proxy: <span class="math inline">y_t = r_t^2</span>. The MLE objective becomes</p>
<p><span class="math display">
\mathcal{L}_{\text{MLE}} = \sum_{t=1}^{T}\left[\log \hat v_t + \frac{y_t}{\hat v_t}\right].
</span></p>
<p>Compare this with the QLIKE loss defined in the Methodology section:</p>
<p><span class="math display">
\mathcal{L}_{\text{QLIKE}} = \sum_{t=1}^{T}\left[\frac{y_t}{\hat v_t} - \log\!\left(\frac{y_t}{\hat v_t}\right) - 1\right]
= \sum_{t=1}^{T}\left[\frac{y_t}{\hat v_t} + \log \hat v_t \underbrace{{} - \log y_t - 1}_{\text{constant in } \hat v}\right].
</span></p>
<p>The two expressions differ only by <span class="math inline">-\log y_t - 1</span>, which is constant with respect to <span class="math inline">(\omega, \alpha, \beta)</span>. Maximizing the Gaussian log-likelihood and minimizing QLIKE produce exactly the same parameter estimates.</p>
<p>This equivalence is by design — QLIKE is the evaluation counterpart of the Gaussian quasi-likelihood. The result holds even when returns are non-Gaussian, because the Gaussian log-likelihood is a proper <em>quasi-likelihood</em> for the conditional variance: its first-order conditions are unbiased under any distribution with the correct conditional mean and variance (<a href="https://doi.org/10.2307/2297877">Bollerslev and Wooldridge, 1992</a>). That robustness is what makes MLE the default fitting procedure for GARCH in practice, and what makes QLIKE the natural evaluation metric for variance forecasts.</p>
<h3 data-number="8.4" id="why-not-fit-garch-under-mse" class="anchored"><span class="header-section-number">8.4</span> Why not fit GARCH under MSE?</h3>
<p>One could in principle fit GARCH under MSE instead — minimizing <span class="math inline">\sum_t (r_t^2 - \sigma_t^2)^2</span> over the recursion parameters. This is sometimes called LS-GARCH (least-squares GARCH), though it is non-standard for good reason. MSE treats all observations equally in absolute terms, so a few large volatility spikes dominate the loss surface and can distort parameter estimates. MLE under the Gaussian quasi-likelihood is more statistically efficient: it weights each observation proportionally to its variance, which is the natural scale for a variance model. The <code>arch</code> package — and nearly all GARCH implementations in practice — fits by MLE only.</p>


<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/steveya\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>