<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-10">
<meta name="description" content="GARCH(1,1) outperformed flexible gate models under QLIKE because it separates level, persistence, and innovation share. We introduce PGARCH — a predictor-driven GARCH decomposition — and benchmark Linear PGARCH and XGB-g-PGARCH against the seven models from Part 4.">

<title>Volatility Forecasts (Part 5 — PGARCH: Structure-Aware Variance Forecasting) – Steve Yang</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-html-eb71d4f0124c4d5ff63526840ab633f6.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body>

<nav class="site-nav">
  <a href="../../">Home</a>
  <a href="../../pages/series.html">Series</a>
  <a href="../../pages/projects.html">Projects</a>
  <a href="../../pages/categories.html">Categories</a>
  <a href="../../pages/about.html">About</a>

  <span class="site-nav-spacer"></span>
  <a href="../../pages/search.html">Search</a>
</nav>

<header id="title-block-header">
<h1 class="title">Volatility Forecasts (Part 5 — PGARCH: Structure-Aware Variance Forecasting)</h1>

<p class="date">2026-03-10</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>

  <ul>
  <li><a href="#introduction" id="toc-introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#the-pgarch-model" id="toc-the-pgarch-model"><span class="header-section-number">2</span> The PGARCH Model</a>
  <ul>
  <li><a href="#recursion" id="toc-recursion"><span class="header-section-number">2.1</span> Recursion</a></li>
  <li><a href="#implied-garch-representation" id="toc-implied-garch-representation"><span class="header-section-number">2.2</span> Implied GARCH representation</a></li>
  <li><a href="#special-cases" id="toc-special-cases"><span class="header-section-number">2.3</span> Special cases</a></li>
  </ul></li>
  <li><a href="#linear-pgarch-pgarch-l" id="toc-linear-pgarch-pgarch-l"><span class="header-section-number">3</span> Linear PGARCH (PGARCH-L)</a>
  <ul>
  <li><a href="#estimation" id="toc-estimation"><span class="header-section-number">3.1</span> Estimation</a></li>
  </ul></li>
  <li><a href="#xgb-g-pgarch" id="toc-xgb-g-pgarch"><span class="header-section-number">4</span> XGB-g-PGARCH</a>
  <ul>
  <li><a href="#model-structure" id="toc-model-structure"><span class="header-section-number">4.1</span> Model structure</a></li>
  <li><a href="#custom-xgboost-objective" id="toc-custom-xgboost-objective"><span class="header-section-number">4.2</span> Custom XGBoost objective</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis"><span class="header-section-number">5</span> Analysis</a></li>
  <li><a href="#formal-comparison-and-calibration" id="toc-formal-comparison-and-calibration"><span class="header-section-number">6</span> Formal Comparison and Calibration</a></li>
  <li><a href="#structural-parameter-dynamics" id="toc-structural-parameter-dynamics"><span class="header-section-number">7</span> Structural Parameter Dynamics</a></li>
  <li><a href="#summary-of-rankings" id="toc-summary-of-rankings"><span class="header-section-number">8</span> Summary of Rankings</a></li>
  <li><a href="#conclusion" id="toc-conclusion"><span class="header-section-number">9</span> Conclusion</a>
  <ul>
  <li><a href="#whats-next" id="toc-whats-next"><span class="header-section-number">9.1</span> What’s next</a></li>
  </ul></li>
  <li><a href="#appendix-pgarch-derivative-details" id="toc-appendix-pgarch-derivative-details"><span class="header-section-number">10</span> Appendix: PGARCH Derivative Details</a>
  <ul>
  <li><a href="#loss-functions" id="toc-loss-functions"><span class="header-section-number">10.1</span> Loss functions</a></li>
  <li><a href="#jacobian-recursion-linear-pgarch" id="toc-jacobian-recursion-linear-pgarch"><span class="header-section-number">10.2</span> Jacobian recursion (Linear PGARCH)</a></li>
  <li><a href="#hessian-recursion-linear-pgarch" id="toc-hessian-recursion-linear-pgarch"><span class="header-section-number">10.3</span> Hessian recursion (Linear PGARCH)</a></li>
  <li><a href="#gradient-and-hessian-of-the-training-loss" id="toc-gradient-and-hessian-of-the-training-loss"><span class="header-section-number">10.4</span> Gradient and Hessian of the training loss</a></li>
  <li><a href="#xgb-g-pgarch-adjoint-gradient" id="toc-xgb-g-pgarch-adjoint-gradient"><span class="header-section-number">10.5</span> XGB-g-PGARCH adjoint gradient</a></li>
  <li><a href="#xgb-g-pgarch-hessian-approximation" id="toc-xgb-g-pgarch-hessian-approximation"><span class="header-section-number">10.6</span> XGB-g-PGARCH Hessian approximation</a></li>
  </ul></li>
  </ul>
</nav>
<h2 data-number="1" id="introduction" class="anchored"><span class="header-section-number">1</span> Introduction</h2>
<p>In <a href="../volatility-forecasts-4/">Part 4</a> we ran a training experiment: each model family — ES, STES, and XGBSTES — was fitted under both RMSE and QLIKE, then scored on both metrics out of sample. The most striking result was that the <strong>GARCH(1,1)</strong> model consistently ranked first in out-of-sample QLIKE while placing a competitive third in RMSE — despite using no predictor features at all.</p>
<p>At first glance this is puzzling. STES and XGBSTES are more flexible: they allow the smoothing weight to vary with predictors and, in the case of XGBSTES, through a nonlinear boosted mapping. One would expect this flexibility to help, or at least not hurt, once all models are trained on the same objective. Yet GARCH consistently won under QLIKE.</p>
<p>One explanation lies in what GARCH separates and what STES-type models entangle. A standard GARCH(1,1) recursion,</p>
<p><span class="math display">
h_t = \omega + \alpha y_{t-1} + \beta h_{t-1}
</span></p>
<p>can be rewritten by defining <span class="math inline">\phi = \alpha + \beta</span>, <span class="math inline">g = \alpha/(\alpha+\beta)</span>, and <span class="math inline">\mu = \omega/(1-\alpha-\beta)</span> as</p>
<p><span class="math display">
h_t = (1-\phi)\mu + \phi\Big(g y_{t-1} + (1-g) h_{t-1}\Big)
</span></p>
<p>This decomposition contains three distinct structures:</p>
<ul>
<li><span class="math inline">\mu</span>: the <strong>long-run variance anchor</strong> — the level the forecast reverts to,</li>
<li><span class="math inline">\phi</span>: the <strong>total persistence</strong> — how much weight goes to recent information versus the anchor,</li>
<li><span class="math inline">g</span>: the <strong>innovation share</strong> — within the persistent component, how much weight goes to yesterday’s shock versus yesterday’s state.</li>
</ul>
<p>A STES-style recursion <span class="math inline">h_t = g_t y_{t-1} + (1-g_t) h_{t-1}</span> varies only the innovation share. It does not separately estimate a long-run anchor or a total persistence parameter. A single gate must simultaneously decide how much to react to the latest shock, how much memory to retain, and what level the recursion drifts toward. That is too much to ask from one scalar mechanism — especially under QLIKE.</p>
<p>QLIKE penalizes proportionally: driving <span class="math inline">h_t</span> too low is punished much more heavily than overshooting by the same absolute amount. This makes the loss especially sensitive to getting the <strong>variance scale</strong> and <strong>persistence structure</strong> right. GARCH’s intercept <span class="math inline">\omega</span>, equivalently the anchor <span class="math inline">\mu</span>, prevents the forecast from collapsing toward zero — exactly the failure mode that QLIKE punishes most. STES has no such safeguard.</p>
<p>This motivates a new model family: <strong>Predictive GARCH (PGARCH)</strong>. The idea is to keep the GARCH-like structural decomposition that appears essential for QLIKE performance, but let the structural components be predictor-driven and time-varying. Instead of predicting <span class="math inline">(\omega_t, \alpha_t, \beta_t)</span> directly, we parameterize through the interpretable triple <span class="math inline">(\mu_t, \phi_t, g_t)</span> and define</p>
<p><span class="math display">
h_t = (1-\phi_t)\mu_t + \phi_t\Big(g_t y_{t-1} + (1-g_t) h_{t-1}\Big)
</span></p>
<p>We introduce two first members of this family:</p>
<ol type="1">
<li><strong>PGARCH-L</strong> (Linear PGARCH): all three channels are linear functions of predictors, trained end-to-end by L-BFGS-B with analytic recursive gradients.</li>
<li><strong>XGB-g-PGARCH</strong>: <span class="math inline">\mu</span> and <span class="math inline">\phi</span> come from a fitted PGARCH-L initializer; the innovation-share channel <span class="math inline">g</span> is then refined by a gradient-boosted tree with a custom adjoint-based objective.</li>
</ol>
<p>The rest of this post defines the model family, derives the key equations, and benchmarks both variants against the seven models from Part 4 on the same SPY sample and fixed split.</p>
<h2 data-number="2" id="the-pgarch-model" class="anchored"><span class="header-section-number">2</span> The PGARCH Model</h2>
<h3 data-number="2.1" id="recursion" class="anchored"><span class="header-section-number">2.1</span> Recursion</h3>
<p>Let <span class="math inline">y_t \ge 0</span> denote a nonnegative volatility target (we use <span class="math inline">y_t = r_t^2</span>). PGARCH defines the variance forecast by</p>
<p><span class="math display">
h_t = (1-\phi_t)\,\mu_t + \phi_t\,q_t, \qquad q_t = g_t\,y_{t-1} + (1-g_t)\,h_{t-1},
</span></p>
<p>with constraints <span class="math inline">\mu_t &gt; 0</span>, <span class="math inline">\phi_t \in (0,1)</span>, <span class="math inline">g_t \in (0,1)</span>, and a fixed initial state <span class="math inline">h_0 \ge 0</span>.</p>
<p>The quantity <span class="math inline">q_t</span> is a convex combination of yesterday’s shock <span class="math inline">y_{t-1}</span> and yesterday’s state <span class="math inline">h_{t-1}</span>. The full forecast <span class="math inline">h_t</span> is then a convex combination of the long-run anchor <span class="math inline">\mu_t</span> and <span class="math inline">q_t</span>, weighted by persistence <span class="math inline">\phi_t</span>.</p>
<h3 data-number="2.2" id="implied-garch-representation" class="anchored"><span class="header-section-number">2.2</span> Implied GARCH representation</h3>
<p>Defining <span class="math inline">\omega_t = (1-\phi_t)\mu_t</span>, <span class="math inline">\alpha_t = \phi_t g_t</span>, <span class="math inline">\beta_t = \phi_t(1-g_t)</span>, the recursion becomes</p>
<p><span class="math display">
h_t = \omega_t + \alpha_t\,y_{t-1} + \beta_t\,h_{t-1},
</span></p>
<p>a time-varying GARCH(1,1) with <span class="math inline">\alpha_t + \beta_t = \phi_t &lt; 1</span> enforced by construction.</p>
<h3 data-number="2.3" id="special-cases" class="anchored"><span class="header-section-number">2.3</span> Special cases</h3>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Restriction</th>
<th>Model recovered</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\mu_t = \mu</span>, <span class="math inline">\phi_t = \phi</span>, <span class="math inline">g_t = g</span> constant</td>
<td>Constrained GARCH(1,1)</td>
</tr>
<tr class="even">
<td><span class="math inline">\phi_t \equiv 1</span>, anchor dropped</td>
<td>STES exponential smoothing</td>
</tr>
<tr class="odd">
<td><span class="math inline">(\mu_t, \phi_t, g_t)</span> are linear functions of predictors</td>
<td><strong>PGARCH-L</strong> (this post)</td>
</tr>
<tr class="even">
<td><span class="math inline">g_t</span> boosted by XGBoost, <span class="math inline">\mu_t</span> and <span class="math inline">\phi_t</span> from PGARCH-L</td>
<td><strong>XGB-g-PGARCH</strong> (this post)</td>
</tr>
</tbody>
</table>
<p>The nesting structure is the key insight: PGARCH does not abandon GARCH’s recursion. It generalizes the <em>parameter mapping</em> while preserving the structural decomposition that QLIKE rewards.</p>
<h2 data-number="3" id="linear-pgarch-pgarch-l" class="anchored"><span class="header-section-number">3</span> Linear PGARCH (PGARCH-L)</h2>
<p>In PGARCH-L, each structural parameter is a linear function of predictors passed through a link that enforces its constraint. Let <span class="math inline">\tilde{x}_{t-1} = [1, x_{t-1}]</span> denote the augmented feature vector available at time <span class="math inline">t-1</span>. Three linear scores</p>
<p><span class="math display">
a_t = w_\mu^\top \tilde{x}_{t-1}, \qquad b_t = w_\phi^\top \tilde{x}_{t-1}, \qquad c_t = w_g^\top \tilde{x}_{t-1}
</span></p>
<p>are mapped to the structural parameters via</p>
<p><span class="math display">
\mu_t = \mu_{\min} + \operatorname{softplus}(a_t), \qquad
\phi_t = \phi_{\min} + (\phi_{\max} - \phi_{\min})\, \sigma(b_t), \qquad
g_t = g_{\min} + (g_{\max} - g_{\min})\, \sigma(c_t)
</span></p>
<p>The softplus link guarantees <span class="math inline">\mu_t &gt; \mu_{\min} &gt; 0</span>; the sigmoid links map <span class="math inline">\phi_t</span> and <span class="math inline">g_t</span> into <span class="math inline">(0,1)</span>.</p>
<h3 data-number="3.1" id="estimation" class="anchored"><span class="header-section-number">3.1</span> Estimation</h3>
<p>The full parameter vector <span class="math inline">\theta = [w_\mu, w_\phi, w_g]</span> is trained end-to-end by minimizing MSE or QLIKE over the recursive variance path. The gradient is computed analytically via a forward recursion that propagates Jacobians <span class="math inline">J_t = \partial h_t / \partial \theta</span> through the PGARCH state equations. We also derive the corresponding Hessian recursion <span class="math inline">H_t = \partial^2 h_t / \partial \theta \partial \theta^\top</span> for verification and analysis, but the implemented optimizer uses L-BFGS-B with analytic gradients rather than a supplied exact Hessian.</p>
<p>Because the recursion is sequential, <span class="math inline">h_0</span> is treated as a fixed causal warm start (set to <span class="math inline">\max(y_0, h_{\min})</span>), and the loss is computed only over <span class="math inline">t = 1, \ldots, T-1</span>. Full derivative formulas appear in the <a href="#appendix-pgarch-derivative-details">Appendix</a>.</p>
<h2 data-number="4" id="xgb-g-pgarch" class="anchored"><span class="header-section-number">4</span> XGB-g-PGARCH</h2>
<p>A full nonlinear PGARCH could let all three channels be learned by flexible models. The first extension is to boost only the <strong>innovation-share channel</strong> <span class="math inline">g_t</span>, while keeping <span class="math inline">\mu_t</span> and <span class="math inline">\phi_t</span> fixed from a PGARCH-L initializer. This targets exactly the mechanism analogous to the STES gate within the GARCH structure.</p>
<h3 data-number="4.1" id="model-structure" class="anchored"><span class="header-section-number">4.1</span> Model structure</h3>
<p>Given baseline sequences <span class="math inline">\mu_t</span> and <span class="math inline">\phi_t</span> from a fitted PGARCH-L, define</p>
<p><span class="math display">
c_t = c_t^{(0)} + F_g(x_t), \qquad g_t = g_{\min} + (g_{\max} - g_{\min})\,\sigma(c_t)
</span></p>
<p>where <span class="math inline">c_t^{(0)}</span> is the baseline raw score and <span class="math inline">F_g</span> is a gradient-boosted tree ensemble. The recursion remains <span class="math inline">h_{t+1} = (1-\phi_t)\mu_t + \phi_t(g_t y_t + (1-g_t)h_t)</span>.</p>
<h3 data-number="4.2" id="custom-xgboost-objective" class="anchored"><span class="header-section-number">4.2</span> Custom XGBoost objective</h3>
<p>Under this indexing, row <span class="math inline">t</span> produces a raw score that affects the next-step forecast <span class="math inline">h_{t+1}</span>. The exact row-wise gradient is computed via a backward adjoint recursion like we did in <a href="../volatility-forecasts-3/">Part 3</a>: define <span class="math inline">\lambda_t = \partial L / \partial h_t</span> (total derivative including all downstream effects), then</p>
<p><span class="math display">
\lambda_{T-1} = u_{T-1}, \qquad \lambda_t = u_t + \rho_t \lambda_{t+1}
</span></p>
<p>where <span class="math inline">u_t = \partial \ell_t / \partial h_t</span> is the per-step loss derivative and <span class="math inline">\rho_t = \phi_t(1-g_t)</span> is the state propagation coefficient. The row-wise gradient is then</p>
<p><span class="math display">
G_s = \lambda_{s+1} \cdot \phi_s(y_s - h_s) \cdot C_s
</span></p>
<p>where <span class="math inline">C_s = (g_{\max} - g_{\min})\sigma(c_s)(1-\sigma(c_s))</span> is the link derivative.</p>
<p>For the per-row Hessian diagonal, we use a positive curvature surrogate rather than the exact (possibly indefinite) second derivative. Under MSE this is a Gauss-Newton approximation; under QLIKE we use Fisher-style scaling <span class="math inline">w_t = 1/(Nh_t^2)</span>, which is the expected information and avoids amplification from extreme observations. The terminal row (<span class="math inline">s = T-1</span>) receives zero gradient and Hessian since it has no in-sample next-step forecast.</p>
<div id="p5asoxfndr" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-03-17T21:37:21.730580Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-03-17T21:37:21.730472Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-03-17T21:37:35.338983Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-03-17T21:37:35.338699Z&quot;}}" data-execution_count="3">
<details class="code-fold">
<summary>Fit Part 4 baselines locally: GARCH(1,1) + ES/STES/XGBSTES under RMSE and QLIKE</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ── GARCH(1,1) ──────────────────────────────────────────────────────────</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>r_tr_pct <span class="op">=</span> r_tr <span class="op">*</span> SCALE_FACTOR</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>r_all_concat <span class="op">=</span> pd.concat([r_tr, r_te])</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>r_all_pct <span class="op">=</span> r_all_concat <span class="op">*</span> SCALE_FACTOR</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>garch_spec <span class="op">=</span> arch_model(r_tr_pct, vol<span class="op">=</span><span class="st">"GARCH"</span>, p<span class="op">=</span><span class="dv">1</span>, q<span class="op">=</span><span class="dv">1</span>, mean<span class="op">=</span><span class="st">"Zero"</span>, rescale<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>garch_fit <span class="op">=</span> garch_spec.fit(disp<span class="op">=</span><span class="st">"off"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>omega_g, alpha_g, beta_g <span class="op">=</span> garch_fit.params[<span class="st">"omega"</span>], garch_fit.params[<span class="st">"alpha[1]"</span>], garch_fit.params[<span class="st">"beta[1]"</span>]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>cv_sq_is <span class="op">=</span> garch_fit.conditional_volatility.values <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>r_sq_is <span class="op">=</span> r_tr_pct.values <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>garch_pred_is <span class="op">=</span> (omega_g <span class="op">+</span> alpha_g <span class="op">*</span> r_sq_is <span class="op">+</span> beta_g <span class="op">*</span> cv_sq_is) <span class="op">/</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>garch_spec_full <span class="op">=</span> arch_model(r_all_pct, vol<span class="op">=</span><span class="st">"GARCH"</span>, p<span class="op">=</span><span class="dv">1</span>, q<span class="op">=</span><span class="dv">1</span>, mean<span class="op">=</span><span class="st">"Zero"</span>, rescale<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>garch_fit_full <span class="op">=</span> garch_spec_full.fit(disp<span class="op">=</span><span class="st">"off"</span>, last_obs<span class="op">=</span><span class="bu">len</span>(r_tr))</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>garch_fcast <span class="op">=</span> garch_fit_full.forecast(start<span class="op">=</span><span class="bu">len</span>(r_tr), reindex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>garch_pred_os <span class="op">=</span> garch_fcast.variance.values.flatten() <span class="op">/</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"GARCH(1,1):  omega=</span><span class="sc">{</span>omega_g<span class="sc">:.6f}</span><span class="ss">, alpha=</span><span class="sc">{</span>alpha_g<span class="sc">:.4f}</span><span class="ss">, beta=</span><span class="sc">{</span>beta_g<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Shared scaling and grids for STES / XGBSTES ─────────────────────────</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>r_tr_scaled <span class="op">=</span> r_tr <span class="op">*</span> SCALE_FACTOR</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>y_tr_scaled <span class="op">=</span> y_tr <span class="op">*</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>r_all_scaled <span class="op">=</span> r_all <span class="op">*</span> SCALE_FACTOR</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>XGB_PARAMS <span class="op">=</span> {</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"booster"</span>: <span class="st">"gblinear"</span>, <span class="st">"updater"</span>: <span class="st">"coord_descent"</span>, <span class="st">"max_depth"</span>: <span class="dv">5</span>,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">"learning_rate"</span>: <span class="fl">0.01</span>, <span class="st">"subsample"</span>: <span class="fl">1.0</span>, <span class="st">"colsample_bytree"</span>: <span class="fl">1.0</span>,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">"min_child_weight"</span>: <span class="fl">1.0</span>, <span class="st">"reg_lambda"</span>: <span class="fl">1.0</span>, <span class="st">"reg_alpha"</span>: <span class="fl">0.0</span>, <span class="st">"verbosity"</span>: <span class="dv">0</span>,</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>STES_L2_GRID <span class="op">=</span> [{<span class="st">"l2_reg"</span>: v} <span class="cf">for</span> v <span class="kw">in</span> [<span class="fl">0.0</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.1</span>, <span class="fl">1.0</span>]]</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>GRID_E2E <span class="op">=</span> [</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"min_child_weight"</span>: <span class="fl">5.0</span>, <span class="st">"learning_rate"</span>: <span class="fl">0.05</span>, <span class="st">"max_depth"</span>: <span class="dv">3</span>},</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"min_child_weight"</span>: <span class="fl">20.0</span>, <span class="st">"learning_rate"</span>: <span class="fl">0.1</span>, <span class="st">"max_depth"</span>: <span class="dv">3</span>},</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"min_child_weight"</span>: <span class="fl">50.0</span>, <span class="st">"learning_rate"</span>: <span class="fl">0.05</span>, <span class="st">"max_depth"</span>: <span class="dv">2</span>},</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co"># ── ES (RMSE / QLIKE) ───────────────────────────────────────────────────</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>es_rmse_m <span class="op">=</span> STESModel(loss<span class="op">=</span><span class="st">"mse"</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>es_rmse_m.fit(X_tr_s[[<span class="st">"const"</span>]], y_tr, returns<span class="op">=</span>r_tr)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>_tmp, _ <span class="op">=</span> es_rmse_m.predict_with_alpha(X_all_s[[<span class="st">"const"</span>]], returns<span class="op">=</span>r_all)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>es_pred_is, es_pred_os <span class="op">=</span> _tmp[:<span class="bu">len</span>(X_tr_s)], _tmp[<span class="bu">len</span>(X_tr_s):]</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>es_qlike_m <span class="op">=</span> STESModel(loss<span class="op">=</span><span class="st">"qlike"</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>es_qlike_m.fit(X_tr_s[[<span class="st">"const"</span>]], y_tr, returns<span class="op">=</span>r_tr)</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>_tmp, _ <span class="op">=</span> es_qlike_m.predict_with_alpha(X_all_s[[<span class="st">"const"</span>]], returns<span class="op">=</span>r_all)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>es_qlike_pred_is, es_qlike_pred_os <span class="op">=</span> _tmp[:<span class="bu">len</span>(X_tr_s)], _tmp[<span class="bu">len</span>(X_tr_s):]</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="co"># ── STES (RMSE / QLIKE) ─────────────────────────────────────────────────</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>stes_rmse_m <span class="op">=</span> STESModel(loss<span class="op">=</span><span class="st">"mse"</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>stes_rmse_m.fit(X_tr_s, y_tr, returns<span class="op">=</span>r_tr, perform_cv<span class="op">=</span><span class="va">True</span>, cv_grid<span class="op">=</span>STES_L2_GRID, cv_splits<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>_tmp, _ <span class="op">=</span> stes_rmse_m.predict_with_alpha(X_all_s, returns<span class="op">=</span>r_all)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>stes_pred_is, stes_pred_os <span class="op">=</span> _tmp[:<span class="bu">len</span>(X_tr_s)], _tmp[<span class="bu">len</span>(X_tr_s):]</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>stes_qlike_m <span class="op">=</span> STESModel(loss<span class="op">=</span><span class="st">"qlike"</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>stes_qlike_m.fit(X_tr_s, y_tr, returns<span class="op">=</span>r_tr, perform_cv<span class="op">=</span><span class="va">True</span>, cv_grid<span class="op">=</span>STES_L2_GRID, cv_splits<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>_tmp, _ <span class="op">=</span> stes_qlike_m.predict_with_alpha(X_all_s, returns<span class="op">=</span>r_all)</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>stes_qlike_pred_is, stes_qlike_pred_os <span class="op">=</span> _tmp[:<span class="bu">len</span>(X_tr_s)], _tmp[<span class="bu">len</span>(X_tr_s):]</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="co"># ── XGBSTES (RMSE / QLIKE) ──────────────────────────────────────────────</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>xgb_rmse_m <span class="op">=</span> XGBoostSTESModel(</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>    xgb_params<span class="op">=</span>XGB_PARAMS,</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>    num_boost_round<span class="op">=</span><span class="dv">200</span>,</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>    fit_method<span class="op">=</span><span class="st">"end_to_end"</span>,</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>    loss<span class="op">=</span><span class="st">"mse"</span>,</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>    e2e_grad_hess_scale<span class="op">=</span><span class="fl">1.0</span>,</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>xgb_rmse_m.fit(X_tr_s, y_tr_scaled, returns<span class="op">=</span>r_tr_scaled, perform_cv<span class="op">=</span><span class="va">True</span>, cv_grid<span class="op">=</span>GRID_E2E, cv_splits<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>_tmp <span class="op">=</span> xgb_rmse_m.predict(X_all_s, returns<span class="op">=</span>r_all_scaled) <span class="op">/</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>xgbstes_pred_is, xgbstes_pred_os <span class="op">=</span> _tmp[:<span class="bu">len</span>(X_tr_s)], _tmp[<span class="bu">len</span>(X_tr_s):]</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>xgb_qlike_m <span class="op">=</span> XGBoostSTESModel(</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>    xgb_params<span class="op">=</span>XGB_PARAMS, num_boost_round<span class="op">=</span><span class="dv">200</span>, fit_method<span class="op">=</span><span class="st">"end_to_end"</span>,</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>    loss<span class="op">=</span><span class="st">"qlike"</span>, e2e_grad_hess_scale<span class="op">=</span><span class="fl">1.0</span>, random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>xgb_qlike_m.fit(X_tr_s, y_tr_scaled, returns<span class="op">=</span>r_tr_scaled, perform_cv<span class="op">=</span><span class="va">True</span>, cv_grid<span class="op">=</span>GRID_E2E, cv_splits<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>_tmp <span class="op">=</span> xgb_qlike_m.predict(X_all_s, returns<span class="op">=</span>r_all_scaled) <span class="op">/</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>xgb_qlike_pred_is, xgb_qlike_pred_os <span class="op">=</span> _tmp[:<span class="bu">len</span>(X_tr_s)], _tmp[<span class="bu">len</span>(X_tr_s):]</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Part 4 baselines ready (7 models)."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>GARCH(1,1):  omega=0.018841, alpha=0.0952, beta=0.8899
Part 4 baselines ready (7 models).</code></pre>
</div>
</div>
<div id="tj51g17cdi9" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-03-17T21:37:35.340582Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-03-17T21:37:35.340476Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-03-17T21:38:24.392707Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-03-17T21:38:24.392449Z&quot;}}" data-execution_count="4">
<details class="code-fold">
<summary>Fit PGARCH-L and XGB-g-PGARCH under RMSE and QLIKE</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ── PGARCH-L (RMSE) ────────────────────────────────────────────────────</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pgarch_l_rmse <span class="op">=</span> PGARCHLinearModel(loss<span class="op">=</span><span class="st">"rmse"</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>pgarch_l_rmse.fit(y_tr.values, X_pgarch_tr.values)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>h_pgarch_l_rmse <span class="op">=</span> pgarch_l_rmse.predict_variance(y_all.values, X_pgarch_all.values)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>pgarch_l_rmse_is <span class="op">=</span> h_pgarch_l_rmse[:<span class="bu">len</span>(y_tr)]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>pgarch_l_rmse_os <span class="op">=</span> h_pgarch_l_rmse[<span class="bu">len</span>(y_tr):]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>implied_rmse <span class="op">=</span> pgarch_l_rmse.implied_garch_params(X_pgarch_tr.values)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"PGARCH-L (RMSE) implied GARCH (mean): "</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"omega=</span><span class="sc">{</span>np<span class="sc">.</span>mean(implied_rmse[<span class="st">'omega'</span>])<span class="sc">:.6f}</span><span class="ss">, "</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"alpha=</span><span class="sc">{</span>np<span class="sc">.</span>mean(implied_rmse[<span class="st">'alpha'</span>])<span class="sc">:.4f}</span><span class="ss">, "</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"beta=</span><span class="sc">{</span>np<span class="sc">.</span>mean(implied_rmse[<span class="st">'beta'</span>])<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># ── PGARCH-L (QLIKE) ───────────────────────────────────────────────────</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>pgarch_l_qlike <span class="op">=</span> PGARCHLinearModel(loss<span class="op">=</span><span class="st">"qlike"</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>pgarch_l_qlike.fit(y_tr.values, X_pgarch_tr.values)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>h_pgarch_l_qlike <span class="op">=</span> pgarch_l_qlike.predict_variance(y_all.values, X_pgarch_all.values)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>pgarch_l_qlike_is <span class="op">=</span> h_pgarch_l_qlike[:<span class="bu">len</span>(y_tr)]</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>pgarch_l_qlike_os <span class="op">=</span> h_pgarch_l_qlike[<span class="bu">len</span>(y_tr):]</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>implied_qlike <span class="op">=</span> pgarch_l_qlike.implied_garch_params(X_pgarch_tr.values)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"PGARCH-L (QLIKE) implied GARCH (mean): "</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"omega=</span><span class="sc">{</span>np<span class="sc">.</span>mean(implied_qlike[<span class="st">'omega'</span>])<span class="sc">:.6f}</span><span class="ss">, "</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"alpha=</span><span class="sc">{</span>np<span class="sc">.</span>mean(implied_qlike[<span class="st">'alpha'</span>])<span class="sc">:.4f}</span><span class="ss">, "</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"beta=</span><span class="sc">{</span>np<span class="sc">.</span>mean(implied_qlike[<span class="st">'beta'</span>])<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="co"># ── XGB-g-PGARCH ───────────────────────────────────────────────────────</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Scale y for XGBoost to avoid the gradient suppression problem from Part 3:</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="co"># with unscaled y ~ 1e-4, the custom-objective row gradients are O(1e-5),</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="co"># completely overwhelmed by reg_lambda=1.0.  Scaling y by SCALE_FACTOR^2</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="co"># brings gradients to O(1) so that XGBoost's regularization operates on</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="co"># the correct scale.</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>y_tr_pgarch_scaled <span class="op">=</span> y_tr.values <span class="op">*</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>y_all_pgarch_scaled <span class="op">=</span> y_all.values <span class="op">*</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a><span class="co"># ── XGB-g-PGARCH (RMSE) ────────────────────────────────────────────────</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>xgb_pgarch_rmse <span class="op">=</span> XGBGPGARCHModel(</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>    loss<span class="op">=</span><span class="st">"rmse"</span>,</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>    n_estimators<span class="op">=</span><span class="dv">200</span>,</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>    learning_rate<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>    max_depth<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>    min_child_weight<span class="op">=</span><span class="fl">5.0</span>,</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>    reg_lambda<span class="op">=</span><span class="fl">1.0</span>,</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>    init_method<span class="op">=</span><span class="st">"linear_pgarch"</span>,</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>xgb_pgarch_rmse.fit(y_tr_pgarch_scaled, X_pgarch_tr)</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>h_xgb_rmse_scaled <span class="op">=</span> xgb_pgarch_rmse.predict_variance(y_all_pgarch_scaled, X_pgarch_all)</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>h_xgb_rmse <span class="op">=</span> h_xgb_rmse_scaled <span class="op">/</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>xgb_pgarch_rmse_is <span class="op">=</span> h_xgb_rmse[:<span class="bu">len</span>(y_tr)]</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>xgb_pgarch_rmse_os <span class="op">=</span> h_xgb_rmse[<span class="bu">len</span>(y_tr):]</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"XGB-g-PGARCH (RMSE) train loss (scaled): </span><span class="sc">{</span>xgb_pgarch_rmse<span class="sc">.</span>train_loss_<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a><span class="co"># ── XGB-g-PGARCH (QLIKE) ───────────────────────────────────────────────</span></span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>xgb_pgarch_qlike <span class="op">=</span> XGBGPGARCHModel(</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>    loss<span class="op">=</span><span class="st">"qlike"</span>,</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>    n_estimators<span class="op">=</span><span class="dv">200</span>,</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>    learning_rate<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a>    max_depth<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a>    min_child_weight<span class="op">=</span><span class="fl">5.0</span>,</span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>    reg_lambda<span class="op">=</span><span class="fl">1.0</span>,</span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>    init_method<span class="op">=</span><span class="st">"linear_pgarch"</span>,</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a>    random_state<span class="op">=</span><span class="dv">42</span>,</span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>xgb_pgarch_qlike.fit(y_tr_pgarch_scaled, X_pgarch_tr)</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a>h_xgb_qlike_scaled <span class="op">=</span> xgb_pgarch_qlike.predict_variance(y_all_pgarch_scaled, X_pgarch_all)</span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a>h_xgb_qlike <span class="op">=</span> h_xgb_qlike_scaled <span class="op">/</span> (SCALE_FACTOR <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a>xgb_pgarch_qlike_is <span class="op">=</span> h_xgb_qlike[:<span class="bu">len</span>(y_tr)]</span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>xgb_pgarch_qlike_os <span class="op">=</span> h_xgb_qlike[<span class="bu">len</span>(y_tr):]</span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"XGB-g-PGARCH (QLIKE) train loss (scaled): </span><span class="sc">{</span>xgb_pgarch_qlike<span class="sc">.</span>train_loss_<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">All PGARCH models fitted."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>PGARCH-L (RMSE) implied GARCH (mean): omega=0.000003, alpha=0.0559, beta=0.9243
PGARCH-L (QLIKE) implied GARCH (mean): omega=0.000014, alpha=0.0138, beta=0.8888
XGB-g-PGARCH (RMSE) train loss (scaled): 24.466985
XGB-g-PGARCH (QLIKE) train loss (scaled): 0.930868

All PGARCH models fitted.</code></pre>
</div>
</div>
<div class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-03-17T21:38:24.394146Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-03-17T21:38:24.394060Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-03-17T21:38:24.450072Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-03-17T21:38:24.449626Z&quot;}}" data-tbl-cap="All eleven model variants: Part 4 baselines plus PGARCH-L and XGB-g-PGARCH" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>actual_is <span class="op">=</span> y_tr.values</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>actual_os <span class="op">=</span> y_te.values</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>model_predictions <span class="op">=</span> {</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GARCH(1,1)"</span>:         {<span class="st">"loss"</span>: <span class="st">"MLE"</span>,   <span class="st">"is"</span>: garch_pred_is,       <span class="st">"os"</span>: garch_pred_os},</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ES (RMSE)"</span>:          {<span class="st">"loss"</span>: <span class="st">"RMSE"</span>,  <span class="st">"is"</span>: es_pred_is,          <span class="st">"os"</span>: es_pred_os},</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ES (QLIKE)"</span>:         {<span class="st">"loss"</span>: <span class="st">"QLIKE"</span>, <span class="st">"is"</span>: es_qlike_pred_is,    <span class="st">"os"</span>: es_qlike_pred_os},</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"STES (RMSE)"</span>:        {<span class="st">"loss"</span>: <span class="st">"RMSE"</span>,  <span class="st">"is"</span>: stes_pred_is,        <span class="st">"os"</span>: stes_pred_os},</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"STES (QLIKE)"</span>:       {<span class="st">"loss"</span>: <span class="st">"QLIKE"</span>, <span class="st">"is"</span>: stes_qlike_pred_is,  <span class="st">"os"</span>: stes_qlike_pred_os},</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGBSTES (RMSE)"</span>:     {<span class="st">"loss"</span>: <span class="st">"RMSE"</span>,  <span class="st">"is"</span>: xgbstes_pred_is,     <span class="st">"os"</span>: xgbstes_pred_os},</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGBSTES (QLIKE)"</span>:    {<span class="st">"loss"</span>: <span class="st">"QLIKE"</span>, <span class="st">"is"</span>: xgb_qlike_pred_is,   <span class="st">"os"</span>: xgb_qlike_pred_os},</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"PGARCH-L (RMSE)"</span>:    {<span class="st">"loss"</span>: <span class="st">"RMSE"</span>,  <span class="st">"is"</span>: pgarch_l_rmse_is,    <span class="st">"os"</span>: pgarch_l_rmse_os},</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"PGARCH-L (QLIKE)"</span>:   {<span class="st">"loss"</span>: <span class="st">"QLIKE"</span>, <span class="st">"is"</span>: pgarch_l_qlike_is,   <span class="st">"os"</span>: pgarch_l_qlike_os},</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGB-g-PGARCH (RMSE)"</span>:  {<span class="st">"loss"</span>: <span class="st">"RMSE"</span>,  <span class="st">"is"</span>: xgb_pgarch_rmse_is,  <span class="st">"os"</span>: xgb_pgarch_rmse_os},</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGB-g-PGARCH (QLIKE)"</span>: {<span class="st">"loss"</span>: <span class="st">"QLIKE"</span>, <span class="st">"is"</span>: xgb_pgarch_qlike_is, <span class="st">"os"</span>: xgb_pgarch_qlike_os},</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>comparison_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Model"</span>: <span class="bu">list</span>(model_predictions.keys()),</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Train Loss"</span>: [v[<span class="st">"loss"</span>] <span class="cf">for</span> v <span class="kw">in</span> model_predictions.values()],</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"IS RMSE"</span>: [rmse(actual_is, v[<span class="st">"is"</span>]) <span class="cf">for</span> v <span class="kw">in</span> model_predictions.values()],</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"OS RMSE"</span>: [rmse(actual_os, v[<span class="st">"os"</span>]) <span class="cf">for</span> v <span class="kw">in</span> model_predictions.values()],</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"OS MAE"</span>: [mae(actual_os, v[<span class="st">"os"</span>]) <span class="cf">for</span> v <span class="kw">in</span> model_predictions.values()],</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"OS QLIKE"</span>: [qlike(actual_os, v[<span class="st">"os"</span>]) <span class="cf">for</span> v <span class="kw">in</span> model_predictions.values()],</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>display(style_results_table(comparison_table, precision<span class="op">=</span><span class="dv">6</span>, index_col<span class="op">=</span><span class="st">"Model"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="full-benchmark-table" class="cell-output cell-output-display">
<style type="text/css">
#T_59b54 table {
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.95rem;
  line-height: 1.4;
}
#T_59b54 thead th {
  text-align: left;
  font-weight: 600;
  border-bottom: 1px solid #ddd;
  padding: 8px 12px;
}
#T_59b54 tbody td {
  padding: 8px 12px;
  border-bottom: 1px solid #eee;
}
#T_59b54 tbody tr:nth-child(even) {
  background-color: #f7f7f756;
}
</style>

<table id="T_59b54" class="caption-top">
<caption>All eleven model variants: Part 4 baselines plus PGARCH-L and XGB-g-PGARCH</caption>
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_59b54_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Train Loss</th>
<th id="T_59b54_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">IS RMSE</th>
<th id="T_59b54_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">OS RMSE</th>
<th id="T_59b54_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">OS MAE</th>
<th id="T_59b54_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">OS QLIKE</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Model</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col3" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col4" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_59b54_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">GARCH(1,1)</th>
<td id="T_59b54_row0_col0" class="data row0 col0">MLE</td>
<td id="T_59b54_row0_col1" class="data row0 col1">0.000504</td>
<td id="T_59b54_row0_col2" class="data row0 col2">0.000460</td>
<td id="T_59b54_row0_col3" class="data row0 col3">0.000139</td>
<td id="T_59b54_row0_col4" class="data row0 col4">1.561044</td>
</tr>
<tr class="even">
<th id="T_59b54_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">ES (RMSE)</th>
<td id="T_59b54_row1_col0" class="data row1 col0">RMSE</td>
<td id="T_59b54_row1_col1" class="data row1 col1">0.000506</td>
<td id="T_59b54_row1_col2" class="data row1 col2">0.000464</td>
<td id="T_59b54_row1_col3" class="data row1 col3">0.000140</td>
<td id="T_59b54_row1_col4" class="data row1 col4">1.619824</td>
</tr>
<tr class="odd">
<th id="T_59b54_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">ES (QLIKE)</th>
<td id="T_59b54_row2_col0" class="data row2 col0">QLIKE</td>
<td id="T_59b54_row2_col1" class="data row2 col1">0.000508</td>
<td id="T_59b54_row2_col2" class="data row2 col2">0.000477</td>
<td id="T_59b54_row2_col3" class="data row2 col3">0.000144</td>
<td id="T_59b54_row2_col4" class="data row2 col4">1.613638</td>
</tr>
<tr class="even">
<th id="T_59b54_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">STES (RMSE)</th>
<td id="T_59b54_row3_col0" class="data row3 col0">RMSE</td>
<td id="T_59b54_row3_col1" class="data row3 col1">0.000501</td>
<td id="T_59b54_row3_col2" class="data row3 col2">0.000451</td>
<td id="T_59b54_row3_col3" class="data row3 col3">0.000135</td>
<td id="T_59b54_row3_col4" class="data row3 col4">1.637742</td>
</tr>
<tr class="odd">
<th id="T_59b54_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">STES (QLIKE)</th>
<td id="T_59b54_row4_col0" class="data row4 col0">QLIKE</td>
<td id="T_59b54_row4_col1" class="data row4 col1">0.000503</td>
<td id="T_59b54_row4_col2" class="data row4 col2">0.000478</td>
<td id="T_59b54_row4_col3" class="data row4 col3">0.000141</td>
<td id="T_59b54_row4_col4" class="data row4 col4">1.599050</td>
</tr>
<tr class="even">
<th id="T_59b54_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">XGBSTES (RMSE)</th>
<td id="T_59b54_row5_col0" class="data row5 col0">RMSE</td>
<td id="T_59b54_row5_col1" class="data row5 col1">0.000503</td>
<td id="T_59b54_row5_col2" class="data row5 col2">0.000440</td>
<td id="T_59b54_row5_col3" class="data row5 col3">0.000132</td>
<td id="T_59b54_row5_col4" class="data row5 col4">1.706396</td>
</tr>
<tr class="odd">
<th id="T_59b54_level0_row6" class="row_heading level0 row6" data-quarto-table-cell-role="th">XGBSTES (QLIKE)</th>
<td id="T_59b54_row6_col0" class="data row6 col0">QLIKE</td>
<td id="T_59b54_row6_col1" class="data row6 col1">0.000510</td>
<td id="T_59b54_row6_col2" class="data row6 col2">0.000472</td>
<td id="T_59b54_row6_col3" class="data row6 col3">0.000148</td>
<td id="T_59b54_row6_col4" class="data row6 col4">1.610119</td>
</tr>
<tr class="even">
<th id="T_59b54_level0_row7" class="row_heading level0 row7" data-quarto-table-cell-role="th">PGARCH-L (RMSE)</th>
<td id="T_59b54_row7_col0" class="data row7 col0">RMSE</td>
<td id="T_59b54_row7_col1" class="data row7 col1">0.000510</td>
<td id="T_59b54_row7_col2" class="data row7 col2">0.000466</td>
<td id="T_59b54_row7_col3" class="data row7 col3">0.000151</td>
<td id="T_59b54_row7_col4" class="data row7 col4">1.641674</td>
</tr>
<tr class="odd">
<th id="T_59b54_level0_row8" class="row_heading level0 row8" data-quarto-table-cell-role="th">PGARCH-L (QLIKE)</th>
<td id="T_59b54_row8_col0" class="data row8 col0">QLIKE</td>
<td id="T_59b54_row8_col1" class="data row8 col1">0.000483</td>
<td id="T_59b54_row8_col2" class="data row8 col2">0.000459</td>
<td id="T_59b54_row8_col3" class="data row8 col3">0.000132</td>
<td id="T_59b54_row8_col4" class="data row8 col4">1.550144</td>
</tr>
<tr class="even">
<th id="T_59b54_level0_row9" class="row_heading level0 row9" data-quarto-table-cell-role="th">XGB-g-PGARCH (RMSE)</th>
<td id="T_59b54_row9_col0" class="data row9 col0">RMSE</td>
<td id="T_59b54_row9_col1" class="data row9 col1">0.000495</td>
<td id="T_59b54_row9_col2" class="data row9 col2">0.000452</td>
<td id="T_59b54_row9_col3" class="data row9 col3">0.000134</td>
<td id="T_59b54_row9_col4" class="data row9 col4">1.718700</td>
</tr>
<tr class="odd">
<th id="T_59b54_level0_row10" class="row_heading level0 row10" data-quarto-table-cell-role="th">XGB-g-PGARCH (QLIKE)</th>
<td id="T_59b54_row10_col0" class="data row10 col0">QLIKE</td>
<td id="T_59b54_row10_col1" class="data row10 col1">0.000490</td>
<td id="T_59b54_row10_col2" class="data row10 col2">0.000468</td>
<td id="T_59b54_row10_col3" class="data row10 col3">0.000133</td>
<td id="T_59b54_row10_col4" class="data row10 col4">1.558804</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-ranking-chart" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-03-17T21:38:24.452175Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-03-17T21:38:24.451893Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-03-17T21:38:24.647293Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-03-17T21:38:24.647010Z&quot;}}" data-execution_count="6">
<details class="code-fold">
<summary>Two-panel ranking chart: OS RMSE vs OS QLIKE</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Color mapping: PGARCH family gets a distinct blue-green palette</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>_palette <span class="op">=</span> {</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GARCH(1,1)"</span>:           <span class="st">"#5F7A8A"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ES (RMSE)"</span>:            <span class="st">"#C9A66B"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ES (QLIKE)"</span>:           <span class="st">"#A68B4B"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"STES (RMSE)"</span>:          BLOG_PALETTE[<span class="dv">0</span>],</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"STES (QLIKE)"</span>:         <span class="st">"#D8893B"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGBSTES (RMSE)"</span>:       BLOG_PALETTE[<span class="dv">1</span>],</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGBSTES (QLIKE)"</span>:      <span class="st">"#8C5E58"</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"PGARCH-L (RMSE)"</span>:      <span class="st">"#2B7A78"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"PGARCH-L (QLIKE)"</span>:     <span class="st">"#17614E"</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGB-g-PGARCH (RMSE)"</span>:  <span class="st">"#3AAFA9"</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"XGB-g-PGARCH (QLIKE)"</span>: <span class="st">"#1B8A84"</span>,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">8</span>))</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, metric <span class="kw">in</span> <span class="bu">zip</span>(axes, [<span class="st">"OS RMSE"</span>, <span class="st">"OS QLIKE"</span>]):</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    chart_df <span class="op">=</span> comparison_table.sort_values(metric, ascending<span class="op">=</span><span class="va">True</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    colors <span class="op">=</span> [_palette.get(m, <span class="st">"#999999"</span>) <span class="cf">for</span> m <span class="kw">in</span> chart_df[<span class="st">"Model"</span>]]</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    bars <span class="op">=</span> ax.barh(chart_df[<span class="st">"Model"</span>], chart_df[metric], color<span class="op">=</span>colors, edgecolor<span class="op">=</span><span class="st">"white"</span>, linewidth<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    ax.set_title(metric, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(metric)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    ax.invert_yaxis()</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> bar, val <span class="kw">in</span> <span class="bu">zip</span>(bars, chart_df[metric]):</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>        ax.text(val, bar.get_y() <span class="op">+</span> bar.get_height() <span class="op">/</span> <span class="dv">2</span>, <span class="ss">f" </span><span class="sc">{</span>val<span class="sc">:.6f}</span><span class="ss">"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">"Out-of-Sample Rankings: All Eleven Models"</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img src="index_files/figure-html/ranking-chart-output-1.png" id="ranking-chart" class="img-fluid"></p>
</figure>
</div>
</div>
</div>
<h2 data-number="5" id="analysis" class="anchored"><span class="header-section-number">5</span> Analysis</h2>
<p>The benchmark table and ranking chart shows the following:</p>
<p><strong>PGARCH-L (QLIKE) takes the top QLIKE spot.</strong> With an OS QLIKE of 1.550, it edges out GARCH(1,1) (1.561) — the model that dominated every STES variant in <a href="../volatility-forecasts-4/">Part 4</a>. It also ranks 4th in RMSE (0.000459), making it the first model in the series to be competitive on <em>both</em> metrics simultaneously. This confirms the structural hypothesis: preserving the three-channel decomposition (<span class="math inline">\mu</span>, <span class="math inline">\phi</span>, <span class="math inline">g</span>) while adding predictor-driven flexibility is what it takes to match or beat GARCH under QLIKE.</p>
<p><strong>XGB-g-PGARCH (RMSE) is the 3rd-best RMSE model</strong> (0.000452), behind only XGBSTES (RMSE) and STES (RMSE). The nonlinear boosting in the <span class="math inline">g</span>-channel picks up level-sensitive signal that the linear model misses. However, the same model ranks dead last in QLIKE (1.719) — worse even than XGBSTES (RMSE). The boosted gate’s flexibility, when trained under RMSE, drives the variance forecast in directions that QLIKE punishes.</p>
<p><strong>XGB-g-PGARCH (QLIKE) lands between the linear extremes.</strong> At QLIKE rank 2 (1.559) it closes most of the gap to GARCH but falls behind PGARCH-L (QLIKE). Its RMSE is somewhat worse (rank 8, 0.000468). The result suggests that boosting the <span class="math inline">g</span>-channel under QLIKE adds noise relative to the linear baseline — the current three-feature predictor space does not contain enough nonlinear signal to justify the additional flexibility.</p>
<p><strong>RMSE-trained PGARCH-L misses on QLIKE</strong> (1.642, rank 9), echoing the <a href="../volatility-forecasts-4/">Part 4</a> finding that even the right model structure cannot overcome a misaligned training loss.</p>
<p>We now formalize these observations with head-to-head comparisons, Diebold-Mariano tests, and Mincer-Zarnowitz calibration regressions.</p>
<div id="head-to-head-table" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-03-17T21:38:24.648849Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-03-17T21:38:24.648743Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-03-17T21:38:24.660574Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-03-17T21:38:24.660196Z&quot;}}" data-tbl-cap="Head-to-head: RMSE-trained vs QLIKE-trained within each PGARCH family, and cross-family comparisons" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Within-family: PGARCH-L and XGB-g-PGARCH ───────────────────────────</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>head_to_head <span class="op">=</span> pd.DataFrame({</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Family"</span>: [<span class="st">"PGARCH-L"</span>, <span class="st">"XGB-g-PGARCH"</span>],</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"OS RMSE (RMSE)"</span>: [</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        rmse(actual_os, pgarch_l_rmse_os),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        rmse(actual_os, xgb_pgarch_rmse_os),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"OS RMSE (QLIKE)"</span>: [</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        rmse(actual_os, pgarch_l_qlike_os),</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>        rmse(actual_os, xgb_pgarch_qlike_os),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Δ RMSE"</span>: [</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>        rmse(actual_os, pgarch_l_qlike_os) <span class="op">-</span> rmse(actual_os, pgarch_l_rmse_os),</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>        rmse(actual_os, xgb_pgarch_qlike_os) <span class="op">-</span> rmse(actual_os, xgb_pgarch_rmse_os),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"OS QLIKE (RMSE)"</span>: [</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>        qlike(actual_os, pgarch_l_rmse_os),</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        qlike(actual_os, xgb_pgarch_rmse_os),</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"OS QLIKE (QLIKE)"</span>: [</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>        qlike(actual_os, pgarch_l_qlike_os),</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>        qlike(actual_os, xgb_pgarch_qlike_os),</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Δ QLIKE"</span>: [</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>        qlike(actual_os, pgarch_l_qlike_os) <span class="op">-</span> qlike(actual_os, pgarch_l_rmse_os),</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>        qlike(actual_os, xgb_pgarch_qlike_os) <span class="op">-</span> qlike(actual_os, xgb_pgarch_rmse_os),</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Head-to-head: RMSE-trained vs QLIKE-trained within each PGARCH family:"</span>)</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>display(style_results_table(head_to_head, precision<span class="op">=</span><span class="dv">6</span>, index_col<span class="op">=</span><span class="st">"Family"</span>))</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Full 11-model ranking table ─────────────────────────────────────────</span></span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>rank_table <span class="op">=</span> comparison_table[[<span class="st">"Model"</span>, <span class="st">"OS RMSE"</span>, <span class="st">"OS QLIKE"</span>]].copy()</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>rank_table[<span class="st">"RMSE Rank"</span>] <span class="op">=</span> rank_table[<span class="st">"OS RMSE"</span>].rank(method<span class="op">=</span><span class="st">"dense"</span>).astype(<span class="bu">int</span>)</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>rank_table[<span class="st">"QLIKE Rank"</span>] <span class="op">=</span> rank_table[<span class="st">"OS QLIKE"</span>].rank(method<span class="op">=</span><span class="st">"dense"</span>).astype(<span class="bu">int</span>)</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>rank_table <span class="op">=</span> rank_table.sort_values([<span class="st">"RMSE Rank"</span>, <span class="st">"QLIKE Rank"</span>]).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Out-of-sample ranking under both loss functions:"</span>)</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>display(style_results_table(rank_table, precision<span class="op">=</span><span class="dv">6</span>, index_col<span class="op">=</span><span class="st">"Model"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Head-to-head: RMSE-trained vs QLIKE-trained within each PGARCH family:</code></pre>
</div>
<div id="head-to-head-table-1" class="cell-output cell-output-display">
<style type="text/css">
#T_a2e33 table {
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.95rem;
  line-height: 1.4;
}
#T_a2e33 thead th {
  text-align: left;
  font-weight: 600;
  border-bottom: 1px solid #ddd;
  padding: 8px 12px;
}
#T_a2e33 tbody td {
  padding: 8px 12px;
  border-bottom: 1px solid #eee;
}
#T_a2e33 tbody tr:nth-child(even) {
  background-color: #f7f7f756;
}
</style>

<table id="T_a2e33" class="caption-top">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_a2e33_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">OS RMSE (RMSE)</th>
<th id="T_a2e33_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">OS RMSE (QLIKE)</th>
<th id="T_a2e33_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Δ RMSE</th>
<th id="T_a2e33_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">OS QLIKE (RMSE)</th>
<th id="T_a2e33_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">OS QLIKE (QLIKE)</th>
<th id="T_a2e33_level0_col5" class="col_heading level0 col5" data-quarto-table-cell-role="th">Δ QLIKE</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Family</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col3" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col4" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col5" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_a2e33_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">PGARCH-L</th>
<td id="T_a2e33_row0_col0" class="data row0 col0">0.000466</td>
<td id="T_a2e33_row0_col1" class="data row0 col1">0.000459</td>
<td id="T_a2e33_row0_col2" class="data row0 col2">-0.000007</td>
<td id="T_a2e33_row0_col3" class="data row0 col3">1.641674</td>
<td id="T_a2e33_row0_col4" class="data row0 col4">1.550144</td>
<td id="T_a2e33_row0_col5" class="data row0 col5">-0.091530</td>
</tr>
<tr class="even">
<th id="T_a2e33_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">XGB-g-PGARCH</th>
<td id="T_a2e33_row1_col0" class="data row1 col0">0.000452</td>
<td id="T_a2e33_row1_col1" class="data row1 col1">0.000468</td>
<td id="T_a2e33_row1_col2" class="data row1 col2">0.000016</td>
<td id="T_a2e33_row1_col3" class="data row1 col3">1.718700</td>
<td id="T_a2e33_row1_col4" class="data row1 col4">1.558804</td>
<td id="T_a2e33_row1_col5" class="data row1 col5">-0.159896</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Out-of-sample ranking under both loss functions:</code></pre>
</div>
<div id="head-to-head-table-2" class="cell-output cell-output-display">
<style type="text/css">
#T_38850 table {
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.95rem;
  line-height: 1.4;
}
#T_38850 thead th {
  text-align: left;
  font-weight: 600;
  border-bottom: 1px solid #ddd;
  padding: 8px 12px;
}
#T_38850 tbody td {
  padding: 8px 12px;
  border-bottom: 1px solid #eee;
}
#T_38850 tbody tr:nth-child(even) {
  background-color: #f7f7f756;
}
</style>

<table id="T_38850" class="caption-top">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_38850_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">OS RMSE</th>
<th id="T_38850_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">OS QLIKE</th>
<th id="T_38850_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">RMSE Rank</th>
<th id="T_38850_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">QLIKE Rank</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Model</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col3" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_38850_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">XGBSTES (RMSE)</th>
<td id="T_38850_row0_col0" class="data row0 col0">0.000440</td>
<td id="T_38850_row0_col1" class="data row0 col1">1.706396</td>
<td id="T_38850_row0_col2" class="data row0 col2">1</td>
<td id="T_38850_row0_col3" class="data row0 col3">10</td>
</tr>
<tr class="even">
<th id="T_38850_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">STES (RMSE)</th>
<td id="T_38850_row1_col0" class="data row1 col0">0.000451</td>
<td id="T_38850_row1_col1" class="data row1 col1">1.637742</td>
<td id="T_38850_row1_col2" class="data row1 col2">2</td>
<td id="T_38850_row1_col3" class="data row1 col3">8</td>
</tr>
<tr class="odd">
<th id="T_38850_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">XGB-g-PGARCH (RMSE)</th>
<td id="T_38850_row2_col0" class="data row2 col0">0.000452</td>
<td id="T_38850_row2_col1" class="data row2 col1">1.718700</td>
<td id="T_38850_row2_col2" class="data row2 col2">3</td>
<td id="T_38850_row2_col3" class="data row2 col3">11</td>
</tr>
<tr class="even">
<th id="T_38850_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">PGARCH-L (QLIKE)</th>
<td id="T_38850_row3_col0" class="data row3 col0">0.000459</td>
<td id="T_38850_row3_col1" class="data row3 col1">1.550144</td>
<td id="T_38850_row3_col2" class="data row3 col2">4</td>
<td id="T_38850_row3_col3" class="data row3 col3">1</td>
</tr>
<tr class="odd">
<th id="T_38850_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">GARCH(1,1)</th>
<td id="T_38850_row4_col0" class="data row4 col0">0.000460</td>
<td id="T_38850_row4_col1" class="data row4 col1">1.561044</td>
<td id="T_38850_row4_col2" class="data row4 col2">5</td>
<td id="T_38850_row4_col3" class="data row4 col3">3</td>
</tr>
<tr class="even">
<th id="T_38850_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">ES (RMSE)</th>
<td id="T_38850_row5_col0" class="data row5 col0">0.000464</td>
<td id="T_38850_row5_col1" class="data row5 col1">1.619824</td>
<td id="T_38850_row5_col2" class="data row5 col2">6</td>
<td id="T_38850_row5_col3" class="data row5 col3">7</td>
</tr>
<tr class="odd">
<th id="T_38850_level0_row6" class="row_heading level0 row6" data-quarto-table-cell-role="th">PGARCH-L (RMSE)</th>
<td id="T_38850_row6_col0" class="data row6 col0">0.000466</td>
<td id="T_38850_row6_col1" class="data row6 col1">1.641674</td>
<td id="T_38850_row6_col2" class="data row6 col2">7</td>
<td id="T_38850_row6_col3" class="data row6 col3">9</td>
</tr>
<tr class="even">
<th id="T_38850_level0_row7" class="row_heading level0 row7" data-quarto-table-cell-role="th">XGB-g-PGARCH (QLIKE)</th>
<td id="T_38850_row7_col0" class="data row7 col0">0.000468</td>
<td id="T_38850_row7_col1" class="data row7 col1">1.558804</td>
<td id="T_38850_row7_col2" class="data row7 col2">8</td>
<td id="T_38850_row7_col3" class="data row7 col3">2</td>
</tr>
<tr class="odd">
<th id="T_38850_level0_row8" class="row_heading level0 row8" data-quarto-table-cell-role="th">XGBSTES (QLIKE)</th>
<td id="T_38850_row8_col0" class="data row8 col0">0.000472</td>
<td id="T_38850_row8_col1" class="data row8 col1">1.610119</td>
<td id="T_38850_row8_col2" class="data row8 col2">9</td>
<td id="T_38850_row8_col3" class="data row8 col3">5</td>
</tr>
<tr class="even">
<th id="T_38850_level0_row9" class="row_heading level0 row9" data-quarto-table-cell-role="th">ES (QLIKE)</th>
<td id="T_38850_row9_col0" class="data row9 col0">0.000477</td>
<td id="T_38850_row9_col1" class="data row9 col1">1.613638</td>
<td id="T_38850_row9_col2" class="data row9 col2">10</td>
<td id="T_38850_row9_col3" class="data row9 col3">6</td>
</tr>
<tr class="odd">
<th id="T_38850_level0_row10" class="row_heading level0 row10" data-quarto-table-cell-role="th">STES (QLIKE)</th>
<td id="T_38850_row10_col0" class="data row10 col0">0.000478</td>
<td id="T_38850_row10_col1" class="data row10 col1">1.599050</td>
<td id="T_38850_row10_col2" class="data row10 col2">11</td>
<td id="T_38850_row10_col3" class="data row10 col3">4</td>
</tr>
</tbody>
</table>
</div>
<p>Head-to-head: RMSE-trained vs QLIKE-trained within each PGARCH family, and cross-family comparisons</p>
</div>
<h2 data-number="6" id="formal-comparison-and-calibration" class="anchored"><span class="header-section-number">6</span> Formal Comparison and Calibration</h2>
<p>Point metrics and rankings are informative, but we need to test whether the differences are statistically meaningful. As in <a href="../volatility-forecasts-4/">Part 4</a>, we use two complementary diagnostics (<a href="../forecast-comparison/">background</a>):</p>
<ol type="1">
<li><strong>Diebold-Mariano tests</strong> on squared-error and QLIKE loss differentials. A negative DM statistic favors the first-named model.</li>
<li><strong>Mincer-Zarnowitz regressions</strong> on the variance scale. A slope <span class="math inline">\beta \approx 1</span> indicates well-calibrated forecasts.</li>
</ol>
<p>The key pairwise comparisons are: PGARCH-L vs GARCH (does the linear structural model match the benchmark?), XGB-g-PGARCH vs GARCH (does boosting improve on it?), XGB-g-PGARCH vs XGBSTES (does the PGARCH model family beat the STES model family?), and XGB-g-PGARCH vs PGARCH-L (does nonlinear flexibility in <span class="math inline">g_t</span> help or hurt?).</p>
<div id="dm-mz-tests" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-03-17T21:38:24.662277Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-03-17T21:38:24.662128Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-03-17T21:38:24.679627Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-03-17T21:38:24.679329Z&quot;}}" data-execution_count="8">
<details class="code-fold">
<summary>Diebold-Mariano tests and Mincer-Zarnowitz regressions</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _sq_loss(y, yhat):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (np.asarray(y) <span class="op">-</span> np.asarray(yhat)) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _qlike_loss(y, yhat, eps<span class="op">=</span><span class="fl">1e-8</span>):</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    y, yhat <span class="op">=</span> np.asarray(y, dtype<span class="op">=</span><span class="bu">float</span>), np.clip(np.asarray(yhat, dtype<span class="op">=</span><span class="bu">float</span>), eps, <span class="va">None</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    ratio <span class="op">=</span> np.clip(y, eps, <span class="va">None</span>) <span class="op">/</span> yhat</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ratio <span class="op">-</span> np.log(ratio) <span class="op">-</span> <span class="fl">1.0</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Key pairwise DM comparisons ────────────────────────────────────────</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>dm_pairs <span class="op">=</span> [</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># PGARCH-L vs GARCH</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"PGARCH-L (RMSE) vs GARCH"</span>,       pgarch_l_rmse_os,       garch_pred_os),</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"PGARCH-L (QLIKE) vs GARCH"</span>,      pgarch_l_qlike_os,      garch_pred_os),</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># XGB-g-PGARCH vs GARCH</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGB-g-PGARCH (RMSE) vs GARCH"</span>,   xgb_pgarch_rmse_os,     garch_pred_os),</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGB-g-PGARCH (QLIKE) vs GARCH"</span>,  xgb_pgarch_qlike_os,    garch_pred_os),</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># XGB-g-PGARCH vs XGBSTES (same family comparison)</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGB-g-PGARCH (RMSE) vs XGBSTES (RMSE)"</span>,   xgb_pgarch_rmse_os,  xgbstes_pred_os),</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGB-g-PGARCH (QLIKE) vs XGBSTES (QLIKE)"</span>,  xgb_pgarch_qlike_os, xgb_qlike_pred_os),</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># XGB-g-PGARCH vs PGARCH-L (boosting benefit)</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGB-g-PGARCH (RMSE) vs PGARCH-L (RMSE)"</span>,   xgb_pgarch_rmse_os,  pgarch_l_rmse_os),</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGB-g-PGARCH (QLIKE) vs PGARCH-L (QLIKE)"</span>,  xgb_pgarch_qlike_os, pgarch_l_qlike_os),</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>dm_rows <span class="op">=</span> []</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, pred_a, pred_b <span class="kw">in</span> dm_pairs:</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>    res_sq <span class="op">=</span> diebold_mariano(_sq_loss(actual_os, pred_a), _sq_loss(actual_os, pred_b), h<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>    res_ql <span class="op">=</span> diebold_mariano(_qlike_loss(actual_os, pred_a), _qlike_loss(actual_os, pred_b), h<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>    dm_rows.append({</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Comparison"</span>: label,</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>        <span class="st">"DM (SqErr)"</span>: res_sq[<span class="st">"dm_stat"</span>], <span class="st">"p (SqErr)"</span>: res_sq[<span class="st">"p_value"</span>],</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>        <span class="st">"DM (QLIKE)"</span>: res_ql[<span class="st">"dm_stat"</span>], <span class="st">"p (QLIKE)"</span>: res_ql[<span class="st">"p_value"</span>],</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>dm_table <span class="op">=</span> pd.DataFrame(dm_rows)</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Diebold-Mariano tests (negative DM favors first-named model):"</span>)</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>display(style_results_table(dm_table, precision<span class="op">=</span><span class="dv">4</span>, index_col<span class="op">=</span><span class="st">"Comparison"</span>))</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Mincer-Zarnowitz regressions ────────────────────────────────────────</span></span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>mz_models <span class="op">=</span> [</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"GARCH(1,1)"</span>,           garch_pred_os),</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"ES (RMSE)"</span>,            es_pred_os),</span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"STES (RMSE)"</span>,          stes_pred_os),</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGBSTES (RMSE)"</span>,       xgbstes_pred_os),</span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGBSTES (QLIKE)"</span>,      xgb_qlike_pred_os),</span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"PGARCH-L (RMSE)"</span>,      pgarch_l_rmse_os),</span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"PGARCH-L (QLIKE)"</span>,     pgarch_l_qlike_os),</span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGB-g-PGARCH (RMSE)"</span>,  xgb_pgarch_rmse_os),</span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"XGB-g-PGARCH (QLIKE)"</span>, xgb_pgarch_qlike_os),</span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a>mz_rows <span class="op">=</span> []</span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, pred <span class="kw">in</span> mz_models:</span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a>    mz <span class="op">=</span> mincer_zarnowitz(actual_os, pred)</span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a>    mz_rows.append({</span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Model"</span>: label,</span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a>        <span class="st">"const"</span>: mz[<span class="st">"params"</span>].get(<span class="st">"const"</span>, np.nan),</span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a>        <span class="st">"beta"</span>: mz[<span class="st">"params"</span>].get(<span class="st">"beta"</span>, np.nan),</span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a>        <span class="st">"R2"</span>: mz[<span class="st">"r2"</span>],</span>
<span id="cb10-62"><a href="#cb10-62" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb10-63"><a href="#cb10-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-64"><a href="#cb10-64" aria-hidden="true" tabindex="-1"></a>mz_table <span class="op">=</span> pd.DataFrame(mz_rows)</span>
<span id="cb10-65"><a href="#cb10-65" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Mincer-Zarnowitz calibration regressions:"</span>)</span>
<span id="cb10-66"><a href="#cb10-66" aria-hidden="true" tabindex="-1"></a>display(style_results_table(mz_table, precision<span class="op">=</span><span class="dv">4</span>, index_col<span class="op">=</span><span class="st">"Model"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Diebold-Mariano tests (negative DM favors first-named model):</code></pre>
</div>
<div id="dm-mz-tests-1" class="cell-output cell-output-display">
<style type="text/css">
#T_31987 table {
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.95rem;
  line-height: 1.4;
}
#T_31987 thead th {
  text-align: left;
  font-weight: 600;
  border-bottom: 1px solid #ddd;
  padding: 8px 12px;
}
#T_31987 tbody td {
  padding: 8px 12px;
  border-bottom: 1px solid #eee;
}
#T_31987 tbody tr:nth-child(even) {
  background-color: #f7f7f756;
}
</style>

<table id="T_31987" class="caption-top">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_31987_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">DM (SqErr)</th>
<th id="T_31987_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">p (SqErr)</th>
<th id="T_31987_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">DM (QLIKE)</th>
<th id="T_31987_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">p (QLIKE)</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Comparison</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col3" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_31987_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">PGARCH-L (RMSE) vs GARCH</th>
<td id="T_31987_row0_col0" class="data row0 col0">1.3016</td>
<td id="T_31987_row0_col1" class="data row0 col1">0.1932</td>
<td id="T_31987_row0_col2" class="data row0 col2">4.7745</td>
<td id="T_31987_row0_col3" class="data row0 col3">0.0000</td>
</tr>
<tr class="even">
<th id="T_31987_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">PGARCH-L (QLIKE) vs GARCH</th>
<td id="T_31987_row1_col0" class="data row1 col0">-0.0735</td>
<td id="T_31987_row1_col1" class="data row1 col1">0.9414</td>
<td id="T_31987_row1_col2" class="data row1 col2">-0.4210</td>
<td id="T_31987_row1_col3" class="data row1 col3">0.6738</td>
</tr>
<tr class="odd">
<th id="T_31987_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">XGB-g-PGARCH (RMSE) vs GARCH</th>
<td id="T_31987_row2_col0" class="data row2 col0">-0.6818</td>
<td id="T_31987_row2_col1" class="data row2 col1">0.4955</td>
<td id="T_31987_row2_col2" class="data row2 col2">3.2143</td>
<td id="T_31987_row2_col3" class="data row2 col3">0.0013</td>
</tr>
<tr class="even">
<th id="T_31987_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">XGB-g-PGARCH (QLIKE) vs GARCH</th>
<td id="T_31987_row3_col0" class="data row3 col0">0.5035</td>
<td id="T_31987_row3_col1" class="data row3 col1">0.6147</td>
<td id="T_31987_row3_col2" class="data row3 col2">-0.0917</td>
<td id="T_31987_row3_col3" class="data row3 col3">0.9270</td>
</tr>
<tr class="odd">
<th id="T_31987_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">XGB-g-PGARCH (RMSE) vs XGBSTES (RMSE)</th>
<td id="T_31987_row4_col0" class="data row4 col0">0.8876</td>
<td id="T_31987_row4_col1" class="data row4 col1">0.3749</td>
<td id="T_31987_row4_col2" class="data row4 col2">0.8201</td>
<td id="T_31987_row4_col3" class="data row4 col3">0.4123</td>
</tr>
<tr class="even">
<th id="T_31987_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">XGB-g-PGARCH (QLIKE) vs XGBSTES (QLIKE)</th>
<td id="T_31987_row5_col0" class="data row5 col0">-0.1289</td>
<td id="T_31987_row5_col1" class="data row5 col1">0.8975</td>
<td id="T_31987_row5_col2" class="data row5 col2">-1.2912</td>
<td id="T_31987_row5_col3" class="data row5 col3">0.1968</td>
</tr>
<tr class="odd">
<th id="T_31987_level0_row6" class="row_heading level0 row6" data-quarto-table-cell-role="th">XGB-g-PGARCH (RMSE) vs PGARCH-L (RMSE)</th>
<td id="T_31987_row6_col0" class="data row6 col0">-1.1962</td>
<td id="T_31987_row6_col1" class="data row6 col1">0.2317</td>
<td id="T_31987_row6_col2" class="data row6 col2">1.2643</td>
<td id="T_31987_row6_col3" class="data row6 col3">0.2063</td>
</tr>
<tr class="even">
<th id="T_31987_level0_row7" class="row_heading level0 row7" data-quarto-table-cell-role="th">XGB-g-PGARCH (QLIKE) vs PGARCH-L (QLIKE)</th>
<td id="T_31987_row7_col0" class="data row7 col0">1.4877</td>
<td id="T_31987_row7_col1" class="data row7 col1">0.1370</td>
<td id="T_31987_row7_col2" class="data row7 col2">2.1293</td>
<td id="T_31987_row7_col3" class="data row7 col3">0.0333</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mincer-Zarnowitz calibration regressions:</code></pre>
</div>
<div id="dm-mz-tests-2" class="cell-output cell-output-display">
<style type="text/css">
#T_15c4b table {
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.95rem;
  line-height: 1.4;
}
#T_15c4b thead th {
  text-align: left;
  font-weight: 600;
  border-bottom: 1px solid #ddd;
  padding: 8px 12px;
}
#T_15c4b tbody td {
  padding: 8px 12px;
  border-bottom: 1px solid #eee;
}
#T_15c4b tbody tr:nth-child(even) {
  background-color: #f7f7f756;
}
</style>

<table id="T_15c4b" class="caption-top">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_15c4b_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">const</th>
<th id="T_15c4b_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">beta</th>
<th id="T_15c4b_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">R2</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Model</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_15c4b_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">GARCH(1,1)</th>
<td id="T_15c4b_row0_col0" class="data row0 col0">-0.0000</td>
<td id="T_15c4b_row0_col1" class="data row0 col1">1.0190</td>
<td id="T_15c4b_row0_col2" class="data row0 col2">0.2652</td>
</tr>
<tr class="even">
<th id="T_15c4b_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">ES (RMSE)</th>
<td id="T_15c4b_row1_col0" class="data row1 col0">0.0000</td>
<td id="T_15c4b_row1_col1" class="data row1 col1">0.8843</td>
<td id="T_15c4b_row1_col2" class="data row1 col2">0.2564</td>
</tr>
<tr class="odd">
<th id="T_15c4b_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">STES (RMSE)</th>
<td id="T_15c4b_row2_col0" class="data row2 col0">0.0000</td>
<td id="T_15c4b_row2_col1" class="data row2 col1">1.0122</td>
<td id="T_15c4b_row2_col2" class="data row2 col2">0.2930</td>
</tr>
<tr class="even">
<th id="T_15c4b_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">XGBSTES (RMSE)</th>
<td id="T_15c4b_row3_col0" class="data row3 col0">0.0000</td>
<td id="T_15c4b_row3_col1" class="data row3 col1">1.0725</td>
<td id="T_15c4b_row3_col2" class="data row3 col2">0.3275</td>
</tr>
<tr class="odd">
<th id="T_15c4b_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">XGBSTES (QLIKE)</th>
<td id="T_15c4b_row4_col0" class="data row4 col0">0.0000</td>
<td id="T_15c4b_row4_col1" class="data row4 col1">0.7272</td>
<td id="T_15c4b_row4_col2" class="data row4 col2">0.2635</td>
</tr>
<tr class="even">
<th id="T_15c4b_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">PGARCH-L (RMSE)</th>
<td id="T_15c4b_row5_col0" class="data row5 col0">-0.0000</td>
<td id="T_15c4b_row5_col1" class="data row5 col1">1.0262</td>
<td id="T_15c4b_row5_col2" class="data row5 col2">0.2466</td>
</tr>
<tr class="odd">
<th id="T_15c4b_level0_row6" class="row_heading level0 row6" data-quarto-table-cell-role="th">PGARCH-L (QLIKE)</th>
<td id="T_15c4b_row6_col0" class="data row6 col0">-0.0000</td>
<td id="T_15c4b_row6_col1" class="data row6 col1">1.2821</td>
<td id="T_15c4b_row6_col2" class="data row6 col2">0.2817</td>
</tr>
<tr class="even">
<th id="T_15c4b_level0_row7" class="row_heading level0 row7" data-quarto-table-cell-role="th">XGB-g-PGARCH (RMSE)</th>
<td id="T_15c4b_row7_col0" class="data row7 col0">0.0000</td>
<td id="T_15c4b_row7_col1" class="data row7 col1">1.0690</td>
<td id="T_15c4b_row7_col2" class="data row7 col2">0.2910</td>
</tr>
<tr class="odd">
<th id="T_15c4b_level0_row8" class="row_heading level0 row8" data-quarto-table-cell-role="th">XGB-g-PGARCH (QLIKE)</th>
<td id="T_15c4b_row8_col0" class="data row8 col0">-0.0000</td>
<td id="T_15c4b_row8_col1" class="data row8 col1">1.1459</td>
<td id="T_15c4b_row8_col2" class="data row8 col2">0.2431</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The DM tests organize the eleven models into four stories.</p>
<ol type="1">
<li><p><strong>PGARCH-L (QLIKE) vs GARCH — statistically indistinguishable.</strong> Under QLIKE loss, DM = −0.42 (p = 0.67); under squared error, DM = −0.07 (p = 0.94). The point estimates favor PGARCH-L on both metrics, but the improvement is too small to reject equal predictive ability. This is still a meaningful result though: PGARCH-L <em>matches</em> GARCH under QLIKE — something no STES variant accomplished in Part 4. When trained under RMSE instead, PGARCH-L significantly underperforms GARCH on QLIKE (DM = 4.77, p &lt; 0.001), confirming that the training loss must align with the evaluation criterion.</p></li>
<li><p><strong>XGB-g-PGARCH (QLIKE) vs GARCH — also indistinguishable.</strong> DM = −0.09 (p = 0.93) under QLIKE. The boosted model matches GARCH but does not improve on it. However, XGB-g-PGARCH (RMSE) tells a different story: despite ranking 3rd in RMSE, it significantly underperforms GARCH on QLIKE (DM = 3.21, p = 0.001). The boosted <span class="math inline">g</span>-channel, when optimized for squared error, overshoots on the episodes that QLIKE penalizes most.</p></li>
<li><p><strong>XGB-g-PGARCH vs PGARCH-L — boosting hurts under QLIKE.</strong> XGB-g-PGARCH (QLIKE) vs PGARCH-L (QLIKE) yields DM = 2.13 (p = 0.033) under QLIKE loss — the <em>linear</em> model significantly outperforms the <em>boosted</em> model. Under squared error, DM = 1.49 (p = 0.14) also favors PGARCH-L directionally. With only three return-based features, the nonlinear flexibility in the boosted <span class="math inline">g</span>-channel does not find useful signal; it adds estimation noise that degrades QLIKE performance. This result underscores that model complexity must be justified by feature richness.</p></li>
<li><p><strong>PGARCH vs STES/XGBSTES.</strong> XGB-g-PGARCH (RMSE) vs XGBSTES (RMSE): DM = 0.82 (p = 0.41) under QLIKE. XGBSTES still has the lower mean QLIKE on this split, but once the RMSE baselines are refit locally the difference is no longer statistically significant. XGB-g-PGARCH (QLIKE) vs XGBSTES (QLIKE): DM = −1.29 (p = 0.20) — the PGARCH model family shows a directional QLIKE advantage but not significant.</p></li>
</ol>
<p><strong>MZ calibration</strong> reveals a trade-off between QLIKE score and proportional calibration. GARCH (β = 1.02) and PGARCH-L (RMSE) (β = 1.03) are the best-calibrated models. PGARCH-L (QLIKE) overshoots to β = 1.28, while XGB-g-PGARCH (QLIKE) sits at β = 1.15 — better calibrated than PGARCH-L (QLIKE) but with a worse QLIKE score. The boosted model’s additional flexibility pulls calibration back toward one at the cost of QLIKE optimality. XGBSTES (RMSE) retains the highest R² (0.33), while the PGARCH family ranges from 0.24 to 0.29.</p>
<h2 data-number="7" id="structural-parameter-dynamics" class="anchored"><span class="header-section-number">7</span> Structural Parameter Dynamics</h2>
<p>One advantage of the PGARCH decomposition over STES is interpretability. Because PGARCH exposes <span class="math inline">\mu_t</span>, <span class="math inline">\phi_t</span>, and <span class="math inline">g_t</span> as separate time-varying quantities, we can inspect how each structural role evolves over the out-of-sample period. STES provides only a single gate <span class="math inline">\alpha_t</span>, which conflates all three roles.</p>
<p>The figure below plots the three channels from PGARCH-L (QLIKE) over the test period. We expect <span class="math inline">\mu_t</span> to track long-run variance regimes, <span class="math inline">\phi_t</span> to remain high (reflecting the well-known persistence of equity volatility), and <span class="math inline">g_t</span> to spike after large shocks — the same reaction pattern that STES captures, but now isolated from the persistence and level channels.</p>
<div id="bowyeag579c" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-03-17T21:38:24.681190Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-03-17T21:38:24.681081Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-03-17T21:38:25.155061Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-03-17T21:38:25.154786Z&quot;}}" data-execution_count="9">
<details class="code-fold">
<summary>Time-varying structural parameters: μ_t, φ_t, g_t over the test period</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract PGARCH-L (QLIKE) structural components for the OS period</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>comps_os <span class="op">=</span> pgarch_l_qlike.predict_components(X_pgarch_te.values)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>mu_os <span class="op">=</span> comps_os[<span class="st">"mu"</span>]</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>phi_os <span class="op">=</span> comps_os[<span class="st">"phi"</span>]</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>g_os <span class="op">=</span> comps_os[<span class="st">"g"</span>]</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>dates_os <span class="op">=</span> X_te.index</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">9</span>), sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel 1: long-run anchor μ_t</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(dates_os, mu_os, color<span class="op">=</span><span class="st">"#17614E"</span>, linewidth<span class="op">=</span><span class="fl">0.8</span>, label<span class="op">=</span><span class="vs">r"</span><span class="dv">$\m</span><span class="vs">u_t</span><span class="dv">$</span><span class="vs"> </span><span class="kw">(</span><span class="vs">long-run anchor</span><span class="kw">)</span><span class="vs">"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axhline(np.mean(mu_os), color<span class="op">=</span><span class="st">"#999999"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, linewidth<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span><span class="ss">f"mean = </span><span class="sc">{</span>np<span class="sc">.</span>mean(mu_os)<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="vs">r"</span><span class="dv">$\m</span><span class="vs">u_t</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(loc<span class="op">=</span><span class="st">"upper right"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Long-Run Variance Anchor"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel 2: total persistence φ_t</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(dates_os, phi_os, color<span class="op">=</span><span class="st">"#2B7A78"</span>, linewidth<span class="op">=</span><span class="fl">0.8</span>, label<span class="op">=</span><span class="vs">r"</span><span class="dv">$</span><span class="er">\</span><span class="vs">phi_t</span><span class="dv">$</span><span class="vs"> </span><span class="kw">(</span><span class="vs">persistence</span><span class="kw">)</span><span class="vs">"</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axhline(np.mean(phi_os), color<span class="op">=</span><span class="st">"#999999"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, linewidth<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span><span class="ss">f"mean = </span><span class="sc">{</span>np<span class="sc">.</span>mean(phi_os)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="vs">r"</span><span class="dv">$</span><span class="er">\</span><span class="vs">phi_t</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend(loc<span class="op">=</span><span class="st">"lower right"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Total Persistence"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel 3: innovation share g_t</span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].plot(dates_os, g_os, color<span class="op">=</span><span class="st">"#3AAFA9"</span>, linewidth<span class="op">=</span><span class="fl">0.8</span>, label<span class="op">=</span><span class="vs">r"</span><span class="dv">$</span><span class="vs">g_t</span><span class="dv">$</span><span class="vs"> </span><span class="kw">(</span><span class="vs">innovation share</span><span class="kw">)</span><span class="vs">"</span>)</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].axhline(np.mean(g_os), color<span class="op">=</span><span class="st">"#999999"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, linewidth<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span><span class="ss">f"mean = </span><span class="sc">{</span>np<span class="sc">.</span>mean(g_os)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_ylabel(<span class="vs">r"</span><span class="dv">$</span><span class="vs">g_t</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].legend(loc<span class="op">=</span><span class="st">"upper right"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"Innovation Share"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">"PGARCH-L (QLIKE): Structural Parameter Dynamics — Out of Sample"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img src="index_files/figure-html/cell-10-output-1.png" class="img-fluid"></p>
</figure>
</div>
</div>
</div>
<div id="f9qc419q97d" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-03-17T21:38:25.157560Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-03-17T21:38:25.157366Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-03-17T21:38:25.272995Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-03-17T21:38:25.272693Z&quot;}}" data-execution_count="10">
<details class="code-fold">
<summary>Forecast paths: GARCH vs PGARCH-L vs XGB-g-PGARCH (2019–2021 window)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Focus on a window that includes the COVID volatility spike</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>window_start <span class="op">=</span> pd.Timestamp(<span class="st">"2019-01-01"</span>, tz<span class="op">=</span><span class="st">"UTC"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>window_end <span class="op">=</span> pd.Timestamp(<span class="st">"2021-12-31"</span>, tz<span class="op">=</span><span class="st">"UTC"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> (dates_os <span class="op">&gt;=</span> window_start) <span class="op">&amp;</span> (dates_os <span class="op">&lt;=</span> window_end)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">5</span>))</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>ax.plot(dates_os[mask], actual_os[mask], color<span class="op">=</span><span class="st">"#CCCCCC"</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, label<span class="op">=</span><span class="st">"Realized variance"</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>ax.plot(dates_os[mask], garch_pred_os[mask], color<span class="op">=</span><span class="st">"#5F7A8A"</span>, linewidth<span class="op">=</span><span class="fl">1.0</span>, label<span class="op">=</span><span class="st">"GARCH(1,1)"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>ax.plot(dates_os[mask], pgarch_l_qlike_os[mask], color<span class="op">=</span><span class="st">"#17614E"</span>, linewidth<span class="op">=</span><span class="fl">1.0</span>, label<span class="op">=</span><span class="st">"PGARCH-L (QLIKE)"</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>ax.plot(dates_os[mask], xgb_pgarch_qlike_os[mask], color<span class="op">=</span><span class="st">"#3AAFA9"</span>, linewidth<span class="op">=</span><span class="fl">1.0</span>, label<span class="op">=</span><span class="st">"XGB-g-PGARCH (QLIKE)"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Variance"</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Out-of-Sample Forecast Paths (2019–2021)"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"upper right"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img src="index_files/figure-html/cell-11-output-1.png" class="img-fluid"></p>
</figure>
</div>
</div>
</div>
<h2 data-number="8" id="summary-of-rankings" class="anchored"><span class="header-section-number">8</span> Summary of Rankings</h2>
<p>Across all eleven model variants, the ranking table reveals a clear separation by training objective. Under RMSE, the top three are XGBSTES (RMSE), STES (RMSE), and XGB-g-PGARCH (RMSE). Under QLIKE, the top three are PGARCH-L (QLIKE), XGB-g-PGARCH (QLIKE), and GARCH(1,1).</p>
<p>PGARCH-L (QLIKE) is the first model in the series to rank in the top four under <em>both</em> criteria (rank 4 in RMSE, rank 1 in QLIKE). In Part 4, GARCH was the sole dual-metric performer. This is achieved by combining the GARCH structure that QLIKE rewards with predictor-driven flexibility that keeps RMSE competitive.</p>
<p>The boosted XGB-g-PGARCH variant shows a different pattern: strong in RMSE when RMSE-trained (rank 3), strong in QLIKE when QLIKE-trained (rank 2), but with sharper trade-offs between the two metrics. On this feature set, the linear PGARCH-L is the more robust choice.</p>
<h2 data-number="9" id="conclusion" class="anchored"><span class="header-section-number">9</span> Conclusion</h2>
<p>In this post we introduced PGARCH — a model family that generalizes GARCH(1,1) by making its structural parameters dependent on exogenous variables — and benchmarked two members against the seven models from Part 4. Three findings stand out.</p>
<ol type="1">
<li><p>The structural decomposition reduces QLIKE loss. PGARCH-L (QLIKE) achieves the best out-of-sample QLIKE score (1.550) across all eleven model variants, edging out GARCH(1,1) (1.561) while remaining competitive in RMSE (rank 4). No STES variant accomplished this in Part 4. The three-channel decomposition — separate <span class="math inline">\mu</span>, <span class="math inline">\phi</span>, <span class="math inline">g</span> — is the structural feature that QLIKE rewards, and PGARCH preserves it while adding predictor-driven flexibility. Formally, the DM test shows the improvement over GARCH is directional but not statistically significant (p = 0.67), placing PGARCH-L on equal footing with GARCH rather than clearly surpassing it.</p></li>
<li><p>Boosting the <span class="math inline">g</span>-channel alone creates on three features creates noisy results. XGB-g-PGARCH shows that nonlinear flexibility in the innovation-share channel can help (RMSE rank 3 under RMSE training) or hurt (significantly worse than PGARCH-L under QLIKE, DM = 2.13, p = 0.033). With only three return-based features, the boosted gate does not find enough nonlinear signal to justify its additional complexity under QLIKE — it adds estimation noise.</p></li>
<li><p>Training loss still dominates model structure. PGARCH-L (RMSE) scores 1.642 under QLIKE and is significantly worse than GARCH (DM = 4.77, p &lt; 0.001). XGB-g-PGARCH (RMSE) is even worse at 1.719, last among all eleven models. The same structural decomposition that leads the QLIKE rankings under QLIKE training falls to ranks 9 and 11 under RMSE training.</p></li>
</ol>
<h3 data-number="9.1" id="whats-next" class="anchored"><span class="header-section-number">9.1</span> What’s next</h3>
<p>The finding that boosting hurts on a sparse feature set points directly to the next step: the feature set may be the binding constraint. In the next post we will explore the following directions:</p>
<ol type="1">
<li><strong>Feature expansion</strong> — adding trailing realized-variance windows, calendar indicators, and economic variables to the predictor set. With a richer feature space, the nonlinear capacity of XGB-g-PGARCH should become an advantage rather than a liability.</li>
<li><strong>Multi-channel boosting</strong> — extending the XGBoost objective to jointly learn <span class="math inline">\mu_t</span> and <span class="math inline">g_t</span> (or all three channels), allowing the long-run anchor to respond to macroeconomic regimes.</li>
<li><strong>Rolling evaluation</strong> — replacing the fixed split with expanding-window or rolling-origin evaluation to produce time-indexed DM statistics and assess forecast stability across market regimes.</li>
</ol>
<h2 data-number="10" id="appendix-pgarch-derivative-details" class="anchored"><span class="header-section-number">10</span> Appendix: PGARCH Derivative Details</h2>
<p>This appendix collects the full derivative formulas used to train the models in this post.</p>
<h3 data-number="10.1" id="loss-functions" class="anchored"><span class="header-section-number">10.1</span> Loss functions</h3>
<p>We consider two training losses over the effective sample <span class="math inline">t = 1, \ldots, T-1</span> (excluding the warm-start <span class="math inline">h_0</span>), with <span class="math inline">N = T-1</span>:</p>
<p><strong>MSE:</strong> <span class="math display">
L_{\text{MSE}} = \frac{1}{N}\sum_{t=1}^{T-1}(y_t - h_t)^2, \qquad u_t = \frac{2(h_t - y_t)}{N}, \qquad v_t = \frac{2}{N}
</span></p>
<p><strong>QLIKE:</strong> <span class="math display">
L_{\text{QLIKE}} = \frac{1}{N}\sum_{t=1}^{T-1}\left(\log h_t + \frac{y_t}{h_t}\right), \qquad u_t = \frac{1}{N}\left(\frac{1}{h_t} - \frac{y_t}{h_t^2}\right), \qquad v_t = \frac{1}{N}\left(-\frac{1}{h_t^2} + \frac{2y_t}{h_t^3}\right)
</span></p>
<h3 data-number="10.2" id="jacobian-recursion-linear-pgarch" class="anchored"><span class="header-section-number">10.2</span> Jacobian recursion (Linear PGARCH)</h3>
<p>Let <span class="math inline">\theta = [w_\mu, w_\phi, w_g]</span> and <span class="math inline">\tilde{x}_{t-1} = [1, x_{t-1}]</span>. Define block-embedded vectors <span class="math inline">d_t^\mu</span>, <span class="math inline">d_t^\phi</span>, <span class="math inline">d_t^g</span> that place <span class="math inline">\tilde{x}_{t-1}</span> in the appropriate block of <span class="math inline">\theta</span> and zeros elsewhere.</p>
<p>The component Jacobians use the link derivatives:</p>
<p><span class="math display">
J_t^\mu = \sigma(a_t) d_t^\mu, \qquad
J_t^\phi = (\phi_{\max} - \phi_{\min}) s_b(1-s_b) d_t^\phi, \qquad
J_t^g = (g_{\max} - g_{\min}) s_c(1-s_c) d_t^g
</span></p>
<p>The intermediate quantity <span class="math inline">q_t = g_t y_{t-1} + (1-g_t)h_{t-1}</span> has Jacobian</p>
<p><span class="math display">
J_t^q = (1 - g_t) J_{t-1} + (y_{t-1} - h_{t-1}) J_t^g
</span></p>
<p>The state Jacobian follows from <span class="math inline">h_t = (1-\phi_t)\mu_t + \phi_t q_t</span>:</p>
<p><span class="math display">
J_t = (1-\phi_t) J_t^\mu + (q_t - \mu_t) J_t^\phi + \phi_t J_t^q, \qquad J_0 = 0
</span></p>
<h3 data-number="10.3" id="hessian-recursion-linear-pgarch" class="anchored"><span class="header-section-number">10.3</span> Hessian recursion (Linear PGARCH)</h3>
<p>The link Hessians are rank-one matrices:</p>
<p><span class="math display">
H_t^\mu = s_a(1-s_a) d_t^\mu (d_t^\mu)^\top, \qquad
H_t^\phi = (\phi_{\max}-\phi_{\min}) s_b(1-s_b)(1-2s_b) d_t^\phi (d_t^\phi)^\top
</span></p>
<p>and similarly for <span class="math inline">H_t^g</span>. The Hessian recursions are:</p>
<p><span class="math display">
H_t^q = (1-g_t) H_{t-1} + (y_{t-1}-h_{t-1}) H_t^g - J_t^g J_{t-1}^\top - J_{t-1}(J_t^g)^\top
</span></p>
<p><span class="math display">
H_t = (1-\phi_t) H_t^\mu + (q_t-\mu_t) H_t^\phi + \phi_t H_t^q + J_t^\phi(J_t^q - J_t^\mu)^\top + (J_t^q - J_t^\mu)(J_t^\phi)^\top, \qquad H_0 = 0
</span></p>
<h3 data-number="10.4" id="gradient-and-hessian-of-the-training-loss" class="anchored"><span class="header-section-number">10.4</span> Gradient and Hessian of the training loss</h3>
<p><span class="math display">
\nabla_\theta L = \sum_{t=1}^{T-1} u_t J_t, \qquad
\nabla_\theta^2 L = \sum_{t=1}^{T-1}\left(v_t J_t J_t^\top + u_t H_t\right)
</span></p>
<h3 data-number="10.5" id="xgb-g-pgarch-adjoint-gradient" class="anchored"><span class="header-section-number">10.5</span> XGB-g-PGARCH adjoint gradient</h3>
<p>With <span class="math inline">\mu_t</span>, <span class="math inline">\phi_t</span> fixed and only <span class="math inline">c_t</span> (the raw score for <span class="math inline">g_t</span>) variable:</p>
<ul>
<li><strong>Local impulse:</strong> <span class="math inline">\delta_s = \phi_s(y_s - h_s) C_s</span> where <span class="math inline">C_s = (g_{\max}-g_{\min}) \sigma(c_s)(1-\sigma(c_s))</span>.</li>
<li><strong>State propagation:</strong> <span class="math inline">\rho_s = \phi_s(1-g_s)</span>.</li>
<li><strong>Adjoint:</strong> <span class="math inline">\lambda_{T-1} = u_{T-1}</span>; <span class="math inline">\lambda_t = u_t + \rho_t \lambda_{t+1}</span> for <span class="math inline">t = T-2, \ldots, 0</span>.</li>
<li><strong>Row gradient:</strong> <span class="math inline">G_s = \lambda_{s+1}\,\delta_s</span> for <span class="math inline">s = 0, \ldots, T-2</span>; <span class="math inline">G_{T-1} = 0</span>.</li>
</ul>
<h3 data-number="10.6" id="xgb-g-pgarch-hessian-approximation" class="anchored"><span class="header-section-number">10.6</span> XGB-g-PGARCH Hessian approximation</h3>
<p><strong>MSE (Gauss-Newton):</strong> <span class="math display">
H_s \approx \sum_{t=s+1}^{T-1} \frac{2}{N}\left(\frac{\partial h_t}{\partial c_s}\right)^2
</span></p>
<p><strong>QLIKE (Fisher-style):</strong> replace <span class="math inline">2/N</span> with <span class="math inline">w_t = \operatorname{clip}(1/(N h_t^2), \varepsilon, w_{\max})</span>.</p>
<p>Both are computed efficiently via a backward accumulation:</p>
<p><span class="math display">
F_{T-1} = w_{T-1}, \qquad F_t = w_t + \rho_t^2 F_{t+1}, \qquad H_s = \delta_s^2 F_{s+1}
</span></p>


<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button,
          { trigger: "manual",
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/steveya\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined;
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              }
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            }
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>