---
# the default layout is 'page'
icon: fas fa-book
order: 1
---

The following is a list of my past and present projects. Each project consists of a title, a brief description, and a link to the project's GitHub repository. I will be updating this list as I continue to work on new projects.

Projects marked with Work in Progress (WIP) are still in progress and may not be fully functional.

## Signature Method
My study notes on the signature method
 - Blog Post:
   - [Signature Methods (Part 1 - Motivation)](../posts/signature-method-1/)
   - [Signature Methods (Part 2 - Signature and Augmentation)](../posts/signature-method-2/)
   - [Signature Methods (Part 3 - Lead–Lag Augmentation and Practical Limitations to the Signature Method)](../posts/signature-method-3/)
   - Signature Methods in Volatility Forecasts

## Volatility Forecasting
My work on volatility forecasting. How far can we go by extending simple exponential smoothing filter?
 - Blog Post: 
   - [Volatility Forecasts (Part 1 - ES vs STES Model)](../posts/volatility-forecasts-1/)
   - [Volatility Forecasts (Part 2 - XGBoost-STES Algorithm 1)](../posts/volatility-forecasts-2/)
   - [Volatility Forecasts (Part 3 - XGBoost-STES Algorithm 2)](../posts/volatility-forecasts-3/)
   - Signature Methods in Volatility Forecasts
 - Research Code: [volatility-forecast](https://github.com/steveya/volatility-forecast/blob/main/examples)
 - Research Library: [volatility-forecast](https://github.com/steveya/volatility-forecast)

## Malaria Detection
My work on the Capstone Project for the certificate program Applied Data Science with MIT Professional Education. 
 - Blog Post: 
   - [Malaria Detection (Part 1: Introduction and Data Preparation)](../posts/malaria-detection-1/)
   - [Malaria Detection (Part 2: Model Building and Training)](../posts/malaria-detection-2/)
   - [Malaria Detection (Part 3: Results and Reflections)](../posts/malaria-detection-3/)
   - [Malaria Detection (Part 4: Finetuning VGG16 with LoRA)](../posts/malaria-detection-4/)
 - GitHub Repository: [data-science](https://github.com/steveya/data-science/blob/main/notebook/malaria-detection/malaria-detection.ipynb)

## Short Rate Models
I have been planning on writing a series on some of the interesting short-rate models that I have encountered in the past. There are just so many models that it is impossible to cover them all. If you have any suggestions, please let me know!
 - Blog Post: 
   - [Short Rate Models (Part 1: Introducing Merton's Model)](../posts/short-rate-models-1/)
   - [Short Rate Models (Part 2: Simulating and Calibrating Merton's Model)](../posts/short-rate-models-2/)
   - [Short Rate Models (Part 3: Introducing Vasicek Model)](../posts/short-rate-models-3/)
   - [Short Rate Models (Part 4: Simulating and Calibrating Vasicek Model)](../posts/short-rate-models-4/)
   - [WIP Short Rate Models (Part 5: Introduction to Affine Term-Structure Model)](#)
   - [WIP Short Rate Models (Part 6: Pinning Down the Risk Premium - Kim-Orphanides (2008))](#)
   - [WIP Short Rate Models (Part 7: How About Macro? Ang and Piazzesi (2003))](#)
   - [WIP Short Rate Models (Part 8: Short-Rate and Taylor Rule. Smith and Taylor (2008))](#)
   - [WIP Short Rate Models (Part 9: Local Momentum. Duan (2016))](#)
 - WIP GitHub Repository: [short-rate-models](https://github.com/steveya/short-rate-models)

## Nowcasting
My step-by-step guide to implement a nowcasting model (based on dynamic factor model framework) from scratch in Python.
 - Blog Post: 
   - [WIP Roll Your Own Nowcasts (Part 1)](#)

## Teaching Kids Math
I have been teaching kids math ever since I have kids. I want to start writing down some of them and made them into videos if possible. I need a lot of help with the video part...
 - Blog Post: 
   - [WIP Teaching Kids Math - Arcsin Law (Part 1: Examples)](#)
   - [WIP Teaching Kids Math - Arcsin Law (Part 2: Intuition)](#)