#!/usr/bin/env python3
"""Generate Quarto index pages from post metadata.

This script scans published posts under posts/*/index.qmd and posts/*/index.ipynb,
then writes generated index pages for series, notes, projects, and categories.
"""

from __future__ import annotations

import json
import re
from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError:
    yaml = None

ROOT = Path(__file__).resolve().parent.parent
POSTS_DIR = ROOT / "posts"
PAGES_DIR = ROOT / "pages"
PROJECTS_FILE = ROOT / "data" / "projects.yml"

GENERATED_HEADER = (
    "<!-- Generated by scripts/generate_indexes.py. Do not edit manually. -->"
)
CATEGORY_ORDER = [
    "Quantitative Finance",
    "Volatility Modeling",
    "Time Series",
    "Interest Rate Models",
    "Stochastic Processes",
    "Signature Methods",
    "Trading Strategies",
    "Machine Learning",
    "Computer Vision",
    "Deep Learning",
    "Healthcare AI",
    "Statistics",
    "Linear Models",
    "Optimization",
    "Rates",
    "Dimensionality Reduction",
    "Regularization",
]


@dataclass
class PostMeta:
    slug: str
    source_path: Path
    source_type: str
    title: str
    date: str
    description: str = ""
    categories: list[str] = field(default_factory=list)
    draft: bool = False
    content_type: str = "note"
    series_id: str | None = None
    series_title: str | None = None
    series_part: int | None = None
    project_ids: list[str] = field(default_factory=list)

    @property
    def url(self) -> str:
        return f"../posts/{self.slug}/"

    @property
    def display_date(self) -> str:
        return self.date


@dataclass
class Project:
    id: str
    title: str
    order: int
    status: str
    summary: str
    repo_links: list[dict[str, str]] = field(default_factory=list)


class MetadataError(RuntimeError):
    pass


PART_RE = re.compile(r"\(Part\s*(\d+)[:\-\u2014\)]", re.IGNORECASE)
SLUG_PART_RE = re.compile(r"-(\d+)$")


def _split_top_level(value: str, separator: str) -> list[str]:
    parts: list[str] = []
    current: list[str] = []
    depth = 0
    quote: str | None = None

    for char in value:
        if quote:
            current.append(char)
            if char == quote:
                quote = None
            continue

        if char in {'"', "'"}:
            quote = char
            current.append(char)
            continue

        if char == "[":
            depth += 1
        elif char == "]":
            depth -= 1

        if char == separator and depth == 0:
            parts.append("".join(current).strip())
            current = []
            continue

        current.append(char)

    parts.append("".join(current).strip())
    return [part for part in parts if part]


def _split_key_value(line: str) -> tuple[str, str | None]:
    quote: str | None = None
    depth = 0

    for index, char in enumerate(line):
        if quote:
            if char == quote:
                quote = None
            continue

        if char in {'"', "'"}:
            quote = char
            continue
        if char == "[":
            depth += 1
            continue
        if char == "]":
            depth -= 1
            continue
        if char == ":" and depth == 0:
            key = line[:index].strip()
            value = line[index + 1 :].strip()
            return key, value if value else None

    raise MetadataError(f"Could not parse YAML line: {line}")


def _parse_scalar(value: str) -> Any:
    if value in {"true", "True"}:
        return True
    if value in {"false", "False"}:
        return False
    if value in {"null", "Null", "none", "None", "~"}:
        return None

    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [_parse_scalar(part) for part in _split_top_level(inner, ",")]

    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        return value[1:-1]

    if re.fullmatch(r"-?\d+", value):
        return int(value)

    return value


def _parse_yaml_block(lines: Sequence[str], start: int, indent: int) -> tuple[Any, int]:
    index = start
    while index < len(lines) and not lines[index].strip():
        index += 1

    if index >= len(lines):
        return {}, index

    stripped = lines[index].lstrip()
    current_indent = len(lines[index]) - len(stripped)
    if current_indent < indent:
        return {}, index

    if stripped.startswith("- "):
        items: list[Any] = []
        while index < len(lines):
            line = lines[index]
            if not line.strip():
                index += 1
                continue

            stripped = line.lstrip()
            current_indent = len(line) - len(stripped)
            if current_indent < indent or not stripped.startswith("- "):
                break

            remainder = stripped[2:].strip()
            index += 1
            if not remainder:
                nested, index = _parse_yaml_block(lines, index, indent + 2)
                items.append(nested)
                continue

            try:
                key, value = _split_key_value(remainder)
            except MetadataError:
                items.append(_parse_scalar(remainder))
                continue
            if value is None:
                nested, index = _parse_yaml_block(lines, index, indent + 2)
                item = {key: nested}
            else:
                item = {key: _parse_scalar(value)}

            continuation, new_index = _parse_yaml_block(lines, index, indent + 2)
            if isinstance(continuation, dict) and continuation:
                item.update(continuation)
                index = new_index
            items.append(item)

        return items, index

    mapping: dict[str, Any] = {}
    while index < len(lines):
        line = lines[index]
        if not line.strip():
            index += 1
            continue

        stripped = line.lstrip()
        current_indent = len(line) - len(stripped)
        if current_indent < indent:
            break
        if current_indent > indent:
            raise MetadataError(f"Unexpected indentation in YAML: {line}")

        key, value = _split_key_value(stripped)
        index += 1
        if value is None:
            nested, index = _parse_yaml_block(lines, index, indent + 2)
            mapping[key] = nested
        else:
            mapping[key] = _parse_scalar(value)

    return mapping, index


def load_yaml_text(text: str) -> Any:
    if yaml is not None:
        return yaml.safe_load(text) or {}

    lines = text.splitlines()
    parsed, _ = _parse_yaml_block(lines, 0, 0)
    return parsed or {}


def load_projects() -> list[Project]:
    data = load_yaml_text(PROJECTS_FILE.read_text(encoding="utf-8"))
    projects = []
    for item in data.get("projects", []):
        projects.append(
            Project(
                id=item["id"],
                title=item["title"],
                order=int(item.get("order", 999)),
                status=item.get("status", "active"),
                summary=item.get("summary", "").strip(),
                repo_links=list(item.get("repo_links", [])),
            )
        )
    return sorted(projects, key=lambda p: (p.order, p.title.lower()))


def normalize_date(value: Any) -> str:
    if isinstance(value, datetime):
        return value.date().isoformat()
    if isinstance(value, date):
        return value.isoformat()
    return str(value).strip().strip('"').strip("'")


def ensure_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v).strip() for v in value if str(v).strip()]
    return [str(value).strip()] if str(value).strip() else []


def extract_qmd_frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise MetadataError(f"Missing frontmatter start in {path}")
    _, _, rest = text.partition("---\n")
    frontmatter, sep, _ = rest.partition("\n---")
    if not sep:
        raise MetadataError(f"Missing frontmatter end in {path}")
    return load_yaml_text(frontmatter)


def extract_notebook_frontmatter(path: Path) -> dict[str, Any]:
    notebook = json.loads(path.read_text(encoding="utf-8"))
    cells = notebook.get("cells", [])
    if not cells:
        raise MetadataError(f"Notebook has no cells: {path}")
    first = cells[0]
    if first.get("cell_type") != "markdown":
        raise MetadataError(f"First notebook cell is not markdown: {path}")
    source = first.get("source", [])
    text = "\n".join(str(line).rstrip("\n") for line in source)
    if not text.startswith("---"):
        raise MetadataError(f"Notebook frontmatter not found in first cell: {path}")

    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise MetadataError(f"Notebook frontmatter malformed: {path}")

    frontmatter_lines: list[str] = []
    for line in lines[1:]:
        if line.strip() == "---":
            break
        frontmatter_lines.append(line)

    frontmatter = "\n".join(frontmatter_lines).strip()
    if not frontmatter:
        raise MetadataError(f"Notebook frontmatter malformed: {path}")
    return load_yaml_text(frontmatter)


def infer_series_part(title: str, slug: str) -> int | None:
    match = PART_RE.search(title)
    if match:
        return int(match.group(1))
    slug_match = SLUG_PART_RE.search(slug)
    if slug_match:
        return int(slug_match.group(1))
    return None


def infer_series_id(slug: str) -> str | None:
    slug_match = SLUG_PART_RE.search(slug)
    if slug_match:
        return slug[: slug_match.start()]
    return None


def infer_series_title(title: str) -> str | None:
    if "Part" not in title:
        return None
    base = re.sub(r"\s*\(Part\s*\d+.*?\)", "", title, flags=re.IGNORECASE)
    base = re.sub(r"\s*[\-\u2014]\s*Part\s*\d+.*$", "", base, flags=re.IGNORECASE)
    return base.strip() or None


def load_posts(project_ids: set[str]) -> list[PostMeta]:
    posts: list[PostMeta] = []
    for post_dir in sorted(p for p in POSTS_DIR.iterdir() if p.is_dir()):
        qmd_path = post_dir / "index.qmd"
        ipynb_path = post_dir / "index.ipynb"
        if qmd_path.exists():
            meta = extract_qmd_frontmatter(qmd_path)
            source_path = qmd_path
            source_type = "qmd"
        elif ipynb_path.exists():
            meta = extract_notebook_frontmatter(ipynb_path)
            source_path = ipynb_path
            source_type = "ipynb"
        else:
            continue

        slug = post_dir.name
        title = str(meta.get("title", slug)).strip()
        description = str(meta.get("description", "")).strip()
        post = PostMeta(
            slug=slug,
            source_path=source_path,
            source_type=source_type,
            title=title,
            date=normalize_date(meta.get("date", "")),
            description=description,
            categories=ensure_list(meta.get("categories")),
            draft=bool(meta.get("draft", False)),
            content_type=str(meta.get("content-type", "")).strip() or "",
            series_id=str(meta.get("series-id", "")).strip() or None,
            series_title=str(meta.get("series-title", "")).strip() or None,
            series_part=meta.get("series-part"),
            project_ids=ensure_list(meta.get("project-ids")),
        )

        if not post.content_type:
            inferred_part = infer_series_part(post.title, post.slug)
            post.content_type = "series" if inferred_part else "note"
        if post.series_part is None and post.content_type == "series":
            post.series_part = infer_series_part(post.title, post.slug)
        if not post.series_id and post.content_type == "series":
            post.series_id = infer_series_id(post.slug)
        if not post.series_title and post.content_type == "series":
            post.series_title = infer_series_title(post.title)
        if not post.project_ids and post.series_id and post.series_id in project_ids:
            post.project_ids = [post.series_id]

        posts.append(post)
    return sorted(posts, key=lambda p: (p.date, p.title.lower()), reverse=True)


def validate_posts(posts: list[PostMeta], project_ids: set[str]) -> None:
    series_seen: dict[str, set[int]] = {}
    for post in posts:
        if post.draft:
            continue
        if not post.date:
            raise MetadataError(f"Missing date for {post.source_path}")
        if not post.categories:
            raise MetadataError(f"Missing categories for {post.source_path}")
        unknown_projects = [pid for pid in post.project_ids if pid not in project_ids]
        if unknown_projects:
            raise MetadataError(
                f"Unknown project ids {unknown_projects} in {post.source_path}"
            )
        if post.content_type == "series":
            if not post.series_id or not post.series_title or post.series_part is None:
                raise MetadataError(f"Incomplete series metadata in {post.source_path}")
            seen_parts = series_seen.setdefault(post.series_id, set())
            if post.series_part in seen_parts:
                raise MetadataError(
                    f"Duplicate series-part {post.series_part} for series {post.series_id}"
                )
            seen_parts.add(post.series_part)


def published_posts(posts: list[PostMeta]) -> list[PostMeta]:
    return [post for post in posts if not post.draft]


def section_title(project: Project) -> str:
    if project.status == "wip":
        return f"{project.title} (WIP)"
    return project.title


def format_post_bullet(post: PostMeta, include_date: bool = False) -> str:
    suffix = f" ({post.display_date})" if include_date else ""
    if post.description:
        return f"- [{post.title}]({post.url}){suffix}: {post.description}"
    return f"- [{post.title}]({post.url}){suffix}"


def render_series_page(
    posts: list[PostMeta], project_lookup: dict[str, Project]
) -> str:
    series_posts = [post for post in posts if post.content_type == "series"]
    grouped: dict[str, list[PostMeta]] = {}
    for post in series_posts:
        grouped.setdefault(post.series_id or post.slug, []).append(post)
    order_map = {project.id: project.order for project in project_lookup.values()}
    series_ids = sorted(
        grouped,
        key=lambda sid: (
            order_map.get(sid, 999),
            (grouped[sid][0].series_title or sid).lower(),
        ),
    )

    lines = [
        "---",
        'title: "Series"',
        "page-layout: full",
        "title-block-banner: false",
        "---",
        "",
        GENERATED_HEADER,
        "",
        "A generated index of multi-part series.",
        "",
    ]

    for series_id in series_ids:
        items = sorted(grouped[series_id], key=lambda post: post.series_part or 0)
        title = items[0].series_title or items[0].title
        lines.append(f"## {title}")
        project = project_lookup.get(series_id)
        if project and project.summary:
            lines.append(project.summary)
            lines.append("")
        for post in items:
            lines.append(format_post_bullet(post, include_date=False))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_notes_page(posts: list[PostMeta]) -> str:
    note_posts = [post for post in posts if post.content_type == "note"]
    lines = [
        "---",
        'title: "Notes"',
        "page-layout: full",
        "title-block-banner: false",
        "---",
        "",
        GENERATED_HEADER,
        "",
        "A generated index of standalone technical notes and essays.",
        "",
    ]
    if not note_posts:
        lines.append("No standalone notes have been published yet.")
        lines.append("")
    else:
        for post in note_posts:
            lines.append(format_post_bullet(post, include_date=True))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_projects_page(posts: list[PostMeta], projects: list[Project]) -> str:
    published = published_posts(posts)
    by_project: dict[str, list[PostMeta]] = {project.id: [] for project in projects}
    for post in published:
        for project_id in post.project_ids:
            by_project.setdefault(project_id, []).append(post)

    lines = [
        "---",
        'title: "Projects"',
        "icon: fas fa-book",
        "order: 1",
        "---",
        "",
        GENERATED_HEADER,
        "",
        "A generated map of long-running projects, related series, and standalone notes.",
        "",
        "Projects marked as Work in Progress (WIP) are still in progress and may not be fully functional.",
        "",
    ]

    for project in projects:
        related = by_project.get(project.id, [])
        series_posts = sorted(
            [post for post in related if post.content_type == "series"],
            key=lambda post: (
                0 if post.series_id == project.id else 1,
                (post.series_title or "").lower(),
                post.series_part or 0,
                post.date,
            ),
        )
        note_posts = sorted(
            [post for post in related if post.content_type == "note"],
            key=lambda post: post.date,
            reverse=True,
        )

        lines.append(f"## {section_title(project)}")
        if project.summary:
            lines.append(project.summary)
            lines.append("")

        if project.repo_links:
            for link in project.repo_links:
                link_text = link.get("text", link["url"])
                lines.append(f"- {link['label']}: [{link_text}]({link['url']})")
            lines.append("")

        if series_posts:
            lines.append("### Series")
            for post in series_posts:
                lines.append(format_post_bullet(post, include_date=False))
            lines.append("")

        if note_posts:
            lines.append("### Related Notes")
            for post in note_posts:
                lines.append(format_post_bullet(post, include_date=True))
            lines.append("")

        if not series_posts and not note_posts:
            lines.append("Writing for this project is not published yet.")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_categories_page(posts: list[PostMeta]) -> str:
    category_map: dict[str, list[PostMeta]] = {}
    for post in published_posts(posts):
        for category in post.categories:
            category_map.setdefault(category, []).append(post)

    def category_sort_key(name: str) -> tuple[int, str]:
        try:
            return (CATEGORY_ORDER.index(name), name.lower())
        except ValueError:
            return (len(CATEGORY_ORDER) + 1, name.lower())

    lines = [
        "---",
        'title: "Categories"',
        "page-layout: full",
        "title-block-banner: false",
        "---",
        "",
        GENERATED_HEADER,
        "",
        "A generated topic index built from published post metadata.",
        "",
    ]

    for category in sorted(category_map, key=category_sort_key):
        lines.append(f"## {category}")
        for post in sorted(category_map[category], key=lambda p: p.date, reverse=True):
            lines.append(format_post_bullet(post, include_date=True))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_page(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def main() -> int:
    projects = load_projects()
    project_lookup = {project.id: project for project in projects}
    project_ids = set(project_lookup)
    posts = load_posts(project_ids)
    validate_posts(published_posts(posts), project_ids)

    write_page(
        PAGES_DIR / "series.qmd",
        render_series_page(published_posts(posts), project_lookup),
    )
    write_page(PAGES_DIR / "notes.qmd", render_notes_page(published_posts(posts)))
    write_page(PAGES_DIR / "projects.qmd", render_projects_page(posts, projects))
    write_page(PAGES_DIR / "categories.qmd", render_categories_page(posts))

    print("Generated pages:")
    print("- pages/series.qmd")
    print("- pages/notes.qmd")
    print("- pages/projects.qmd")
    print("- pages/categories.qmd")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
